## 제1절 부동산학의 이해

### [1] 부동산학의 정의

* 부동산활동의 능률화의 원리 및 그 응용기술을 개척하는 **종합응용과학**이다.
* 부동산의 가치증진과 관련된 의사결정과정을 연구하기 위하여 부동산에 대해 법적·경제적·기술적 측면에서 접근을 시도하는 종합응용과학이다.
* 토지와 토지에 연결되어 있는 항구적인 토지개량물에 관하여 그것과 관련된 직업적·물적·법적·금융적 측면들을 기술하고 분석하는 학문연구의 한 분야이다.
* 부동산활동을 연구하여 인간과 부동산 간의 관계를 개선하고자 하는 이론적 체계이다.

### [2] 부동산학의 학문적 성격

인간사회의 여러 현상을 과학적·체계적으로 연구하는 사회과학에 해당되며 구체적으로 인간과 부동산의 상호작용을 연구한다. 순수과학과 달리 복잡한 현실적 사회문제를 해결하고자 하는 **응용과학**이다. 부동산활동과 현상을 연구할 때 경제학·법학·행정학·사회학·심리학 등 여러 분야의 학문과 연계되어 있다는 점에서 **종합과학**의 성격을 지닌다. 또한 실천과학이며, 경험과학, 규범과학에 해당한다.

사회과학::  
  인간과 부동산의 상호작용을 연구한다.

실천과학::
  부동산활동의 원리와 그 응용기술을 부동산행위의 기본으로 삼는 실천 과학이다.

응용과학::
  부동산문제 해결을 위한 기술적인 실천방법을 제시하고 유용성을 검증할 수 있는 응용과학이다, 순수과학과는 달리 복잡한 현실적 문제를 해결한다.

경험과학::
  추상적이 아닌 현실의 부동산활동을 대상으로 하는 구체적인 경험과학이다.

종합과학::

  부동산 활동과 현상을 연구할 때 경제학·법학·행정학·사회학·심리학 등과 연계된 종합과학이다.

규범과학::

  부동산현상을 보고 어떤 부동산행위가 사회적으로 바람직한 것인가를 밝히고 판단할 수 있는 규범과학이다. 

### [3] 부동산학의 여러 측면과 복합개념

부동산의 개념과 범위는 인간의 눈에 비치는 유형적(기술적) 측면과 관념적으로만 인식하는 무형적(법률적, 경제적) 측면으로 파악할 수 있다.
부동산학은 여러 부동산현상을 이해하고 분석하거나 부동산결정을 행하고 부동산활동을 전개해 나가기 위해 주로 복합개념의 사고원리를 사용한다. 
따라서 부동산을 유형·무형의 법률·경제·기술 측면이 복합된 개념으로 이해하는 것으로 부동산할동을 위한 의사결정에 중요하다.


## 제2절 부동산학의 연구대상과 연구분야

### [1] 부동산학의 연구대상

부동산활동 및 부동산현상이 연구 대상이다.

부동산현상::

  부동산에서 비롯된 모든 기술·경제·제도 및 기타 제 현상을 말한다. 인간의 부동산활동으로부터 생기기도 하지만 부동산의 본질로부터 오는 경우도 있다.

부동산활동::

  부동산과 인간의 관계로서 인간이 부동산을 대상으로 전개하는 관리적 면의 여러가지 행위를 말한다.

### [2] 부동산학의 연구분야

부동산을 구성하는 각 분야가 공통적으로 어떤 기능과 역할을 수행하고 있느냐에 따라 부동산결정분야, 부동산결정 지원분야, 부동산학의 기초분야로 나뉜다. +
일반적으로 부동산이 일반 재화에 비해 거래비용이 크고 부동산이용의 비가역적 특성 때문에 의사결정 지원분야의 역할이 더욱 중요하다.

### [3] 부동산학의 접근방법

종합식::

  부동산을 기술적·경제적·법률적 측면 등의 복합개념으로 종합하여 이론을 구축하는 방법이다.

분산식::

  일반적 주변과학(법학·경제학·공학 등)에 의하여 각기 개별적·부분적으로 부동산을 다루는 방법이다.

중점식::

  부동산과 부동산활동의 특정 측면(법률적 접근·경제적 접근·기술적 접근)에만 중점을 두는 방법이다.

법적·제도적::

  이론적 기초를 법률과 제도에 두는 방법이다.

현상학적::

  토지를 객체로 근대성을 지적하고 토지는 인간의 노동의 산물이 아니므로 그 자체는 아무런 가치가 없다고 본다. 따라서 자연인 토지를 대상으로 하는 활동은 인간세상과 토지를 함께 보는 것에서 출발한다고 본다.

행태과학적::

  부동산활동에 내재하는 인간적 요인에 착안항 부동산행태를 중심으로 부동산활동의 본질을 규명하는 방법이다. 최근 부동산경영·마케팅·중개이론 등을 과학화하는데 이 접근방법이 채택되는 경향이 증가하고 있다.

의사결정 접근방법::

  인간은 합리적인 존재이며 자기이윤의 극대화를 목표로 활동한다는 기본 가정에서 출발한다. +
  부동산활동을 하는 인간은 논리적이고 에측 가능한 사고과정이나 의사결정과정을 만들고, 항상 자기이윤의 극대화를 위한 행동에서 가장 개인적인 이익을 주는 선택이나 대안을 택한다는 것이다.


## 제3절 부동산학의 이론

### [1] 일반적인 이념의 방향

합법성::

  부동산현상과 부동산활동이 적법하게 이루어져야 한다.

효율성::

  효율성은 경제학 논리와 관련이 깊으며 일정한 투입수준에서 최대의 산출을 얻자는 것이다.  부동산의 최유효이용이란 부동산의 효율적 이용을 의미한다. <br>
  효율성은 주로 사적 주체의 행동이념이다.

형평성::

  사회의 특정 세력이나 계층으로 치우치지 않는 상태를 의미한다. 공정과 불공정 등에 적용되는 개념으로 사회정의를 고려하며 사회적 공평·평등·분배정의 등으로 표현된다.

### [2] 부동산학의 지도이념

공·사익 조화의 원리 - 법률적 측면::

  사익이 개인의 이익이라면 공익은 불특정 다수의 이익을 의미한다. 부동산의 특성에서 기인하는 많은 공·사법상의 여러 규율이 부동산활동에 영향을 주며
  그로 인해 부동산현상을 변화시킨다는 점에서 공·사익 조화의 원리가 중요하다는 것이다.

효율적 관리의 원리 - 경제적 측면::

  부동산의 보존과 이용 및 개발 등 관리가 효율적이어야 한다는 경제적 측면의 지도이념이다.


공간 및 환경가치 증대의 원리 - 기술적 측면::

  한정된 자연적 공간을 인간생활의 욕구에 부응하도록 기술혁신을 통해 공간활용을 증대하고 환경가치를 증대하여야 한다는 기술적 특면의 지도이다.

### [3] 부동산학에서 추구하는 가치

형평보다는 효율을 중시한다. 그러나 사회 전체적으로는 형평성도 중요하다.
하지만 현실에서는 효율성이 강조하다보면 형평성이 훼손되고, 형평성을 강조하면 효율성이 저해되는 문제가 자주 발생한다.


## 제4절 부동산활동과 부동산현상

### [1] 부동산활동과 부동산현상

부동산활동은 부동산을 대상으로 전개하는 인간의 관리적 측면에서의 행위를 말한다. 부동산현상은 부동산에서 비롯된 기술·경제·제도 등의 모든 현상을 말한다.

### [2] 부동산활동의 주체

부동산활동의 주체는 공적부문, 사적부문, 전문협회 등으로 나눌 수 있다.

공적부문(정부)::

  주로 부동산의 관리·규제·보조·과세 등으로 나타낸다.

사적부문(민간)::

  부동산 개발업·평가업·중개업·금융업·괸리업 등으로 나타나며, 다른 부문들의 활동에 비해 가장 활발하다

전문협회::

  공인중개사협회나 감정평가사협회, 주택관리사협회 등의 활동을 말한다.  이 부문은 교육 프로그램의 제공, 새로운 정보의 교환 및 제공, 연구 및 출판물의 간행, 회원들의 자질향상과 권익보호활동 등을 주로 한다.

### [3] 부동산활동의 속성

과학성 및 기술성::

  부동산활동은 부동산이론의 능률화에 과학성으로, 부동산실무의 능률화에 기술성으로 기여한다.

사회성·공공성::

  토지는 국토공간으로 용도가 다양하며 국가 존립에 매우 중요하다. 특히 주택은 환경성이 있으며 졍제 비중이 크다.

사익성::

  공익성을 해치지 않는 한 국민의 사익을 존중한다.

전문성::

  높은 전문성이 요구되므로 공인자격제를 도입하고 있다.

윤리성::

  사회성·공공성이 강조되므로 부동산업자에게 직업윤리를 요구한다. 유형으로 는 고용, 조직, 서비스, 공중 유형이 있다. 

====
**부동산윤리의 유형**

고용 윤리::

  자신은 물론 자신이 고용한 종업원들이 법규와 윤리 규정을 준수하도록 지도·감독한다.

조직 윤리::

  동업자에게 불이익을 주지 않아야 하며 동업자단체에 가입하여 단체의 일원으로서 역할과 기능을 성실하게 협력한다.   

서비스 윤리::

  의뢰인의 관계에서 지켜야할 중심적인 윤리이다.

공중 윤리::

  부동산기업가는 일반공중이 복리를 증진하는 방향으로 업무활동을 전개한다.
====

정보활동::

  부동산활동의 대부분은 정보활동이다. 부동산은 부동성이 있고 주변현상에 통제 불가능한 요인이 많으므로 정보활동이 중요하다.

대인활동 및 대물활동::

  직간접적으로 여러 사람이 관여하는 대인활동이므로 대인관계 증진의 노력이 요구되며 기술적 전문지식과 함께 효과적인 대물활동이 필요하다.

임장활동::

  사무실보다는 현장에서 많은 시간을 보내는 것을 임장활동이라고 한다. 부동산결정에 필요한 여러 사항은 서면만으로 정확하게 파악하기 어려우므로 물리적 상태를 직접 확인·분석한다.

공간활동::

  부동산은 수평·공중·지중 공간을 대상으로 부동산활동을 전개한다. 거래활동의 대상은 3차원 공간이다.

배려의 장기성::

  부동산은 '영속성'과 '용도의 다양성'이 있으므로 일반 소비상품에 대한 활동과 달리 장기적 배려하에 결정되고 실행된다. 여기에는 필수적으로 '사회·행정·경제적 위치의 가변성'에 대한 배려가 수반된다.

복합개념::

  부동산활동은 사고방식이 복합개념을 토대로 한다.

### [4] 부동산활동의 일반원칙

**능률적으로**::

  부동산학은 부동산활동의 능률화를 목표로 한다. 
  부동산활동은 소유활동에서는 최유효이용의 원칙을, 거래활동에서는 거래질서 확립의 원칙이 지도원리이다.

**안전하게**::

  거래사고와 관련하여 안전성을 강력하게 의식하여야 한다.
  특히 안정성의 개념에 있어서는 복합관계의 논리에 따라서 법률적·경제적·기술적 안정성을 고려하여야 한다.

**경제적으로**::

  경제성 원칙은 최소의 희생으로 최대의 효과를 올리려는 것이 일반적이다. 
이 원칙은 부동산활동 전반에 걸친 합리적 선택의 원칙이라고 할 수 있다.

**공정하게**::

  부동산은 사회성과 공공성을 갖는 재화이므로 그것을 대상으로 하는 활동도 공정성이 요구된다.

