2과목 : 민법 및 민사특별법

#### [2015-41] 통정허위표시의 무효는 선의의 ‘제3자’에게 대항하지 못한다는 규정의 ‘제3자’에 해당하는 자를 모두 고른 것은?(다툼이 있으면 판례에 따름)
====
ㄱ. 통정허위표시에 의한 채권을 가압류한 자
ㄴ. 통정허위표시에 의해 설정된 전새권에 대해 저당권을 설정 받은 자
ㄷ. 대리인의 통정허위표시에서 본인
ㄹ. 통정허위표기에 의해 체결된 제3자를 위한 계약에서 제3자
====
① ㄱ, ㄴ
② ㄱ, ㄷ
③ ㄴ, ㄷ
④ ㄴ, ㄹ
⑤ ㄷ, ㄹ

#### [2015-42] 준법률행위인 것은?(다툼이 있으면 판례에 따름)
① 법정대리인의 동의
② 착오에 의한 의사표시의 취소
③ 채무이행의 최고
④ 무권대리행위에 대한 추인
⑤ 임대차계약의 해지

#### [2015-43] 甲은 토지거래허가구역 내 자신의 토지를 乙에게 매도하였고 곧 토지거래허가를 받기로 하였다. 다음 설명 중 옳은 것을 모두 고른 것은?(다툼이 있으면 판례에 따름)
====
ㄱ. 갑과 을은 토지거래허가신청절차에 협력할 의무가 있다.
ㄴ. 갑은 계약상 채무불이행을 이유로 계약을 해제할 수 있다.
ㄷ. 계약이 현재 유동적 무효 상태라는 이유로 을은 이미 지급한 계약금 등을 부당이득으로 반환청구할 수 있다.
ㄹ. 을은 토지거래허가가 있을 것을 조건으로 하여 갑을 상대로 소유권이전등기절차의 이행을 청구할 수 없다.
====
① ㄱ, ㄴ, ㄹ
② ㄱ, ㄷ
③ ㄱ, ㄹ
④ ㄴ, ㄷ
⑤ ㄴ, ㄹ

#### [2015-44] 반사회질서의 법률행위로서 무효인 것을 모두 고른 것은?(다툼이 있으면 판례에 따름)
====
ㄱ. 무허가 건물의 임대행위
ㄴ. 처음부터 보험사고를 가장하여 보험금을 취할 목적으로 체결한 보험계약
ㄷ. 변호사가 민사소송의 승소 대가로 성공보수를 받기로 한 약정
ㄹ. 수사기관에서 참고인으로서 자신이 잘 알지못하는 내용에 대한 허위진술을 하고 대가를 제공받기도 하는 약정
====
① ㄱ, ㄴ② ㄴ
③ ㄴ, ㄹ④ ㄷ
⑤ ㄷ, ㄹ

#### [2015-45] 무권대리에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 무권대리행위의 일부에 대한 추인은 상대방의 동의를 얻지 못하는 한 효력이 없다.
② 무권대리행위를 추인한 경우 원칙적으로 추인한 때로부터 유권대리와 마찬가지의 효력이 생긴다.
③ 무권대리행위의 추인의 의사표시는 본인이 상대방에게 하지 않으면, 상대방이 그 사실을 알았더라도 상대방에게 대항하지 못한다.
④ 무권대리인의 계약상대방은 계약 당시 대리권 없음을 안 경우에도 본인에 대해 계약을 철회할 수 있다.
⑤ 무권대리행위가 무권대리인의 과실없이 제3자의 기망 등 위법행위로 야기된 경우, 특별한 사정이 없는 한 무권대리인은 상대방에게 책임을 지지 않는다.

#### [2015-46] 甲은 자신의 X토지를 乙에게 매도하고 중도금을 수령한 후, 다시 丙에게 매도하고 소유권이전등기까지 경료해 주었다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 따름)
① 특별한 사정이 없는 한 丙은 X토지의 소유권을 취득한다.
② 특별한 사정이 없는 한 乙은 최고 없이도 甲과의 계약을 해제할 수 있다.
③ 丙이 甲의 乙에 대한 배임행위에 적극 가담한 경우, 乙은 丙을 상대로 직접 등기의 말소를 청구할 수 없다.
④ 甲과 丙의 계약이 사회질서 위반으로 무효인 경우, 丙으로부터 X토지를 전득한 丁은 선의이더라도 그 소유권을 취득하지 못한다.
⑤ 만약 丙의 대리인 戊가 丙을 대리하여 X토지를 매수하면서 甲의 배임행위에 적극 가담하였다면, 그러한 사정을 모르는 丙은 그 소유권을 취득한다.

#### [2015-47] 표현대리에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 상대방의 유권대리 주장에는 표현대리의 주장도 포함된다.
② 권한을 넘은 표현대리의 기본대리권은 대리행위와 같은 종류의 행위에 관한 것이어야 한다.
③ 권한을 넘은 표현대리의 기본대리권에는 대리인에 의하여 선임된 복대리인의 권한도 포함된다.
④ 대리권수여표시에 의한 표현대리에서 대리권수여표시는 대리권 또는 대리인이라는 표현을 사용한 경우에 한정 된다.
⑤ 대리권소멸 후의 표현대리가 인정되고 그 표현대리의 권한을 넘는 대리행위가 있는 경우, 권한을 넘은 표현 대리가 성립할 수 없다.

#### [2015-48] 미성년자 甲은 법정대리인 丙의 동의없이 자신의 토지를 甲이 미성년자임을 안 乙에게 매도하고 대금수령과 동시에 소유권이전등기를 해주었는데, 丙이 甲의 미성년을 이유로 계약을 적법하게 취소하였다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 따름)
① 계약은 소급적으로 무효가 된다.
② 甲이 미성년자임을 乙이 몰랐더라도 丙은 계약을 취소 할 수 있다.
③ 甲과 乙의 반환의무는 서로 동시이행관계에 있다.
④ 甲이 대금을 모두 생활비로 사용한 경우 대금 전액을 반환하여야 한다.
⑤ 만약 乙이 선의의 丁에게 매도하고 이전등기하였다면, 丙이 취소하였더라도 丁은 소유권을 취득한다.

#### [2015-49] 착오에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 매도인이 계약을 적법하게 해제한 후에도 매수인은 계약해제에 따른 불이익을 면하기 위하여 중요부분의 착오를 이유로 취소권을 행사하여 계약 전체를 무효로 할 수 있다.
② 표의자가 착오를 이유로 의사표시를 취소한 경우, 취소된 의사표시로 인해 손해를 입은 상대방은 불법행위를 이유로 손해배상을 청구할 수 있다.
③ 착오에 의한 의사표시로 표의자가 경제적 불이익을 입지 않더라도 착오를 이유로 그 의사표시를 취소할 수 있다.
④ 착오가 표의자의 중대한 과실로 인한 경우에는 상대방이 표의자의 착오를 알고 이용하더라도 표의자는 의사표시를 취소할 수 없다.
⑤ 표의자의 중대한 과실 유무는 착오에 의한 의사표시의 효력을 부인하는 자가 증명하여야 한다.

#### [2015-50] 乙은 甲의 X토지에 건물을 소유하기 위하여 지상권을 설정받았다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 따름)
① 乙은 甲의 의사에 반하여 제3자에게 지상권을 양도할 수 없다.
② X토지를 양수한 자는 지상권의 존속 중에 乙에게 그 토지의 인도를 청구할 수 없다.
③ 乙이 약정한 지료의 1년 6개월분을 연체한 경우, 甲은 지상권의 소멸을 청구할 수 있다.
④ 존속기간의 만료로 지상권이 소멸한 경우, 건물이 현존하더라도 乙은 계약의 갱신을 청구할 수 없다.
⑤ 지상권의 존속기간을 정하지 않은 경우, 甲은 언제든지 지상권의 소멸을 청구할 수 있다.

#### [2015-51] 제사주재자인 장남 甲은 1985년 乙의 토지에 허락 없이 부친의 묘를 봉분 형태로 설치한 이래 2015년 현재까지 평온ㆍ공연하게 분묘의 기지(基地)를 점유하여 분묘의 수호와 봉사를 계속하고 있다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 따름)
① 乙은 甲에게 분묘의 이장을 청구할 수 있다.
② 甲은 乙에게 분묘기지에 대한 소유권이전등기를 청구할 수 있다.
③ 甲은 부친의 묘에 모친의 시신을 단분(單墳) 형태로 합장할 권능이 있다.
④ 甲이 분묘기지권을 포기하는 의사를 표시한 경우 점유의 포기가 없더라도 분묘기지권이 소멸한다.
⑤ 甲은 乙에게 지료를 지급할 의무가 있다.

#### [2015-52] 지역권에 관한 설명으로 틀린 것은?
① 1필의 토지 일부를 승역지로 하여 지역권을 설정할 수 있다.
② 요역지의 공유자 1인이 지역권을 취득한 때에는 다른 공유자도 이를 취득한다.
③ 지역권은 요역지와 분리하여 양도하지 못한다.
④ 요역지의 소유자는 지역권에 필요한 부분의 토지소유권을 지역권설정자에게 위기(委棄)하여 공작물의 설치나 수선의무의 부담을 면할 수 있다.
⑤ 지역권자에게는 방해제거청구권과 방해예방청구권이 인정된다.

#### [2015-53] 물권에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 지상권은 본권이 아니다.
② 온천에 관한 권리는 관습법상의 물권이다.
③ 타인의 토지에 대한 관습법상 물권으로서 통행권이 인정된다.
④ 근린공원을 자유롭게 이용한 사정만으로 공원이용권이라는 배타적 권리를 취득하였다고 볼 수는 없다.
⑤ 미등기 무허가건물의 양수인은 소유권이전등기를 경료 받지 않아도 소유권에 준하는 관습법상의 물권을 취득한다.

#### [2015-54] 乙은 丙의 토지 위에 있는 甲소유의 X건물을 매수하여 대금완납 후 그 건물을 인도받고 등기서류를 교부받았지만, 아직 이전등기를 마치지 않았다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 따름)
① 甲의 채권자가 X건물에 대해 강제집행하는 경우, 乙은 이의를 제기하지 못한다.
② X건물로 인해 丙의 토지가 불법점거당하고 있다면, 丙은 乙에게 X건물의 철거를 청구할 수 있다.
③ X건물의 점유를 방해하는 자에 대해 乙은 점유권에 기한 방해제거청구권을 행사할 수 있다.
④ 乙은 X건물로부터 생긴 과실(果實)의 수취권을 가진다.
⑤ 乙로부터 X건물을 다시 매수하여 점유ㆍ사용하고 있는 丁에 대하여 甲은 소유권에 기한 물권적 청구권을 행사 할 수 있다.

#### [2015-55] 등기에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 법률행위를 원인으로 하여 소유권이전등기를 명하는 판결에 따른 소유권의 취득에는 등기를 요하지 않는다.
② 상속인은 피상속인의 사망과 더불어 상속재산인 부동산에 대한 등기를 한 때 소유권을 취득한다.
③ 피담보채권이 소멸하더라도 저당권의 말소등기가 있어야 저당권이 소멸한다.
④ 민사집행법상 경매의 매수인은 등기를 하여야 소유권을 취득할 수 있다.
⑤ 기존 건물 멸실 후 건물이 신축된 경우, 기존 건물에 대한 등기는 신축건물에 대한 등기로서 효력이 없다.

#### [2015-56] 점유에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 점유자의 점유가 자주점유인지 타주점유인지의 여부는 점유자 내심의 의사에 의하여 결정된다.
② 점유자의 점유권원에 관한 주장이 인정되지 않는다는 것만으로도 자유점유의 추정이 깨진다.
③ 점유물이 멸실ㆍ훼손된 경우, 선의의 타주점유자는 이익이 현존하는 한도 내에서 회복자에게 배상책임을 진다.
④ 악의의 점유자는 과실(過失)없이 과실(果實)을 수취하지 못한 때에도 그 과실(果實)의 대가를 회복자에게 보상 하여야 한다.
⑤ 점유자의 특정승계인이 자기의 점유와 전(前)점유자의 점유를 아울러 주장하는 경우, 그 하자도 승계한다.

#### [2015-57] 상린관계에 관한 설명으로 틀린 것은?
① 서로 인접한 토지의 통상의 경계표를 설치하는 경우, 측량비용을 제외한 설치비용은 다른 관습이 없으면 쌍방이 토지면적에 비례하여 부담한다.
② 甲과 乙이 공유하는 토지가 甲의 토지와 乙의 토지로 분할됨으로 인하여 甲의 토지가 공로에 통하지 못하게 된 경우, 甲은 공로에 출입하기 위하여 乙의 토지를 통행할 수 있으나, 乙에게 보상할 의무는 없다.
③ 인지소유자는 자기의 비용으로 담의 높이를 통상보다 높게 할 수 있다.
④ 토지소유자는 과다한 비용이나 노력을 요하지 아니하고는 토지이용에 필요한 물을 얻기 곤란한 때에는 이웃 토지소유자에게 보상하고 여수(餘水)의 급여를 청구할 수 있다.
⑤ 지상권자는 지상권의 목적인 토지의 경계나 그 근방에서 건물을 수선하기 위하여 필요한 범위 내에서 이웃토지의 사용을 청구할 수 있다.

#### [2015-58] 시효취득을 할 수 없는 것은?(다툼이 있으면 판례에 따름)
① 저당권
② 계속되고 표현된 지역권
③ 지상권
④ 국유재산 중 일반재산
⑤ 성명불상자(姓名不詳者)의 토지

#### [2015-59] X토지를 甲이 2/3지분, 乙이 1/3지분으로 등기하여 공유하면서 그 관리방법에 관해 별도로 협의하지 않았다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 따름)
① 丙이 甲으로부터 X토지의 특정부분의 사용ㆍ수익을 허락받아 점유하는 경우, 乙은 丙을 상대로 그 토지부분의 반환을 청구할 수 있다.
② 甲이 부정한 방법으로 X토지 전부에 관한 소유권이전 등기를 甲의 단독명의로 행한 경우, 乙은 甲을 상대로 자신의 지분에 관하여 그 등기의 말소를 청구할 수 있다.
③ X토지에 관하여 丁 명의로 원인무효의 소유권이전등기가 경료되어 있는 경우, 乙은 丁을 상대로 그 등기 전부의 말소를 청구할 수 있다.
④ 戊가 X토지 위에 무단으로 건물을 신축한 경우, 乙은 특별한 사유가 없는 한 자신의 지분에 대응하는 비율의 한도 내에서만 戊를 상대로 손해배상을 청구할 수 있다.
⑤ X토지가 나대지인 경우, 甲은 乙의 동의 없이 건물을 신축할 수 없다.

#### [2015-60] 저당권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 따름)
① 저당권자는 목적물 반환청구권을 갖지 않는다.
② 저당부동산의 종물에는 저당권의 효력이 미치지 않는다는 약정은 등기하지 않더라도 제3자에 대해 효력이 있다.
③ 원본의 반환이 2년간 지체된 경우 채무자는 원본 및 지연배상금의 전부를 변제하여야 저당권등기의 말소를 청구할 수 있다.
④ 저당권은 그 담보하는 채권과 분리하여 다른 채권의 담보로 하지 못한다.
⑤ 저당권이 설정된 토지가「공익사업을 위한 토지 등의 취득 및 보상에 관한 법률」에 따라 협의취득된 경우, 저당권자는 토지소유자가 수령할 보상금에 대하여 물상 대위를 할 수 없다.

#### [2015-61] 전세권에 관한 설명으로 옳은 것은?
① 원전세권자가 소유자의 동의 없이 전전세를 하면 원전 세권은 소멸한다.
② 건물에 대한 전세권이 법정갱신되는 경우 그 존속기간은 2년으로 본다.
③ 제3자가 불법 점유하는 건물에 대해 용익목적으로 전세권을 취득한 자는 제3자를 상대로 건물의 인도를 청구할 수 있다.
④ 전세권자는 특약이 없는 한 목적물의 현상을 유지하기 위해 지출한 필요비의 상환을 청구할 수 있다.
⑤ 전전세권자는 원전세권이 소멸하지 않은 경우에도 전전세권의 목적 부동산에 대해 경매를 신청할 수 있다.

#### [2015-62] 유치권에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 목적물에 대한 점유를 취득한 뒤 그 목적물에 관하여 성립한 채권을 담보하기 위한 유치권은 인정되지 않는다.
② 채권자가 채무자를 직접점유자로 하여 간접점유하는 경우에도 유치권은 성립할 수 있다.
③ 유치권자가 점유를 침탈당한 경우 점유보호청구권과 유치권에 기한 반환청구권을 갖는다.
④ 유치권자는 유치물의 보존에 필요하더라도 채무자의 승낙 없이는 유치물을 사용할 수 없다.
⑤ 임대차종료 후 법원이 임차인의 유익비상환청구권에 유예기간을 인정한 경우, 임차인은 그 기간 내에는 유익비상환청구권을 담보하기 위해 임차목적물을 유치할 수 없다.

#### [2015-63] 甲은 그 소유 나대지(X토지)에 乙의 저당권을 설정한 뒤 건물을 신축하였다. 다음 중 옳은 것을 모두 고른 것은?(다툼이 있으면 판례에 따름)
====
ㄱ. X토지에 대한 저당권실행을 위한 경매개시결정 전에 갑이 A에게 건물 소유권을 이전한 경우, 을은 X토지와 건물에 대해 일괄경매를 청구할 수 있다.
ㄴ. 을의 저당권이 실행되어 B가 X토지를 매수하고 매각대금을 다 낸 경우, 갑은 법정지상권을 취득한다.
ㄷ. 저당권 설정 뒤 X토지에 대해 통상의 강제경매가 실시되어 C가 그 토지를 취득한 경우, 갑은 관습상 법정지상권을 취득하지 못한다.
ㄹ. 저당권 설정 뒤 D가 X토지를 매수 취득하여 그 토지에 필요비를 지출한 경우, 을의 저당권이 실행되면 D는 경매대가로부터 필요비를 우선상환 받을 수 있다.
====
① ㄱ, ㄴ
② ㄱ, ㄹ
③ ㄴ, ㄹ
④ ㄷ
⑤ ㄷ, ㄹ

#### [2015-64] 근저당권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 따름)
① 피담보채무의 확정 전에는 채무자를 변경할 수 없다.
② 1년분이 넘는 지연배상금이라도 채권최고액의 한도 내라면 전액 근저당권에 의해 담보된다.
③ 근저당권이 성립하기 위해서는 그 설정행위와 별도로 피담보채권을 성립시키는 법률행위가 있어야 한다.
④ 후순위 근저당권자가 경매를 신청한 경우 선순위 근저당권의 피담보채권은 매각대금이 완납된 때에 확정된다.
⑤ 선순위 근저당권의 확정된 피담보채권액이 채권최고액을 초과하는 경우, 후순위 근저당권자가 그 채권최고액을 변제하더라도, 선순위 근저당권의 소멸을 청구할 수 없다.

#### [2015-65] 계약의 청약과 승낙에 관한 설명으로 옳은 것은?
① 격지자간의 청약은 이를 자유로이 철회할 수 있다.
② 청약은 상대방 있는 의사표시이므로 청약할 때 상대방이 특정되어야 한다.
③ 청약자가 그 통지를 발송한 후 도달 전에 사망한 경우, 청약은 효력을 상실한다.
④ 격지자간의 계약은 승낙의 통지가 도달한 때에 성립한다.
⑤ 승낙기간을 정하여 청약을 하였으나 청약자가 승낙의 통지를 그 기간 내에 받지 못한 경우, 원칙적으로 청약은 효력을 상실한다.

#### [2015-66] 계약의 유형에 관한 설명으로 틀린 것은?
① 예약은 채권계약이다.
② 전형계약 중 쌍무계약은 유상계약이다.
③ 교환계약은 요물계약이다.
④ 매매계약은 쌍무계약이다.
⑤ 임대차계약은 유상계약이다.

#### [2015-67] 동시이행의 항변권에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 동시이행관계에 있는 쌍방의 채무 중 어느 한 채무가 이행불능이 되어 손해배상채무로 바뀌는 경우, 동시이행의 항변권은 소멸한다.
② 임대차 종료 후 보증금을 반환받지 못한 임차인이 동시이행의 항변권에 기하여 임차목적물을 점유하는 경우, 불법점유로 인한 손해배상책임을 진다.
③ 동시이행의 항변권은 당사자의 주장이 없어도 법원이 직권으로 고려할 사항이다.
④ 채권자의 이행청구소송에서 채무자가 주장한 동시이행의 항변이 받아들여진 경우, 채권자는 전부 패소판결을 받게 된다.
⑤ 선이행의무자가 이행을 지체하는 동안에 상대방의 채무의 변제기가 도래한 경우, 특별한 사정이 없는 한 쌍방의 의무는 동시이행관계가 된다.

#### [2015-68] 甲은 자신의 토지를 乙에게 매도하면서 그 대금은 乙이 甲의 의무이행과 동시에 丙에게 지급하기로 약정하고, 丙은 乙에게 수익의 의사표시를 하였다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 따름)
① 丙은 乙의 채무불이행을 이유로 甲과 乙의 매매계약을 해제할 수 없다.
② 甲과 乙의 매매계약이 적법하게 취소된 경우, 丙의 급부청구권은 소멸한다.
③ 甲이 乙에게 매매계약에 따른 이행을 하지 않더라도, 乙은 특별한 사정이 없는 한 丙에게 대금지급을 거절할 수 없다.
④ 丙이 수익의 의사표시를 한 후에는 특별한 사정이 없는 한 甲과 乙의 합의에 의해 丙의 권리를 소멸시킬 수 없다.
⑤ 丙이 대금을 수령하였으나 매매계약이 무효인 것으로 판명된 경우, 특별한 사정이 없는 한 乙은 丙에게 대금반환을 청구할 수 없다.

#### [2015-69] 계약의 해제에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 따름)
① 계약이 합의해제된 경우, 특약이 없는 한 반환할 금전에 그 받은 날로부터 이자를 붙여 지급할 의무가 없다.
② 계약의 상대방이 여럿인 경우, 해제권자는 그 전원에 대하여 해제권을 행사하여야 한다.
③ 매매계약의 해제로 인하여 양당사자가 부담하는 원상회복의무는 동시이행의 관계에 있다.
④ 성질상 일정한 기간 내에 이행하지 않으면 그 목적을 달성할 수 없는 계약에서 당사자 일방이 그 시기에 이행하지 않으면 해제의 의사표시가 없더라도 해제의 효과가 발생한다.
⑤ 매매대금채권이 양도된 후 매매계약이 해제된 경우, 그양수인은 해제로 권리를 침해당하지 않는 제3자에 해당하지 않는다.

#### [2015-70] 계약금에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 따름)
① 계약금은 별도의 약정이 없는 한 해약금으로 추정된다.
② 매매해약금에 관한 민법 규정은 임대차에도 적용된다.
③ 해약금에 기해 계약을 해제하는 경우에는 원상회복의 문제가 생기지 않는다.
④ 토지거래허가구역 내 토지에 관한 매매계약을 체결하고 계약금만 지급한 상태에서 거래허가를 받은 경우, 다른 약정이 없는 한 매도인은 계약금의 배액을 상환하고 계약을 해제할 수 없다.
⑤ 계약금만 수령한 매도인이 매수인에게 계약의 이행을 최고하고 매매잔금의 지급을 청구하는 소송을 제기한 경우, 다른 약정이 없는 한 매수인은 계약금을 포기하고 계약을 해제할 수 있다.

#### [2015-71] 매매에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 따름)
① 매매비용을 매수인이 전부 부담한다는 약정은 특별한 사정이 없는 한 유효하다.
② 지상권은 매매의 대상이 될 수 없다.
③ 매매목적물의 인도와 동시에 대금을 지급할 경우, 그 인도장소에서 대금을 지급하여야 한다.
④ 매매목적물이 인도되지 않고 대금도 완제되지 않은 경우, 목적물로부터 생긴 과실은 매도인에게 속한다.
⑤ 당사자 사이에 행사기간을 정하지 않은 매매의 예약완결권은 그 예약이 성립한 때로부터 10년 내에 행사하여야 한다.

#### [2015-72] 임차인의 권리에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 임차물에 필요비를 지출한 임차인은 임대차 종료 시 그 가액증가가 현존한 때에 한하여 그 상환을 청구할 수 있다.
② 건물임차인이 그 사용의 편익을 위해 임대인으로부터 부속물을 매수한 경우, 임대차 종료 전에도 임대인에게 그 매수를 청구할 수 있다.
③ 건물소유를 목적으로 한 토지임대차를 등기하지 않았더라도, 임차인이 그 지상건물의 보존등기를 하면, 토지임 대차는 제3자에 대하여 효력이 생긴다.
④ 건물소유를 목적으로 한 토지임대차의 기간이 만료된 경우, 임차인은 계약갱신의 청구 없이도 매도인에게 건물의 매수를 청구할 수 있다.
⑤ 토지임대차가 묵시적으로 갱신된 경우, 임차인은 언제 든지 해지통고 할 수 있으나, 임대인은 그렇지 않다.

#### [2015-73] 건물임대인 甲의 동의를 얻어 임차인 乙이 丙과 전대차계약을 체결하고 그 건물을 인도해 주었다. 옳은 것을 모두 고른 것은?(다툼이 있으면 판례에 따름)
====
ㄱ. 갑과 을의 합의로 임대차계약이 종료되어도 병의 권리는 소멸하지 않는다.
ㄴ. 전대차 종료 시에 병은 건물 사용의 편익을 위해 을의 동의를 얻어 부속한  물건의 매수를 갑에게 청구할 수 있다.
ㄷ. 임대차와 전대차 기간이 모두 만료된 경우, 병은 건물을 갑에게 직접 명도해도 을에 대한 건물명도의무를 면하지 못한다.
ㄹ. 을의 차임연체액이 2기의 차임액에 달하여 갑이 임대차계약을 해지하는 경우, 갑은 병에 대해 그 사유의 통지 없이도 해지로써 대항할 수 있다.
====
① ㄱ, ㄷ
② ㄱ, ㄹ
③ ㄴ, ㄷ
④ ㄴ, ㄹ
⑤ ㄷ, ㄹ

#### [2015-74] 매도인의 담보책임에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 타인의 권리를 매도한 자가 그 전부를 취득하여 매수인에게 이전할 수 없는 경우, 악의의 매수인은 계약을 해제할 수 없다.
② 저당권이 설정된 부동산의 매수인이 저당권의 행사로 그 소유권을 취득할 수 없는 경우, 악의의 매수인은 특별한 사정이 없는 한 계약을 해제하고 손해배상을 청구 할 수 있다.
③ 매매목적인 권리의 전부가 타인에게 속하여 권리의 전부를 이전할 수 없게 된 경우, 매도인은 선의의 매수인에게 신뢰이익을 배상하여야 한다.
④ 매매목적 부동산에 전세권이 설정된 경우, 계약의 목적달성 여부와 관계없이, 선의의 매수인은 계약을 해제할 수 있다.
⑤ 권리의 일부가 타인에게 속한 경우, 선의의 매수인이 갖는 손해배상청구권은 계약한 날로부터 1년 내에 행사되어야 한다.

#### [2015-75] 주택임대차보호법에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 주민등록의 신고는 행정청이 수리한 때가 아니라, 행정청에 도달한 때 효력이 발생한다.
② 등기명령의 집행에 따라 주택 전부에 대해 타인 명의의 임차권등기가 끝난 뒤 소액보증금을 내고 그 주택을 임차한 자는 최우선변제권을 행사할 수 없다.
③ 임차권보다 선순위의 저당권이 존재하는 주택이 경매로 매각된 경우, 경매의 매수인은 임대인의 지위를 승계한다.
④ 소액임차인은 경매신청의 등기 전까지 임대차계약서에 확정일자를 받아야 최우선변제권을 행사할 수 있다.
⑤ 주택임차인의 우선변제권은 대지의 환가대금에는 미치지 않는다.

#### [2015-76] 집합건물의 소유 및 관리에 관한 법령상 집합건물에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 따름)
① 집합건축물대장에 등록되지 않더라도 구분소유가 성립 할 수 있다.
② 공용부분의 사용과 비용부담은 전유부분의 지분비율에 따른다.
③ 집합건물의 공용부분은 시효취득의 대상이 될 수 없다.
④ 관리인 선임 여부와 관계 없이 공유자는 단독으로 공용부분에 대한 보존행위를 할 수 있다.
⑤ 구분소유자는 규약 또는 공정증서로써 달리 정하지 않는 한 그가 가지는 전유부분과 분리하여 대지사용권을 처분할 수 없다.

#### [2015-77] 가등기담보 등에 관한 법률에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 공사대금채무를 담보하기 위한 가등기에도「가등기담보 등에 관한 법률」이 적용된다.
② 청산금을 지급할 필요 없이 청산절차가 종료한 경우, 그때부터 담보목적물의 과실수취권은 채권자에게 귀속한다.
③ 가등기담보의 채무자는 귀속정산과 처분정산 중 하나를 선택할 수 있다.
④ 가등기담보의 채무자의 채무변제와 가등기 말소는 동시 이행관계에 있다.
⑤ 담보가등기 후의 저당권자는 청산기간 내라도 저당권의 피담보채권의 도래 전에는 담보목적 부동산의 경매를 청구할 수 없다.

#### [2015-78] 2015년 甲은 丙의 X토지를 취득하고자 친구 乙과 명의신탁약정을 체결하고 乙에게 그 매수자금을 주었다. 甲과의 약정대로 乙은 명의신탁 사실을 모르는 丙으로부터 X토지를 매수하는 계약을 자기 명의로 체결하고 소유권이전등기를 경료 받았다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 따름)
① X토지의 소유자는 丙이다.
② 甲이 乙과의 관계에서 소유권을 가지는 것을 전제로 하여 장차 X토지의 처분대가를 乙이 甲에게 지급하기로 하는 약정은 유효하다.
③ 甲과 乙 및 甲의 친구 丁 사이의 새로운 명의신탁약정에 의하여 乙이 다시 甲이 지정한 丁에게 X토지의 이전등기를 해 준 경우, 丁은 그 소유권을 취득한다.
④ 만약 乙이 甲의 아들이라면, 명의신탁약정은 유효하다.
⑤ 만약 乙과 명의신탁 사실을 아는 丙이 매매계약에 따른 법률효과를 직접 甲에게 귀속시킬 의도로 계약을 체결한 사정이 인정된다면, 甲과 乙의 명의신탁은 3자간 등 기명의신탁으로 보아야 한다.

#### [2015-79] 부동산 실권리자명의 등기에 관한 법률에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 따름)
① 소유권 이외의 부동산 물권의 명의신탁은 동 법률의 적용을 받지 않는다.
② 채무변제를 담보하기 위해 채권자가 부동산 소유권을 이전받기로 하는 약정은 동 법률의 명의신탁약정에 해당한다.
③ 양자간 등기명의신탁의 경우 신탁자는 수탁자에게 명의신탁약정의 해지를 원인으로 소유권이전등기를 청구할 수 없다.
④ 3자간 등기명의신탁의 경우 수탁자가 자진하여 신탁자에게 소유권이전등기를 해주더라도, 그 등기는 무효이다.
⑤ 명의신탁약정의 무효는 악의의 제3자에게 대항할 수 있다.

#### [2015-80] 상가건물 임대차보호법상 임차인이 그가 주선한 신규 임차인이 되려는 자로부터 권리금을 지급받는 것을 방해한 임대인에게 손해배상을 청구할 권리는 “임대차가 종료한 날부터 ( ) 이내에 행사하지 않으면 시효의 완성으로 소멸한다.” 빈 칸에 들어갈 기간은?
① 6개월
② 1년
③ 2년
④ 3년
⑤ 5년