2과목 : 민법 및 민사특별법


#### [2012-41] 대리에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 임의대리인이 본인의 승낙을 얻어 복대리인을 선임한 경우에는 본인에 대하여 선임ㆍ감독에 관한 책임이 없다.
② 임의대리인이 본인 소유의 미등기부동산의 보존등기를 하기 위해서는 본인에 의한 특별수권이 있어야 한다.
③ 대리인이 대리권 소멸 후 복대리인을 선임하여 그로 하여금 대리행위를 하도록 한 경우, 대리권 소멸 후의 표현대리가 성립할 수 있다.
④ 대리권 수여표시에 의한 표현대리가 성립하기 위해서는 본인과 표현대리인 사이에 유효한 기본적 법률관계가 있어야 한다.
⑤ 법정대리권을 기본대리권으로 하는 권한을 넘은 표현대리는 성립하지 않는다.

#### [2012-42] 다음 중 의무부담행위가 아닌 것은?
① 교환② 임대차
③ 재매매예약④ 주택분양계약
⑤ 채권양도

#### [2012-43] 허위표시의 무효로 대항할 수 없는 선의의 제3자에 해당되지 않는 자는?(다툼이 있으면 판례에 의함)
① 가장전세권자의 전세권부채권을 가압류한 자
② 허위로 체결된 제3자를 위한 계약의 수익자
③ 가장양수인으로부터 저당권을 설정받은 자
④ 가장양수인으로부터 소유권이전등기청구권 보전을 위한 가등기를 경료받은 자
⑤ 가장행위에 기한 근저당권부채권을 가압류한 자

#### [2012-44] 강박에 의한 의사표시에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 강박에 의해 증여의 의사표시를 하였다고 하여 증여의 내심의 효과의사가 결여된 것이라고 할 수 없다.
② 법률행위의 성립과정에 강박이라는 불법적 방법이 사용된 것에 불과한 때에는 반사회질서의 법률행위라고 할 수 없다.
③ 제3자의 강박에 의해 의사표시를 한 경우, 상대방이 그 사실을 알았다면 표의자는 자신의 의사표시를 취소할 수 있다.
④ 강박에 의해 자유로운 의사결정의 여지가 완전히 박탈되어 그 외형만 있는 법률행위는 무효이다.
⑤ 강박행위의 위법성은 어떤 해악의 고지가 거래관념상 그 해악의 고지로써 추구하는 이익 달성을 위한 수단으로 부적당한 경우에는 인정되지 않는다.

#### [2012-45] 협의의 무권대리에 관한 설명으로 틀린 것을 모두 고른 것은?(다툼이 있으면 판례에 의함)
====
ㄱ. 상대방이 무권대리인의 동의를 얻어 단독행위를 한 경우 본인은 이를 추인할 수 있다
ㄴ. 무권대리행위의 추인은 다른 의사표시가 없는 한, 소급효가 인정되지 않는다.
ㄷ. 무권대리에 의한 계약의 추인은 그 대리행위로 인한 권리의 승계인에게도 할 수 있다.
ㄹ. 무권대리행위는 그 효력이 불확정상태에 있다가 본인의 추인 유무에 따라 본인에 대한 효력발생 여부가 결정된다
ㅁ. 무권대리행위의 추인과 추인거절의 의사표시는 무권대리인에게 할 수 있다.
====
① ㄱ, ㄴ
② ㄴ, ㄹ
③ ㄴ, ㅁ
④ ㄷ, ㄹ
⑤ ㄱ, ㄹ, ㅁ

#### [2012-46] 착오에 의한 법률행위에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 매수한 토지가 계약체결 당시부터 법령상의 제한으로 인해 매수인이 의도한 목적대로 이용할 수 없게 된 경우, 매수인의 착오는 동기의 착오가 될 수 있다.
② 주채무자 소유의 부동산에 가압류 등기가 없다고 믿고 보증하였더라도, 그 가압류가 원인무효로 밝혀졌다면 착오를 이유로 취소할 수 없다.
③ 상대방에 의해 유발된 동기의 착오는 동기가 표시되지 않았더라도 중요부분의 착오가 될 수 있다.
④ 공인중개사를 통하지 않고 토지거래를 하는 경우, 토지대장 등을 확인하지 않은 매수인은 매매목적물의 동일성에 착오가 있더라도 착오를 이유로 매매계약을 취소할 수 없다.
⑤ 매수인의 중도금 미지급을 이유로 매도인이 적법하게 계약을 해제한 경우, 매수인은 착오를 이유로 계약을 다시 취소할 수는 없다.

#### [2012-47] 조건과 기한에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 조건의 성취가 미정인 권리는 일반규정에 의하여 처분할 수 있을 뿐 아니라 담보로 할 수도 있다.
② 정지조건부 법률행위에 있어 조건이 성취되면 그 효력은 법률행위시로 소급하여 발생함이 원칙이다.
③ 조건이 법률행위 당시 이미 성취된 경우, 그 조건이 정지조건이면 법률행위는 무효가 된다.
④ 불법조건이 붙어 있는 법률행위는 그 조건만이 무효가 된다.
⑤ 기한이익 상실의 특약은 특별한 사정이 없는 한, 정지조건부 기한이익상실의 특약으로 추정한다.

#### [2012-48] 다음 중 원칙적으로 소급효가 인정되는 것은?(다툼이 있으면 판례에 의함)
① 일부취소
② 계약의 해지
③ 기한도래의 효력
④ 무효행위임을 알고 한 무효행위의 추인
⑤ 청구권보전을 위한 가등기에 기한 본등기에 의한 물권변동시기

#### [2012-49] 甲은 그의 X토지를 내심의 의사와는 달리 乙에게 기부하고, 乙 앞으로 이전등기를 마쳤다. 甲ㆍ乙 사이의 법률관계에 관한 설명으로 옳은 것은?
① 甲의 의사표시는 무효이므로, 乙이 甲의 진의를 몰랐더라도 X토지의 소유권을 취득할 수 없다.
② 甲의 의사표시는 단독행위이므로 비진의표시에 관한 법리가 적용되지 않는다.
③ 甲의 진의에 대한 乙의 악의가 증명되어 X토지의 소유권이 甲에게 회복되면, 乙은 甲에게 그로 인한 손해배상을 청구할 수 있다.
④ 乙이 통상인의 주의만 기울였어도 甲의 진의를 알 수 있었다면, 乙은 X토지의 소유권을 취득할 수 없다.
⑤ 乙로부터 X토지를 매수하여 이전등기를 경료한 丙이 甲의 진의를 몰랐더라도 X토지의 소유권은 여전히 甲에게 있다.

#### [2012-50] 무효인 법률행위는?(다툼이 있으면 판례에 의함)
① 지역권에 저당권을 설정하는 계약
② 무허가 음식점의 음식판매행위
③ 임대인의 동의 없는 임차인의 전대차계약
④ 존속기간이 영구적인 구분지상권 설정계약
⑤ 다른 공유자의 동의 없이 자신의 공유지분에 대해 저당권을 설정하는 행위

#### [2012-51] 지역권에 관한 설명으로 틀린 것은?
① 지역권은 요역지와 분리하여 양도할 수 없다.
② 요역지는 한 필의 토지 전부여야 하나, 승역지는 한 필의 토지의 일부일 수 있다.
③ 지역권자는 지역권에 기한 방해예방청구권을 행사할 수 있다.
④ 공유자 1인이 지역권을 취득하면 다른 공유자도 이를 취득한다.
⑤ 승역지 소유자는 지역권자가 지역권 행사를 위해 승역지에 설치한 공작물을 지역권자와 공동으로 사용하더라도 특약이 없는 한, 그 설치비용을 부담할 필요는 없다.

#### [2012-52] 저당권의 성립 및 효력에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 장래의 특정한 채권은 저당권의 피담보채권이 될 수 있다.
② 물상대위권 행사를 위한 압류는 그 권리를 행사하는 저당권자에 의해서만 가능하다.
③ 저당부동산에 대해 지상권을 취득한 제3자는 저당권자에게 피담보채권을 변제하고 저당권의 소멸을 청구할 수 있다.
④ 건물의 증축비용을 투자한 자가 그 대가로 건물에 대한 공유지분이전등기를 경료받은 경우, 저당권이 실행되더라도 매수대금에서 우선상환을 받을 수 없다.
⑤ 저당권이 설정된 나대지에 건물이 축조된 경우, 토지와 건물이 일괄경매되더라도 저당권자는 그 건물의 매수대금으로부터 우선변제 받을 수 없다.

#### [2012-53] 근저당권에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 채권최고액은 필요적 등기사항이 아니다.
② 피담보채권이 확정되기 전에는 당사자의 약정으로 근저당권을 소멸시킬 수 없다.
③ 확정된 피담보채권액이 채권최고액을 초과하는 경우, 물상보증인은 채권최고액의 변제만으로 근저당권설정등기의 말소를 청구할 수 없다.
④ 최선순위 근저당권자가 경매를 신청하여 경매개시결정이 된 경우, 그 근저당권의 피담보채권은 경매신청시에 확정된다.
⑤ 피담보채권이 확정되기 전에는 채무원인의 변경에 관하여 후순위권리자의 승낙이 있어야 한다.

#### [2012-54] 본권에 기하여 물권적 청구권을 가지는 자는?(다툼이 있으면 판례에 의함)(문제 오류로 실제 시험장에서는 모두 정답 처리되었습니다. 여기서는 1번을 누르시면 정답 처리 됩니다.)
① 가등기담보권자② 유치권자
③ 계약명의신탁자④ 무허가건물의 양수인
⑤ 부동산 점유취득시효 완성 후 등기하지 아니한 자

#### [2012-55] 부동산 물권변동과 공시에 관한 설명으로 틀린 것은?
① 명인방법으로 공시되는 물권변동은 소유권의 이전 또는 유보에 한한다.
② 해제조건부 법률행위에 기해 소유권이전등기가 경료되었더라도 그 조건이 성취되면 소유권은 원래의 소유자에게 복귀한다.
③ 등기부취득시효가 완성된 이후에는 등기원인의 실효를 주장하여 등기명의자의 소유권취득을 부인할 수 없다.
④ 미등기건물의 원시취득자와 그 승계취득자의 합의에 의해 직접 승계취득자 명의로 한 소유권보존등기는 유효하다.
⑤ 점유취득시효완성 후 이전등기 전에 원소유자가 해당 부동산에 관하여 근저당권을 설정한 경우, 특별한 사정이 없는 한 취득시효완성자는 소유권이전등기를 경료함으로써 담보권 제한이 없는 소유권을 취득한다.

#### [2012-56] 부동산에의 부합에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 건물 임차인이 권원에 기하여 증축한 부분에 구조상ㆍ이용상 독립성이 없더라도 임대차종료시 임차인은 증축부분의 소유권을 주장할 수 있다.
② 위의 ① 에서와 같이 독립성이 없더라도, 임차인은 부속물매수청구권을 행사할 수 있다.
③ 저당권설정 이후에 부합한 물건에 대하여 저당권의 효력이 미칠 수 없음을 약정할 수 있다.
④ 자연적인 원인에 의한 부합이 인정되는 경우는 없다.
⑤ 시가 1억원 상당의 부동산에 시가 2억원 상당의 동산이 부합하면, 특약이 없는 한 동산의 소유자가 그 부동산의 소유권을 취득한다.

#### [2012-57] 점유에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 선의의 점유자가 얻은 건물 사용이익은 과실(果實)에 준하여 취급한다.
② 건물 소유의 목적으로 타인의 토지를 임차한 자의 토지 점유는 타주점유이다.
③ 점유물이 멸실ㆍ훼손된 경우, 선의의 타주점유자는 현존이익의 한도 내에서 배상책임을 진다.
④ 선의의 점유자라도 본권에 관한 소에 패소하면 소제기 시부터 악의의 점유자로 본다.
⑤ 공사대금 지급을 위해 부동산 양도담보설정의 취지로 분양계약을 체결한 경우, 수분양자는 목적 부동산을 간접점유한다.

#### [2012-58] 토지거래허가구역 밖에 있는 토지에 대하여 최초 매도인 甲과 중간 매수인 乙, 乙과 최종 매수인 丙 사이에 순차로 매매계약이 체결되고 이들 간에 중간생략등기의 합의가 있는 경우에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 乙의 甲에 대한 소유권이전등기청구권은 소멸하지 않는다.
② 甲ㆍ乙 사이의 계약이 행위무능력을 이유로 적법하게 취소된 경우, 甲은 丙 앞으로 경료된 중간생략등기의 말소를 청구할 수 있다.
③ 甲은 乙의 매매대금 미지급을 이유로 丙 명의로의 소유권이전등기의무 이행을 거절할 수 있다.
④ 甲과 乙, 乙과 丙이 중간등기 생략의 합의를 순차적으로 한 경우, 丙은 甲의 동의가 없더라도 甲을 상대로 중간생략등기청구를 할 수 있다.
⑤ 중간생략등기의 합의 후 甲ㆍ乙 사이의 매매계약이 합의해제된 경우, 甲은 丙 명의로의 소유권이전등기의무의 이행을 거절할 수 있다.

#### [2012-59] 등기의 추정력에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 원인 없이 부적법 말소된 등기에는 권리소멸의 추정력이 인정되지 않는다.
② 등기부상 물권변동의 당사자 사이에는 등기추정력이 원용될 수 없다.
③ 등기된 부동산에 관하여도 점유의 추정력이 인정된다.
④ 건물 소유권보존등기의 명의자가 이를 신축한 것이 아니라도 그 등기의 권리추정력은 인정된다.
⑤ 전 소유자의 사망이후에「부동산소유권이전등기 등에 관한 특별조치법」에 의한 소유권이전등기가 경료되면 그 등기의 추정력은 깨진다.

#### [2012-60] 전세권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 전전세의 존속기간은 원 전세권의 범위를 넘을 수 없다.
② 전세권이 침해된 경우, 전세권자는 점유보호청구권을 행사할 수 있다.
③ 전세권 양도금지특약은 이를 등기하여야 제3자에게 대항할 수 있다.
④ 전세권을 목적으로 한 저당권은 전세권 존속기간이 만료되더라도 그 전세권 자체에 대하여 저당권을 실행할 수 있다.
⑤ 타인의 토지 위에 건물을 신축한 자가 그 건물에 전세권을 설정한 경우, 전세권은 건물의 소유를 목적으로 하는 토지임차권에도 그 효력이 미친다.

#### [2012-61] 부동산의 점유취득시효에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 시효취득을 주장하는 점유자는 자주점유를 증명할 책임이 있다.
② 시효진행 중에 목적부동산이 전전양도된 후 시효가 완성된 경우, 시효완성자는 최종등기명의자에 대해 이전등기를 청구할 수 있다.
③ 취득시효가 완성된 점유자는 토지 소유자가 시효완성 후 당해 토지에 무단으로 담장 등을 설치하더라도 그 철거를 청구할 수 없다.
④ 시효기간 만료 후 명의수탁자로부터 적법하게 이전등기받은 명의신탁자는 시효완성자에게 대항할 수 없다.
⑤ 시효완성으로 이전등기를 경료받은 자가 취득시효기간 중에 체결한 임대차에서 발생한 임료는 원소유자에게 귀속한다.

#### [2012-62] 지상권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 지상권설정의 목적이 된 건물이 전부 멸실하면 지상권은 소멸한다.
② 지상권이 설정된 토지를 양수한 자는 지상권자에게 그 토지의 인도를 청구할 수 없다.
③ 환매특약의 등기가 경료된 나대지의 소유자가 그 지상에 건물을 신축한 후, 환매권이 행사되면 관습상의 법정지상권은 성립할 수 없다.
④ 법원이 결정한 지료의 지급을 2년분 이상 지체한 경우, 토지소유자는 법정지상권의 소멸을 청구할 수 있다.
⑤ 저당권이 설정된 나대지의 담보가치하락을 막기 위해 저당권자 명의의 지상권이 설정된 경우, 피담보채권이 변제되어 저당권이 소멸하면 그 지상권도 소멸한다.

#### [2012-63] 민법상 유치권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 물상대위가 인정되지 않는다.
② 유치권의 성립을 배제하는 특약은 유효하다.
③ 유치권은 채무자 이외의 제3자 소유물에도 성립할 수 있다.
④ 채무자가 유치물을 직접 점유하고 있는 경우, 채권자는 자신의 간접점유를 이유로 유치권을 행사할 수 없다.
⑤ 건축자재를 매도한 자는 그 자재로 건축된 건물에 대해 자신의 대금채권을 담보하기 위하여 유치권을 행사할 수 있다.

#### [2012-64] 유치권에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 유치권자가 제3자와의 점유매개관계에 의해 유치물을 간접점유하는 경우, 유치권은 소멸하지 않는다.
② 유치권자는 매수인(경락인)에 대해서도 피담보채권의 변제를 청구할 수 있다.
③ 유치권을 행사하는 동안에는 피담보채권의 소멸시효가 진행하지 않는다.
④ 유치권자는 유치물로부터 생기는 과실을 수취하여 이를 다른 채권자보다 먼저 자신의 채권변제에 충당할 수 없다.
⑤ 유치권자가 유치물인 주택에 거주하며 이를 사용하는 경우, 특별한 사정이 없는 한 채무자는 유치권소멸을 청구할 수 있다.

#### [2012-65] 甲은 건물소유를 목적으로 乙 소유의 X토지를 임차하여 Y건물을 신축하고 보존등기를 마쳤다. 다음 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 임대차기간이 만료하였으나 乙이 계약갱신을 원하지 않는 경우, 甲은 상당한 가액으로 건물매수를 청구할 수 있다.
② 甲이 2기의 차임액을 연체하여 乙이 임대차계약을 해지한 경우, 甲은 乙에게 건물매수를 청구할 수 없다.
③ 甲의 건물매수청구가 적법한 경우, 乙의 대금지급이 있기까지는 건물부지의 임료 상당액을 반환할 필요는 없다.
④ 甲이 Y건물에 설정한 저당권이 실행되어 丙이 그 소유권을 취득한 경우, 특별한 사정이 없는 한 甲의 토지임차권은 丙에게 이전된다.
⑤ 甲이 乙의 동의 없이 토지임차권과 Y건물을 丙에게 양도한 경우, 원칙적으로 丙은 乙에게 임차권 취득으로써 대항할 수 없다.

#### [2012-66] 임대인 甲은 임차인 乙에게 임대차기간의 만료와 동시에 임대주택의 명도를 요구하고 있다. 다음 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲이 보증금채무를 이행제공하지 않는 한, 乙은 주택의 명도를 거절할 수 있다.
② 乙이 동시이행항변권에 기하여 주택을 사용ㆍ수익하는 경우, 甲은 乙에게 불법점유를 이유로 손해배상책임을 물을 수 없다.
③ 乙이 동시이행항변권에 기하여 주택을 사용ㆍ수익하더라도 그로 인하여 실질적으로 얻은 이익이 있으면 부당이득으로 甲에게 반환하여야 한다.
④ 甲이 보증금채무를 이행제공하였음에도 乙이 주택을 명도하지 않은 경우, 甲이 그 후 보증금채무의 이행제공 없이 명도청구를 하더라도 乙은 동시이행항변권을 행사할 수 있다.
⑤ 乙이 甲에게 변제기가 도래한 대여금 채무를 지고 있다면, 乙은 甲에 대한 보증금채권을 자동채권으로 하여 甲의 乙에 대한 대여금채권과 상계할 수 있다.

#### [2012-67] 甲은 乙로부터 X토지를 매수하여 상가용 건물을 신축할 계획이었으나, 법령상의 제한으로 그 건물을 신축할 수 없게 되었다. 또한 토지의 오염으로 통상적인 사용도 기대할 수 없었다. 다음 중 옳은 것은?(다툼이 있으면 판례에 의함)
① 토지에 대한 법령상의 제한으로 건물신축이 불가능하면 이는 매매목적물의 하자에 해당한다.
② X토지에 하자가 존재하는지의 여부는 언제나 목적물의 인도시를 기준으로 판단하여야 한다.
③ 甲이 토지가 오염되어 있다는 사실을 계약체결시에 알고 있었더라도 乙에게 하자담보책임을 물을 수 있다.
④ 甲이 토지의 오염으로 인하여 계약의 목적을 달성할 수 없더라도 계약을 해제할 수 없다.
⑤ 甲은 토지의 오염사실을 안 날로부터 1년 내에는 언제든지 乙에 대하여 담보책임에 기한 손해배상을 청구할 수 있다.

#### [2012-68] 다음 중 계약체결상의 과실책임이 인정될 수 있는 것은?
① 수량을 지정한 토지매매계약에서 실제면적이 계약면적에 미달하는 경우
② 토지에 대한 매매계약체결 전에 이미 그 토지 전부가 공용수용된 경우
③ 가옥 매매계약 체결 후, 제3자의 방화로 그 가옥이 전소한 경우
④ 유명화가의 그림에 대해 임대차계약을 체결한 후, 임대인의 과실로 그 그림이 파손된 경우
⑤ 저당권이 설정된 토지를 매수하여 이전등기를 마쳤으나, 후에 저당권이 실행되어 소유권을 잃게 된 경우

#### [2012-69] 甲은 그의 X가옥을 乙에게 1억원에 매도하면서 계약체결일에 계약금 1천만원을 받았고, 잔금 9천만원은 그로부터 1개월 후에 지급받기로 하였다. 그리고 甲의 귀책사유로 위 매매계약이 해제되면 甲이 乙에게 1천만원의 위약금을 지급해야 한다는 약정도 함께 하였다. 다음 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 계약금 1천만원을 지급하기로 하는 甲ㆍ乙 사이의 약정은 매매계약에 종된 요물계약이다.
② 甲과 乙이 이행행위에 착수하기 전에 乙은 계약금을 포기하고 계약을 해제할 수 있다.
③ 乙이 잔금을 준비하여 등기절차를 밟기 위해 甲에게 등기소에 동행할 것을 촉구하는 것만으로는 이행의 착수라고 볼 수 없다.
④ 이행행위 착수 전에 乙이 해약금 해제를 한 경우, 乙은 해제에 따른 손해배상청구권을 행사할 수 없다.
⑤ 乙의 귀책사유로 인해 매매계약이 해제되더라도 乙의 위약금지급의무는 인정되지 않는다.

#### [2012-70] 청약과 승낙에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 불특정 다수인을 상대로 하는 청약의 의사표시는 그 효력이 없다.
② 승낙은 청약자에 대하여 하여야 하고, 불특정 다수인에 대한 승낙은 허용되지 않는다.
③ 청약 발신 후 그 도달 전에 청약의 상대방이 행위능력을 상실한 경우, 그 법정대리인이 청약 도달사실을 알았더라도 청약자는 상대방에게 그 청약으로써 대항할 수 없다.
④ 甲이 그 소유의 토지를 乙에게 매도청약하였는데, 乙이 이에 대금을 낮추어 승낙한 경우에도 매매계약은 성립한다.
⑤ 甲이 대금을 확정하지 않고 그의 주택을 乙에게 팔겠다는 의사를 표시하였는데, 乙이 곧 甲에게 1억원에 사겠다는 의사를 표시하였다면 甲ㆍ乙 사이에 그 주택에 대한 매매계약이 성립한다.

#### [2012-71] 다음 중 과실(過失)이 있는 경우에만 인정되는 것은?
① 임차인의 차임감액청구권
② 전세권설정자의 부속물매수청구권
③ 물건의 하자로 인한 매도인의 담보책임
④ 이행불능으로 인한 계약해제권과 손해배상청구권
⑤ 건물 소유를 목적으로 하는 토지임대차에 있어 임차인의 임대인에 대한 건물매수청구권

#### [2012-72] 계약해제의 소급효로부터 보호될 수 있는 제3자에 해당하는 자는?(다툼이 있으면 판례에 의함)
① 계약해제 전, 계약상의 채권을 양수하여 이를 피보전권리로 하여 처분금지가처분결정을 받은 채권자
② 계약해제 전, 해제대상인 계약상의 채권 자체를 압류 또는 전부(轉付)한 채권자
③ 해제대상 매매계약에 의하여 채무자명의로 이전등기된 부동산을 가압류 집행한 가압류채권자
④ 주택의 임대권한을 부여받은 매수인으로부터 매매계약이 해제되기 전에 주택을 임차한 후, 대항요건을 갖추지 않은 임차인
⑤ 해제대상 매매계약의 매수인으로부터 목적 부동산을 증여받은 후 소유권이전등기를 마치지 않은 수증자

#### [2012-73] 甲은 경매절차에서 저당목적물인 乙 소유의 X토지를 매각받고, 그 소유권이전등기가 경료되었다. 다음 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲은 X토지의 물건의 하자를 이유로 담보책임을 물을 수 없음이 원칙이다.
② 채무자 乙이 권리의 하자를 알고 고지하지 않았다면 甲은 乙에게 손해배상을 청구할 수 있다.
③ 경매절차가 무효인 경우, 甲은 담보책임을 물을 수 없다.
④ 담보책임이 인정되는 경우, 甲은 乙의 자력 유무를 고려함이 없이 곧바로 배당채권자에게 대금의 전부 또는 일부의 상환을 청구할 수 있다.
⑤ 만약 乙이 물상보증인인 경우, 담보책임으로 인해 매매계약이 해제되면 그 대금반환채무는 乙이 부담한다.

#### [2012-74] 임대차계약(일시사용을 위한 임대차는 제외)의 당사자가 아래의 권리에 관하여 임차인에게 불리한 약정을 하더라도 그 효력이 인정되는 것은?
① 차임증감청구권
② 필요비 및 유익비상환청구권
③ 임차인의 지상물매수청구권
④ 임차인의 부속물매수청구권
⑤ 기간의 약정이 없는 임대차의 해지통고

#### [2012-75] 「주택임대차보호법」상의 주택임대차에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 대항력 있는 주택임대차가 기간만료로 종료된 상태에서 임차주택이 양도되더라도 임차인은 이 사실을 안 때로부터 상당한 기간 내에 이의를 제기함으로써, 승계되는 임대차관계의 구속에서 벗어날 수 있다.
② 다른 특별한 규정이 없는 한, 미등기주택에 대해서도 이 법이 적용된다.
③ 임대차기간이 끝난 경우, 임차인이 보증금을 반환받지 못하였다면 임대차관계는 종료하지 않는다.
④ 다가구용 단독주택의 임대차에서는 전입신고를 할 때 지번만 기재하고 동ㆍ호수의 표시가 없어도 대항력을 취득할 수 있다.
⑤ 저당권이 설정된 주택을 임차하여 대항력을 갖춘 이상, 후순위저당권이 실행되더라도 매수인이 된 자에게 대항할 수 있다.

#### [2012-76] 甲은 乙소유의 서울특별시 소재 X상가건물을 2009. 6. 1. 보증금 4,500만원에 임차하여 같은 날 인도받은 후, 같은 해 6. 10. 적법절차에 따라 사업자등록을 신청하였다. 다음 중 옳은 것은?(다툼이 있으면 판례에 의함)
① X건물에 2009. 4. 6. 청구권보전의 가등기를 한 丙이 같은 해 6. 19. 그 가등기에 기한 본등기를 마쳤다면, 甲은 자신의 임차권으로 丙에게 대항할 수 없다.
② 甲이 임차목적물을 사실행위와 더불어 영리를 목적으로 하는 활동이 이루어지는 공장으로 사용하였다면, 상가건물임대차보호법의 적용대상이 아니다.
③ 甲ㆍ乙간에 임대차기간을 정하지 않은 경우, 계약갱신이 없다면 그 계약은 2011. 5. 31.에 만료된다.
④ 甲이 임차부분의 일부를 경과실로 파손한 경우에는 계약갱신을 요구하지 못한다.
⑤ 보증금 이외에 매월 50만원의 차임을 지급하기로 하였다면, 甲은 보증금 중 1,500만원에 대해서는 다른 담보물권자에 우선하여 변제받을 수 있다.

#### [2012-77] 「주택임대차보호법」의 내용에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 최선순위 전세권자로서의 지위와 대항력을 갖춘 주택임차인으로서의 지위를 함께 가진 자가 전세권자의 지위에서 경매를 신청한 경우에는 임차권의 대항력을 주장할 수 없다.
② 주택임차인과 전세권자의 지위를 함께 가지는 자가 임차인의 지위에서 경매법원에 배당요구를 하였다면 전세권에 관해서도 함께 배당요구를 한 것으로 보아야 한다.
③ 대항력 있는 주택임차권과 분리하여 보증금반환채권만을 양수한 자도, 임차주택에 대한 경매절차에서 임차보증금 우선변제권자의 지위에서 배당요구를 할 수 있다.
④ 대항요건 및 확정일자를 갖춘 주택임차권자는 임대차 성립당시 임대인 소유였던 대지가 타인에게 양도되어 임차주택과 대지 소유자가 달라지더라도, 대지의 환가대금에 대해 우선변제권을 행사할 수 있다.
⑤ 주택임차인이 사망한 경우, 그 주택에서 가정공동생활을 하던 사실혼배우자는 항상 상속권자에 우선하여 사망한 임차인의 권리ㆍ의무를 승계한다.

#### [2012-78] 「가등기담보 등에 관한 법률」에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 가등기담보권이 설정된 경우, 설정자는 담보권자에 대하여 그 목적물의 소유권을 자유롭게 행사할 수 있다.
② 귀속청산의 경우, 채권자는 담보권실행의 통지절차에 따라 통지한 청산금의 금액에 대해서는 다툴 수 없다.
③ 청산금 미지급으로 본등기가 무효로 되었다면, 그 후 청산절차를 마치더라도 유효한 등기가 될 수 없다.
④ 실행통지의 상대방이 채무자 등 여러 명인 경우, 그 모두에 대하여 실행통지를 하여야 통지로서의 효력이 발생한다.
⑤ 채권자와 채무자가 가등기담보권설정계약을 체결하면서 가등기 이후에 발생할 채권도 후순위권리자에 대하여 우선변제권을 가지는 가등기담보권의 피담보채권에 포함시키기로 약정할 수 있다.

#### [2012-79] 甲과 乙은「부동산실권리자명의등기에 관한 법률」의 적용을 받는 명의신탁약정을 통하여 丙소유 X건물의 소유권등기를 乙명의로 하였다. 다음 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲이 X건물을 매수한 후, 자신에게 등기이전 없이 곧바로 乙에게 소유권을 이전한 경우, 丙은 여전히 甲에 대해 소유권이전의무를 부담한다.
② 乙이 甲의 허락 없이 A에게 X건물을 신탁하여 재건축사업을 진행한 경우, 특별한 사정이 없는 한 甲은 명의신탁약정의 무효를 이유로 A에게 대항하지 못한다.
③ 乙에게 X건물을 매도한 丙이 甲ㆍ乙간의 계약명의신탁약정에 관하여 선의라면, 그 약정은 유효하다.
④ 乙에게 X건물을 매도한 丙이 甲ㆍ乙간의 계약명의신탁약정을 알고 있었다면, 丙은 乙명의의 등기말소를 청구할 수 있다.
⑤ 甲과 乙이 법률상 부부이고 위법한 목적이 없었다면, 甲은 명의신탁약정의 해지를 원인으로 하는 소유권이전등기를 청구할 수 있다.

#### [2012-80] 「집합건물의 소유 및 관리에 관한 법률」에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 완성된 분양목적물의 하자로 계약목적을 달성할 수 없더라도, 분양계약을 해제할 수 없다.
② 전유부분이 속하는 1동의 건물의 설치ㆍ보존의 흠으로 인하여 다른 자에게 손해를 입힌 경우, 그 흠은 공용부분에 존재하는 것으로 추정한다.
③ 임대 후 분양 전환된 집합건물에 대해서는 분양전환 시점을 기준으로 하여 하자담보책임을 물을 수 있다.
④ 분양자 아닌 시공자는 특별한 사정이 없는 한, 집합건물의 하자에 대하여 담보책임을 진다.
⑤ 집합건물에 하자가 발생한 경우, 하자보수에 갈음하는 손해배상청구권은 집합건물의 인도시에 발생한다.
