2과목 : 민법 및 민사특별법

#### [2014-41] 甲이 乙을 기망하여 건물을 매도하는 계약을 乙과 체결하였다. 법정추인사유에 해당하는 경우는?
① 甲이 乙에게 매매대금의 지급을 청구한 경우
② 甲이 乙에 대한 대금채권을 丙에게 양도한 경우
③ 甲이 이전등기에 필요한 서류를 乙에게 제공한 경우
④ 기망상태에서 벗어난 乙이 이의 없이 매매대금을 지급한 경우
⑤ 乙이 매매계약의 취소를 통해 취득하게 될 계약금 반환 청구권을 丁에게 양도한 경우

#### [2014-42] 불공정한 법률행위에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 궁박은 심리적 원인에 의한 것을 포함한다.
② 불공정한 법률행위에 관한 규정은 부담 없는 증여의 경우에도 적용된다.
③ 불공정한 법률행위에도 무효행위 전환의 법리가 적용될 수 있다.
④ 대리인에 의한 법률행위에서 무경험은 대리인을 기준으로 판단한다.
⑤ 경매절차에서 매각대금이 시가보다 현저히 저렴하더라도 불공정한 법률행위를 이유로 그 무효를 주장할 수 없다.

#### [2014-43] 甲이 자신의 부동산을 乙에게 매도하였는데, 그 사실을 잘 아는 丙이 甲의 배임행위에 적극가담하여 그 부동산을 매수하여 소유권이전등기를 받은 경우에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲ㆍ丙 사이의 매매계약은 무효이다.
② 乙은 丙에게 소유권이전등기를 청구할 수 없다.
③ 乙은 甲을 대위하여 丙에게 소유권이전등기의 말소를 청구할 수 있다.
④ 丙으로부터 그 부동산을 전득한 丁이 선의이면 소유권을 취득한다.
⑤ 乙은 甲ㆍ丙 사이의 매매계약에 대하여 채권자취소권을 행사할 수 없다.

#### [2014-44] 비진의표시에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 대출절차상 편의를 위하여 명의를 빌려준 자가 채무부담의 의사를 가졌더라도 그 의사표시는 비진의표시이다.
② 비진의표시에 관한 규정은 원칙적으로 상대방 있는 단독행위에 적용된다.
③ 매매계약에서 비진의표시는 상대방이 선의이며 과실이 없는 경우에 한하여 유효하다.
④ 사직의사 없는 사기업의 근로자가 사용자의 지시로 어쩔수 없이 일괄사직서를 제출하는 형태의 의사표시는 비진의표시이다.
⑤ 상대방이 표의자의 진의 아님을 알았다는 것은 무효를 주장하는 자가 증명하여야 한다.

#### [2014-45] 대리에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 대리인이 파산선고를 받아도 그의 대리권은 소멸하지 않는다.
② 대리인이 수인인 때에는 원칙적으로 각자가 본인을 대리한다.
③ 대리인은 본인의 허락이 있으면 당사자 쌍방을 대리할 수 있다.
④ 대리인의 대리권 남용을 상대방이 알았거나 알 수 있었을 경우, 대리행위는 본인에게 효력이 없다.
⑤ 매매계약을 체결할 대리권을 수여받은 대리인은 특별한 사정이 없는 한 중도금과 잔금을 수령할 권한이 있다.

#### [2014-46] 착오로 인한 의사표시에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 상대방이 착오자의 진의에 동의하더라도 착오자는 의사표시를 취소할 수 있다.
② 법률에 관한 착오도 법률행위 내용의 중요부분에 관한 착오에 해당될 수 있다.
③ 농지의 상당 부분이 하천임을 사전에 알았더라면 농지 매매계약을 체결하지 않았을 것이 명백한 경우, 법률행위 내용의 중요부분의 착오에 해당될 수 있다.
④ 당사자가 합의한 매매목적물의 지번에 관하여 착오를 일으켜 계약서상 목적물의 지번을 잘못 표시한 경우, 그 계약을 취소할 수 없다.
⑤ 토지소유자가 공무원의 법령오해에 따른 설명으로 착오에 빠져 토지를 국가에 증여한 경우, 이를 취소할 수 있다.

#### [2014-47] 반사회적 법률행위로서 무효가 아닌 것은?(다툼이 있으면 판례에 의함)
① 과도하게 중한 위약벌 약정
② 도박자금에 제공할 목적으로 금전을 대여하는 행위
③ 소송에서의 증언을 조건으로 통상 용인되는 수준을 넘는 대가를 받기로 한 약정
④ 공무원의 직무행위에 관하여 부정한 청탁의 대가로 금전을 지급하기로 한 약정
⑤ 부동산에 대한 강제집행을 면할 목적으로 그 부동산에 허위의 근저당권을 설정하는 행위

#### [2014-48] 사기ㆍ강박에 의한 의사표시에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 사기나 강박에 의한 소송행위는 원칙적으로 취소할 수 없다.
② 대리인의 기망행위로 계약을 체결한 상대방은 본인이 선의이면 계약을 취소할 수 없다.
③ 강박으로 의사결정의 자유가 완전히 박탈되어 법률 행위의 외형만 갖춘 의사표시는 무효이다.
④ 교환계약의 당사자 일방이 자기 소유 목적물의 시가를 묵비한 것은 특별한 사정이 없는 한 기망행위가 아니다.
⑤ 제3자의 사기로 계약을 체결한 경우, 피해자는 그 계약을 취소하지 않고 그 제3자에게 불법행위책임을 물을 수 있다.

#### [2014-49] 대리권 없는 乙이 甲의 이름으로 甲의 부동산을 丙에게 매도하여 소유권이전등기를 해주었다. 그 후 乙이 甲을 단독상속한 경우에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲ㆍ丙 사이의 매매계약은 무효이다.
② 丙명의의 등기는 실체적 권리관계에 부합하므로 유효하다.
③ 乙은 무권대리를 이유로 丙에게 등기의 말소를 청구할 수 없다.
④ 乙은 무권대리를 이유로 丙에게 그 부동산의 점유로 인한 부당이득반환을 청구할 수 있다.
⑤ 만약 丙이 그 부동산을 丁에게 매도하고 소유권이전 등기를 해준 경우, 乙은 丁에 대하여 등기말소를 청구 할 수 없다.

#### [2014-50] 추인하여도 효력이 생기지 않는 무효인 법률행위를 모두 고른 것은?(다툼이 있으면 판례에 의함)
====
ㄱ. 불공정한 법률행위
ㄴ. 무권대리인의 법률행위
ㄷ. 불법조건이 붙은 법률행위
ㄹ. 통정허위표시에 의한 임대차계약
====
① ㄱ, ㄴ
② ㄱ, ㄷ
③ ㄴ, ㄹ
④ ㄱ, ㄷ, ㄹ
⑤ ㄴ, ㄷ, ㄹ

#### [2014-51] 정지조건부 법률행위에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 조건이 불성취로 확정되면 그 법률행위는 무효이다.
② 정지조건부 권리는 조건이 성취되지 않은 동안 소멸시효가 진행되지 않는다.
③ 조건성취가 미정인 권리는 일반규정에 의하여 처분할 수 있다.
④ 조건성취의 효력은 원칙적으로 법률행위가 성립한 때부터 발생한다.
⑤ 소유권유보약정이 있는 경우, 특별한 사정이 없는 한 매매대금 전부의 지급이라는 조건이 성취될 때까지 매도인이 목적물의 소유권을 보유한다.

#### [2014-52] 지상권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 지료의 지급은 지상권의 성립요건이 아니다.
② 지상권에 기하여 토지에 부속된 공작물은 토지에 부합하지 않는다.
③ 지상권자는 토지소유자의 의사에 반하여 지상권을 타인에게 양도할 수 없다.
④ 구분지상권은 건물 기타 공작물의 소유를 위해 설정할 수 있다.
⑤ 저당권설정자가 담보가치의 하락을 막기 위해 저당권자에게 지상권을 설정해 준 경우, 피담보채권이 소멸하면 그 지상권도 소멸한다.

#### [2014-53] 등기의 추정력에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 소유권이전등기가 된 경우, 특별한 사정이 없는 한 이전등기에 필요한 적법한 절차를 거친 것으로 추정된다.
② 소유권이전등기가 된 경우, 등기명의인은 전 소유자에 대하여 적법한 등기원인에 기한 소유권을 취득한 것으로 추정된다.
③ 소유권이전등기가 불법말소된 경우, 말소된 등기의 최종명의인은 그 회복등기가 경료되기 전이라도 적법한 권리자로 추정된다.
④ 등기명의인이 등기원인행위의 태양이나 과정을 다소 다르게 주장한다고 하여 이로써 추정력이 깨어지는 것은 아니다.
⑤ 소유권이전청구권 보전을 위한 가등기가 있으면, 소유권이전 등기를 청구할 어떠한 법률관계가 있다고 추정된다.

#### [2014-54] A는 B의 X토지를 매수하여 1992. 2. 2.부터 등기 없이 2014년 현재까지 점유하고 있다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 의함)
(문제 오류로 실제 시험장에서는 모두 정답 처리되었습니다. 여기서는 1번을 누르시면 정답 처리 됩니다.)
① A의 B에 대한 매매를 원인으로 한 소유권이전등기청구권은 2002. 2. 2. 시효로 소멸한다.
② A가 매매를 원인으로 하여 점유를 개시하였음을 증명하지 못하면, 그의 점유는 타주점유로 본다.
③ C가 2010. 9. 9. X토지를 B로부터 매수하여 소유권을 취득한 경우, A는 X토지를 시효취득할 수 없다.
④ A가 2013. 3. 3. D에게 X토지를 매도하여 점유를 이전한 경우, D는 시효완성을 이유로 B에 대하여 직접 소유권 이전등기를 청구할 수 없다.
⑤ E가 2014. 4. 4. X토지에 청구권보전의 가등기를 한 경우, A는 더 이상 X토지를 시효취득할 수 없다.

#### [2014-55] 등기가 있어야 부동산물권을 취득하는 경우는?(다툼이 있으면 판례에 의함)
① 지상권을 상속으로 취득하는 경우
② 건물전세권이 법정갱신되는 경우
③ 건물을 신축하여 소유권을 취득하는 경우
④ 현물분할의 합의에 의하여 공유토지에 대한 단독소유권을 취득하는 경우
⑤ 1동의 건물 중 구분된 건물부분이 구조상ㆍ이용상 독립성을 갖추고 구분행위로 인하여 구분소유권을 취득하는 경우

#### [2014-56] 甲과 乙은 X토지에 관하여 구분소유적 공유관계에 있다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲과 乙은 자신들의 특정 구분부분을 단독으로 처분할 수 있다.
② 甲의 특정 구분부분에 대한 乙의 방해행위에 대하여, 甲은 소유권에 기한 방해배제를 청구할 수 있다.
③ 乙의 특정 구분부분에 대한 丙의 방해행위에 대하여, 甲은 丙에게 공유물의 보존행위로서 방해배제를 청구할 수 없다.
④ 丁이 경매를 통하여 乙의 지분을 취득한 경우, 甲ㆍ丁 사이에 구분소유적 공유관계가 당연히 인정되는 것은 아니다.
⑤ 甲이 자신의 특정 구분부분에 Y건물을 신축하여 소유한 경우, 乙이 강제경매를 통하여 甲의 지분을 취득하더라도 甲은 Y건물에 대한 관습법상의 법정지상권을 취득할 수 있다.

#### [2014-57] 甲은 乙소유 단독주택의 일부인 X부분에 대해 전세권을 취득하였다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲은 설정행위로 금지되지 않는 한 전세권을 제3자에게 양도할 수 있다.
② 전세권의 존속기간이 만료한 경우, 甲은 지상물매수를 청구할 수 있다.
③ 甲의 전세권 존속기간이 만료한 경우, 전세권의 용익물 권적 권능은 소멸한다.
④ 甲은 주택 전부에 대하여 후순위권리자보다 전세금의 우선변제를 받을 권리가 있다.
⑤ 乙이 전세금의 반환을 지체한 경우, 甲은 X부분이 아닌 나머지 주택 부분에 대하여 경매를 청구할 수 없다.

#### [2014-58] 상린관계에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 경계에 설치된 경계표는 원칙적으로 상린자의 공유로 추정한다.
② 토지소유자는 이웃 토지로부터 자연히 흘러오는 물을 막지 못한다.
③ 토지소유자는 처마물이 이웃에 직접 낙하하지 않도록 적당한 시설을 하여야 한다.
④ 건물을 축조함에는 특별한 관습이 없으면, 경계로부터 그 건물의 가장 돌출된 부분까지 반미터 이상의 거리를 두어야 한다.
⑤ 토지의 경계에 담이 없는 경우, 특별한 사정이 없는 한 인접지 소유자는 공동비용으로 통상의 담을 설치하는 데 협력할 의무가 없다.

#### [2014-59] 지역권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 지역권은 상속에 의해서 취득할 수 있다.
② 요역지와 분리하여 지역권만을 양도할 수 있다.
③ 지역권자는 일정한 목적을 위하여 타인의 토지를 자기 토지의 편익에 이용할 수 있다.
④ 토지의 불법점유자는 통행지역권의 시효취득을 주장할 수 없다.
⑤ 공유자 1인이 지역권을 취득한 때에는 다른 공유자도 이를 취득한다.

#### [2014-60] 甲은 그의 X건물을 乙에게 매도하여 점유를 이전하였고, 乙은 X건물을 사용ㆍ수익하면서 X건물의 보존ㆍ개량을 위하여 비용을 지출하였다. 甲과 乙 사이의 계약이 무효인 경우의 법률관계에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 乙이 악의인 경우에도 과실수취권이 인정된다.
② 선의의 乙은 甲에 대하여 통상의 필요비의 상환을 청구 할 수 있다.
③ 가액의 증가가 현존하는 경우에 乙은 甲에 대하여 유익비의 상환을 청구할 수 있다.
④ 선의의 乙은 甲에 대하여 점유ㆍ사용으로 인한 이익을 반환할 의무가 있다.
⑤ 乙의 비용상환청구권은 비용을 지출할 때 즉시 이행기가 도래한다.

#### [2014-61] 2014년 甲은 친구 乙과 계약명의신탁을 약정하였다. 그 사실을 알고 있는 丙은 명의수탁자 乙과의 매매계약에 따라 乙명의로 X토지의 소유권을 이전해 주었다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 의함)
① 乙은 X토지에 대한 소유권을 취득한다.
② 甲은 丙에 대하여 X토지에 대한 소유권이전등기를 청구할 수 있다.
③ 乙이 X토지의 소유권이전등기를 말소하지 않더라도 丙은 乙의 매매대금반환청구를 거절할 수 없다.
④ 乙이 X토지를 丁에게 매도하여 소유권이전등기를 해준 경우, 丁은 X토지의 소유권을 취득한다.
⑤ 乙이 X토지를 선의의 丁에게 매도하여 소유권이전등기를 해준 경우, 乙의 행위는 丙의 소유권에 대한 침해행위가 아니다.

#### [2014-62] 유치권과 동시이행항변권에 관한 설명으로 옳은 것을 모두 고른 것은?
====
ㄱ. 유치권과 동시이행항변권은 점유를 성립요건으로 한다
ㄴ. 유치권은 목적물에 관하여 생긴 채권의 담보를 목적으로 한다.
ㄷ. 유치권과 동시이행항변권은 동시에 서로 병존할 수 있다.
ㄹ. 유치권은 독립한 물권인 반면, 동시이행항변권은 이행거절권능에 해당한다.
====
① ㄱ, ㄴ
② ㄱ, ㄹ
③ ㄴ, ㄷ
④ ㄱ, ㄷ, ㄹ
⑤ ㄴ, ㄷ, ㄹ

#### [2014-63] 甲은 乙의 X토지에 대하여 가등기담보권을 취득하였으나, 乙은 변제기에 채무를 이행하지 않고 있다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲은 X토지의 경매를 청구할 수 있다.
② 제3자가 경매로 X토지의 소유권을 취득한 경우, 甲의 가등기담보권은 소멸한다.
③ 甲이 담보계약에 따른 담보권을 실행하여 X토지의 소유권을 취득하기 위해서는 청산절차를 거쳐야 한다.
④ X토지의 후순위권리자는 청산기간에 한정하여 그 피담보채권의 변제기 도래 전이라도 X토지의 경매를 청구할 수 있다.
⑤ 청산기간 전에 乙의 다른 채권자의 강제경매로 제3자가 X토지의 소유권을 취득한 경우에도 甲은 가등기에 기한 본등기를 청구할 수 있다.

#### [2014-64] 저당권의 소멸원인이 아닌 것은?
① 저당목적물이 전부 멸실된 경우
② 피담보채권이 시효완성으로 소멸한 경우
③ 저당목적물이 경매로 인해 제3자에게 매각된 경우
④ 지상권을 목적으로 제3자에게 저당권이 설정된 후 토지 소유자가 그 지상권을 취득한 경우
⑤ 저당권자가 자신 또는 제3자의 이익을 위해 존속시킬 필요가 없는 저당권의 목적물에 대한 소유권을 취득한 경우

#### [2014-65] 甲의 X건물을 임차한 乙은 X건물을 보존ㆍ개량하기 위해 丙으로부터 건축자재를 외상으로 공급받아 수리를 완료하였다. 그 후 임대차가 종료하였지만 수리비를 상환받지 못한 乙은 X건물을 점유하고 있다. 다음 설명 중 틀린 것은?
① 乙이 丙에게 외상대금을 지급하지 않으면 丙은 X건물에 대해 유치권을 행사할 수 있다.
② 乙은 甲이 수리비를 상환할 때까지 X건물에 대해 유치권을 행사할 수 있다.
③ 乙은 甲의 승낙 없이 X건물을 제3자에게 담보로 제공할 수 없다.
④ 乙은 수리비를 상환받기 위하여 X건물을 경매할 수 있다.
⑤ 만약 X건물을 甲으로부터 양수한 丁이 乙에게 X건물의 반환을 청구한 경우, 乙은 유치권으로 대항할 수 있다.

#### [2014-66] 甲은 乙에 대한 금전채권을 담보하기 위해 乙의 X토지에 저당권을 취득하였고, 그 후 丙이 X토지에 대하여 저당권을 취득하였다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 의함)
① 甲은 저당권을 피담보채권과 분리하여 제3자에게 양도할 수 있다.
② 乙이 甲에게 이행기에 피담보채무 전부를 변제하면 甲명의의 저당권은 말소등기를 하지 않아도 소멸한다.
③ 저당권등기는 효력존속요건이므로 甲명의의 저당권등기가 불법말소되면 甲의 저당권은 소멸한다.
④ 甲명의의 저당권등기가 불법말소된 후 丙의 경매신청으로 X토지가 제3자에게 매각되더라도 甲의 저당권등기는 회복될 수 있다.
⑤ 만약 甲명의의 저당권등기가 무효인 경우, 丙의 저당권이 존재하더라도 甲과 乙은 甲명의의 저당권등기를 다른 채권의 담보를 위한 저당권등기로 유용할 수 있다.

#### [2014-67] 2013. 10. 26. 甲은 친구 乙과 명의신탁약정을 하였다. 그 후 甲은 丙소유의 X토지를 매수하면서 丙에게 부탁하여 乙명의로 소유권이전등기를 하였고, X토지는 현재 甲이 점유하고 있다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 의함)
① 乙은 甲에게 X토지의 반환을 청구할 수 없다.
② 甲은 丙에게 X토지의 소유권이전을 청구할 수 없다.
③ 丙은 乙에게 X토지의 소유권이전등기말소를 청구할 수 없다.
④ 甲은 乙에게 부당이득반환을 원인으로 소유권이전등기를 청구할 수 있다.
⑤ 甲은 乙에게 부당이득반환청구권을 피담보채권으로 하여 유치권을 주장할 수 있다.

#### [2014-68] 甲은 건물 소유의 목적으로 乙의 X토지를 임차하여 그 위에 Y건물을 신축한 후 사용하고 있다. 다음 설명중 틀린 것은?(다툼이 있으면 판례에 의함)
① Y건물이 무허가건물이더라도 특별한 사정이 없는 한 甲의 지상물매수청구권의 대상이 될 수 있다.
② 甲의 차임연체를 이유로 乙이 임대차계약을 해지한 경우, 甲은 지상물매수청구권을 행사할 수 없다.
③ 임대차 기간의 정함이 없는 경우, 乙이 해지통고를 하면 甲은 지상물매수청구권을 행사할 수 있다.
④ 대항력을 갖춘 甲의 임차권이 기간만료로 소멸한 후 乙이 X토지를 丙에게 양도한 경우, 甲은 丙을 상대로 지상물 매수청구권을 행사할 수 있다.
⑤ 甲이 Y건물에 근저당권을 설정한 경우, 임대차기간이 만료하면 甲은 乙을 상대로 지상물매수청구권을 행사할 수 없다.

#### [2014-69] 집합건물의 소유 및 관리에 관한 법률에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 집합건물의 임차인은 관리인이 될 수 없다.
② 서면결의의 방법에 의한 재건축결의가 가능하다.
③ 전유부분에 설정된 저당권의 효력은 특별한 사정이 없는 한 대지사용권에 미친다.
④ 관리단집회는 구분소유자 전원이 동의하면 소집절차를 거치지 않고 소집할 수 있다.
⑤ 공용부분 관리비에 대한 연체료는 특별승계인에게 승계되는 공용부분 관리비에 포함되지 않는다.

#### [2014-70] 甲은 채무자 乙의 X토지와 제3자 丙의 Y토지에 대하여 피담보채권 5천만원의 1번 공동저당권을, 丁은 X토지에 乙에 대한 피담보채권 2천만원의 2번 저당권을, 戊는 Y토지에 丙에 대한 피담보채권 3천만원의 2번 저당권을 취득하였다. Y토지가 경매되어 배당금액 5천만원 전액이 甲에게 배당된 후 X토지 매각대금 중 4천만원이 배당되는 경우, 戊가 X토지 매각대금에서 배당받을 수 있는 금액은?(다툼이 있으면 판례에 의함)
① 0원
② 1천만원
③ 2천만원
④ 3천만원
⑤ 4천만원

#### [2014-71] 2014. 1. 甲은 선순위 권리자가 없는 乙의 X상가건물을 보증금 1억원, 월차임 40만원에 임차하여 대항요건을 갖추고 확정일자를 받았다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲이 3기의 차임 상당액을 연체한 경우, 乙은 甲의 계약갱신요구를 거절할 수 있다.
② 임대기간에 대하여 별도의 약정이 없는 경우, 그 기간은 1년으로 본다.
③ 甲이 보증금반환청구소송의 확정판결에 따라 X건물에 대한 경매를 신청하는 경우, 甲의 건물명도의무이행은 집행개시의 요건이다.
④ 甲이 X건물의 환가대금에서 보증금을 우선변제받기 위해서는 대항요건이 배당요구 종기까지 존속하여야 한다.
⑤ 보증금이 전액 변제되지 않는 한 X건물에 대한 경매가 실시되어 매각되더라도 甲의 임차권은 존속한다.

#### [2014-72] 일시사용을 위한 임대차에서 인정되는 권리를 모두 고른 것은?
====
ㄱ. 임차인의 비용상환청구권
ㄴ. 임대인의 차임증액청구권
ㄷ. 임차인의 부속물매수청구원
ㄹ. 임차건물의 부속물에 대한 법정질권
====
① ㄱ
② ㄹ
③ ㄱ, ㄴ
④ ㄴ, ㄷ
⑤ ㄷ, ㄹ

#### [2014-73] 2013. 2. 1. 甲은 乙의 서울 소재 X주택을 보증금 7천만원, 임대기간 1년으로 하여 임차하면서, 같은 날 입주와 동시에 주민등록을 마쳤다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 의함)
① 2014. 1. 1. 乙은 甲에게 500만원의 보증금 증액을 청구 할 수 있다.
② 2014. 3. 1. 甲이 임차권의 존속을 주장하더라도 乙은 약정기간의 만료를 이유로 甲에게 X주택의 인도를 청구할 수 있다.
③ 2013. 6. 1. 동거가족이 없는 甲이 자신의 주민등록을 다른 주소로 이전하였더라도 계속하여 X주택에 거주하고 있었다면 대항력은 유지된다.
④ 2012. 12. 1. 乙이 丙에게 X주택에 대하여 근저당권을 설정해 주었더라도 甲은 3,500만원의 한도에서 丙보다 우선변제를 받을 수 있다.
⑤ 2013. 7. 1. 乙이 丁에게 X주택을 양도한 후 임대차기간이 만료된 경우, 특별한 사정이 없는 한 甲은 丁에 대하여만 보증금의 반환을 청구할 수 있다.

#### [2014-74] 동시이행항변권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 계약해제로 인한 당사자 상호간의 원상회복의무는 동시 이행관계에 있다.
② 구분소유적 공유관계가 해소되는 경우, 공유지분권자 상호간의 지분이전등기의무는 동시이행관계에 있다.
③ 임차권등기명령에 의해 등기된 임차권등기말소의무와 보증금반환의무는 동시이행관계에 있다.
④ 동시이행관계에 있는 어느 일방의 채권이 양도되더라도 그 동일성이 인정되는 한 동시이행관계는 존속한다.
⑤ 일방당사자가 선이행의무를 부담하더라도 상대방의 채무이행이 곤란할 현저한 사유가 있는 경우에는 동시 이행항변권을 행사할 수 있다.

#### [2014-75] 청약과 승낙에 관한 설명으로 틀린 것은?
① 불특정 다수인에 대한 청약은 효력이 있다.
② 불특정 다수인에 대한 승낙은 효력이 없다.
③ 청약과 승낙은 각각 그 발송시에 효력이 생긴다.
④ 승낙기간을 정하지 않은 청약은 상당한 기간 내에 승낙의 통지를 받지 못한 때 그 효력을 잃는다.
⑤ 승낙기간을 정하지 않은 청약에 대하여 연착된 승낙은 청약자가 이를 새로운 청약으로 볼 수 있다.

#### [2014-76] 매도인 甲과 매수인 乙이 계약을 하면서 그 대금을 丙에게 지급하기로 하는 제3자를 위한 계약을 체결 하였다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 乙은 甲의 丙에 대한 항변으로 丙에게 대항할 수 있다.
② 丙이 수익의 의사표시를 한 후 乙이 대금을 지급하지 않으면, 甲은 계약을 해제할 수 있다.
③ 丙이 수익의 의사표시를 하면 특별한 사정이 없는 한 乙에 대한 대금지급청구권을 확정적으로 취득한다.
④ 乙이 상당한 기간을 정하여 丙에게 수익 여부의 확답을 최고하였으나 그 기간 내에 확답을 받지 못하면, 丙이 수익을 거절한 것으로 본다.
⑤ 乙이 丙에게 대금을 지급한 후 계약이 해제된 경우, 특별한 사정이 없는 한 乙은 丙에게 대금의 반환을 청구할 수 없다.

#### [2014-77] 매매계약에 관한 설명으로 틀린 것은?
① 매매의 목적이 된 권리가 타인에게 속한 경우에는 매도인은 그 권리를 취득하여 매수인에게 이전하여야 한다.
② 매매계약에 관한 비용은 특별한 사정이 없는 한 당사자가 균분하여 부담한다.
③ 담보책임의 면책특약이 있는 경우, 매도인은 알면서 고지하지 않은 하자에 대해서도 그 책임을 면한다.
④ 목적물의 인도와 동시에 대금을 지급할 경우, 특별한 사정이 없는 한 대금은 목적물의 인도장소에서 지급해야 한다.
⑤ 당사자 일방에 대한 의무이행의 기한이 있는 때에는 상대방의 의무이행에 대하여도 동일한 기한이 있는 것으로 추정한다.

#### [2014-78] 甲은 자신의 2억원 상당 건물을 乙의 토지와 교환하는 계약을 체결하면서 乙로부터 1억원을 보충하여 지급받기로 하였다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲ㆍ乙 사이의 계약은 불요식계약이다.
② 甲과 乙은 특별한 사정이 없는 한 서로 하자담보책임을 지지 않는다.
③ 乙의 보충금 1억원의 미지급은 교환계약의 해제사유에 해당된다.
④ 계약체결 후 건물이 乙의 과실로 소실되었다면, 乙의 보충금지급의무는 소멸하지 않는다.
⑤ 보충금의 지급기한을 정하지 않았다면, 乙은 건물을 인도받은 날부터 지급하지 않은 보충금의 이자를 甲에게 지급해야 한다.

#### [2014-79] 계약해제에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 계약이 적법하게 해제된 후에도 착오를 원인으로 그 계약을 취소할 수 있다.
② 계약을 합의해제한 경우에도 민법상 해제의 효과에 따른 제3자 보호규정이 적용된다.
③ 매도인의 이행불능을 이유로 매수인이 계약을 해제하려면 매매대금의 변제제공을 하여야 한다.
④ 토지매수인으로부터 그 토지 위에 신축된 건물을 매수한자는 토지매매계약의 해제로 인하여 보호받는 제3자에 해당하지 않는다.
⑤ 공유자가 공유토지에 대한 매매계약을 체결한 경우, 특별한 사정이 없는 한 공유자 중 1인은 다른 공유자와 별개로 자신의 지분에 관하여 매매계약을 해제할 수 있다.

#### [2014-80] 2014. 5. 1. 甲이 그의 건물을 乙에게 매도하면서 같은해 5. 10. 계약금을, 그로부터 2개월 후에 중도금 및 잔금을 지급받기로 하였다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲ㆍ乙 사이의 계약금계약은 낙성계약이다.
② 乙이 지급한 계약금은 다른 약정이 없는 한 해약금으로 추정한다.
③ 乙이 계약금을 지급하지 않으면 甲은 계약금약정을 해제할 수 있다.
④ 乙이 2014. 6. 10. 중도금을 지급한 경우, 甲은 계약금의 배액을 상환하고 계약을 해제할 수 없다.
⑤ 乙이 2014. 7. 10. 중도금과 잔금을 지급하였으나 甲이 소유권이전등기를 해주지 않으면 乙은 매매계약을 해제할 수 있다.