2013년

2과목 : 민법 및 민사특별법

#### [2013-41] 의사표시에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 진의 아닌 의사표시는 원칙적으로 무효이다.
② 의사표시자가 그 통지를 발송한 후 사망하거나 제한능력자가 되어도 의사표시의 효력에 영향을 미치지 않는다.
③ 상대방 있는 의사표시는 특별한 사정이 없으면 상대방에게 도달한 때에 그 효력이 생긴다.
④ 의사표시자가 과실 없이 상대방을 알지 못하는 경우, 의사표시는「민사소송법」의 공시송달 규정에 의하여 송달할 수 있다.
⑤ 보통우편의 방법으로 발송되었다는 사실만으로는 상당한 기간 내에 도달하였다고 추정할 수 없다.

#### [2013-42] 법률행위의 효력이 발생하기 위한 요건이 아닌 것은?(다툼이 있으면 판례에 의함)
① 대리행위에서 대리권의 존재
② 정지조건부 법률행위에서 조건의 성취
③ 농지거래계약에서 농지취득자격증명
④ 법률행위 내용의 적법성
⑤ 토지거래허가구역 내의 토지거래계약에 관한 관할관청의 허가

#### [2013-43] 불공정한 법률행위에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 무경험이란 거래 일반의 경험부족을 말하는 것이 아니라 해당 특정영역에서의 경험부족을 말한다.
② 불공정한 법률행위가 되기 위해서는 피해자에게 궁박, 경솔과 무경험 가운데 어느 하나가 필요하다.
③ 법률행위가 현저하게 공정을 잃었다고 하여 곧 그것이 궁박, 경솔 또는 무경험으로 이루어진 것으로 추정되지 않는다.
④ 불공정한 법률행위로 불이익을 입는 당사자가 불공정성을 소송 등으로 주장할 수 없도록 하는 부제소합의는 특별한 사정이 없으면 무효이다.
⑤ 불공정한 법률행위는 약자적 지위에 있는 자의 궁박, 경솔 또는 무경험을 이용한 폭리행위를 규제하려는 데에 그 목적이 있다.

#### [2013-44] 甲은 乙에게 X토지를 ㎡당 98만원에 매도하려고 했는데, 잘못하여 청약서에 ㎡당 89만원으로 기재하였고, 이에 대해 乙이 승낙하였다. 그 후 X토지의 시가가 ㎡당 158만원으로 폭등하자 甲이 丙에게 X토지를 ㎡당 158만원에 매도하고 소유권을 이전해 주었다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 乙은 甲과 丙사이의 매매계약을 사기를 이유로 취소할 수 없다.
② 甲과 乙사이의 매매계약은 특별한 사정이 없는 한 ㎡당 89만원에 성립한다.
③ 乙은 丙명의로 이루어진 소유권이전등기의 말소를 청구할 수 없다.
④ 만일 甲과 乙이 ㎡당 98만원으로 합의하였으나 ㎡당 89만원으로 기재되었다면 甲은 착오를 이유로 매매계약을 취소할 수 없다.
⑤ 만일 甲의 배임행위에 적극 가담한 丙으로부터 선의의 丁이 X토지를 취득하였다면 丁은 甲과 丙사이의 매매계약의 유효를 주장할 수 있다.

#### [2013-45] 법률행위의 종류에 관한 연결이 틀린 것은?
① 채권행위 - 교환
② 상대방 없는 단독행위 - 계약해제
③ 처분행위 - 지상권설정행위
④ 유상행위 - 임대차
⑤ 무상행위 - 증여

#### [2013-46] 대리인에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 복대리인은 그 권한 내에서 대리인의 이름으로 법률행위를 한다.
② 수권행위로 권한을 정하지 않은 경우, 대리인은 대리의 목적인 물건이나 권리의 성질이 변하지 않는 범위에서 그 이용행위를 할 수 있다.
③ 대리인은 그 권한 내에서 사자를 사용할 수 있으며, 이때에는 복대리에 관한 규정이 적용되지 않는다.
④ 대리인에 대하여 성년후견이 개시되면 대리권은 소멸한다.
⑤ 대리인이 수인인 때에 법률이나 수권행위로 다른 정함이 없으면 각자 본인을 대리한다.

#### [2013-47] 법률효과가 확정적이지 않은 것을 모두 고른 것은? (다툼이 있으면 판례에 의함)
====
ㄱ. 상대방과 통정한 허위의 법률행위
ㄴ. 무권대리인의 상대방이 거절한 의사표시
ㄷ. 상대방의 강박으로 인한 의사표시
ㄹ. 조건부 권리를 처분하는 법률행위
ㅁ. 소유권유보부매매를 원인으로 하는 동산 소유권 취득
====
① ㄱ, ㄷ
② ㄱ, ㄹ
③ ㄴ, ㄹ
④ ㄴ, ㅁ
⑤ ㄷ, ㅁ

#### [2013-48] 甲의 대리인 乙은 甲 소유의 부동산을 丙에게 매도하기로 약정하였다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 乙은 특별한 사정이 없으면 丙으로부터 계약금을 수령할 권한이 있다.
② 乙이 丙의 기망행위로 매매계약을 체결한 경우, 甲은 이를 취소할 수 있다.
③ 乙이 매매계약서에 甲의 이름을 기재하고 甲의 인장을 날인한 때에도 유효한 대리행위가 될 수 있다.
④ 乙이 매매계약을 체결하면서 甲을 위한 것임을 표시하지 않은 경우, 특별한 사정이 없으면 그 의사표시는 자기를 위한 것으로 본다.
⑤ 만일 乙이 미성년자인 경우, 甲은 乙이 제한능력자임을 이유로 매매계약을 취소할 수 있다.

#### [2013-49] 반사회적 법률행위로서 무효가 아닌 것은?(다툼이 있으면 판례에 의함)
① 어떤 일이 있어도 이혼하지 않기로 하는 약정
② 불륜관계의 종료를 해제조건으로 하여 내연녀에게 한 증여
③ 수증자가 부동산 매도인의 배임행위에 적극 가담하여 체결한 증여계약
④ 관계 당사자 전원의 합의로 이루어진 중간생략등기
⑤ 공무원의 직무에 관하여 특별한 청탁을 하고 그 보수로 고액의 금전을 지급할 것을 내용으로 한 약정

#### [2013-50] 법률행위의 무효에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 무효인 법률행위를 추인하면 특별한 사정이 없는 한 처음부터 새로운 법률행위를 한 것으로 본다.
② 추인 요건을 갖추면 취소로 무효가 된 법률행위의 추인도 허용된다.
③ 사회질서의 위반으로 무효인 법률행위는 추인의 대상이 되지 않는다.
④ 무효인 법률행위에 따른 법률효과를 침해하는 것처럼 보이는 위법행위가 있더라도 그 손해배상을 청구할 수 없다.
⑤ 폭리행위로 무효가 된 법률행위는 다른 법률행위로 전환될 수 있다.

#### [2013-51] 부동산 물권을 등기 없이 취득할 수 있는 경우가 아닌 것은?(다툼이 있으면 판례에 의함)
① 신축건물의 소유권 취득
② 분묘기지권의 취득
③ 상속에 의한 소유권 취득
④ 법정저당권의 취득
⑤ 점유취득시효에 의한 지역권의 취득

#### [2013-52] 민법상 점유에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 점유자는 평온ㆍ공연하게 점유한 것으로 추정한다.
② 매매계약을 원인으로 토지의 소유자로 등기한 자는 통상 이전등기할 때에 그 토지를 인도받아 점유한 것으로 보아야 한다.
③ 점유자가 점유물에 대하여 행사하는 권리는 적법하게 보유한 것으로 추정한다.
④ 악의의 점유자는 그의 잘못 없이 과실을 훼손 또는 수취하지 못한 때에도 그 과실의 대가를 보상하여야 한다.
⑤ 점유자의 특정승계인은 자기의 점유와 전(前)점유자의 점유를 아울러 주장할 수 있다.

#### [2013-53] 주위토지통행권에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 주위토지통행권자는 담장과 같은 축조물이 통행에 방해가 되더라도 그 철거를 청구할 수 없다.
② 토지분할로 무상주위토지통행권을 취득한 분할토지의 소유자가 그 토지를 양도한 경우, 양수인에게는 무상주위토지통행권이 인정되지 않는다.
③ 소유 토지의 용도에 필요한 통로가 이미 있더라도 그 통로를 사용하는 것보다 더 편리하다면 다른 장소로 통행할 권리가 인정된다.
④ 기존의 통로가 있으면, 그것이 당해 토지의 이용에 부적합하여 실제로 통로로서의 충분한 기능을 하지 못할 때에도 주위토지통행권은 인정되지 않는다.
⑤ 주위토지통행권은 일단 발생하면 나중에 그 토지에 접하는 공로가 개설되어 그 통행권을 인정할 필요가 없어지더라도 소멸하지 않는다.

#### [2013-54] 부동산의 점유취득시효에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 시효취득자는 취득시효의 완성으로 바로 소유권을 취득할 수 없고, 이를 원인으로 소유권이전등기청구권이 발생할 뿐이다.
② 시효취득자의 점유가 계속되는 동안 이미 발생한 소유권이전등기청구권은 시효로 소멸하지 않는다.
③ 시효취득으로 인한 소유권이전등기청구권이 발생하면 부동산소유자와 시효취득자 사이에 계약상의 채권관계가 성립한 것으로 본다.
④ 등기부상 소유명의자가 진정한 소유자가 아니면 원칙적으로 그를 상대로 취득시효의 완성을 원인으로 소유권이전등기를 청구할 수 없다.
⑤ 취득시효 완성 후 시효취득자가 소유권이전등기절차 이행의 소를 제기하였으나 그 후 상대방의 소유를 인정하여 합의로 소를 취하한 경우, 특별한 사정이 없으면 이는 시효이익의 포기이다.

#### [2013-55] 甲과 乙은 X토지를 각 1/2의 지분을 가지고 공유하고 있다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲의 지분에 관하여 제3자 명의로 원인무효의 등기가 이루어진 경우, 乙은 공유물의 보존행위로 그 등기의 말소를 청구할 수 있다.
② 甲이 乙의 동의 없이 X토지 전부를 단독으로 사용하고 있다면, 乙은 공유물의 보존행위로 X토지 전부를 자기에게 반환할 것을 청구할 수 있다.
③ 甲과 乙이 X토지의 각 특정 부분을 구분하여 소유하면서 공유등기를 한 경우, 甲 자신이 구분소유하는 지상에 건물을 신축하더라도 乙은 그 건물의 철거를 청구할 수 없다.
④ 甲이 乙의 동의 없이 X토지의 1/2을 배타적으로 사용하는 경우, 乙은 그의 지분 비율로 甲에게 부당이득의 반환을 청구할 수 있다.
⑤ 제3자가 권원 없이 자기명의로 X토지의 소유권이전등기를 한 경우, 甲은 공유물의 보존행위로 원인무효의 등기 전부의 말소를 청구할 수 있다.

#### [2013-56] 물권의 소멸에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 소유권과 저당권은 소멸시효에 걸리지 않는다.
② 물권의 포기는 물권의 소멸을 목적으로 하는 단독행위이다.
③ 전세권이 저당권의 목적인 경우, 저당권자의 동의 없이 전세권을 포기할 수 없다.
④ 존속기간이 있는 지상권은 특별한 사정이 없으면 그 기간의 만료로 말소등기 없이 소멸한다.
⑤ 甲의 토지에 乙이 지상권을 취득한 후, 그 토지에 저당권을 취득한 丙이 그 토지의 소유권을 취득하더라도 丙의 저당권은 소멸하지 않는다.

#### [2013-57] 관습법상 법정지상권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 법정지상권을 양도하기 위해서는 등기하여야 한다.
② 법정지상권자는 그 지상권을 등기하여야 지상권을 취득할 당시의 토지소유자로부터 토지를 양수한 제3자에게 대항할 수 있다.
③ 법정지상권자는 건물의 유지ㆍ사용에 필요한 범위에서 지상권이 성립된 토지를 자유로이 사용할 수 있다.
④ 지료에 관하여 토지소유자와 협의가 이루어지지 않으면 당사자의 청구에 의하여 법원이 이를 정한다.
⑤ 동일인 소유의 건물과 토지가 매매로 인하여 서로 소유자가 다르게 되었으나, 당사자가 그 건물을 철거하기로 합의한 때에는 관습법상 법정지상권이 성립하지 않는다.

#### [2013-58] 지역권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 토지의 불법점유자는 통행지역권을 시효취득할 수 없다.
② 승역지의 점유가 침탈된 때에도 지역권자는 승역지의 반환을 청구할 수 없다.
③ 승역지는 1필의 토지이어야 하지만, 요역지는 1필의 토지 일부라도 무방하다.
④ 요역지의 전세권자는 특별한 사정이 없으면 지역권을 행사할 수 있다.
⑤ 공유자의 1인이 지역권을 취득한 때에는 다른 공유자도 이를 취득한다.

#### [2013-59] 전세권에 관한 설명으로 틀린 것은?
① 건물의 사용ㆍ수익을 목적으로 하는 전세권에는 상린관계에 관한 규정이 준용되지 않는다.
② 전세권자는 그의 점유가 침해당한 때에는 점유보호청구권을 행사할 수 있다.
③ 설정행위로 금지하지 않으면 전세권자는 전세권을 타인에게 양도할 수 있다.
④ 전세권설정자가 전세금의 반환을 지체하면 전세권자는 그 목적물의 경매를 청구할 수 있다.
⑤ 전세권자가 그 목적물의 성질에 의하여 정하여진 용도에 따라 목적물을 사용ㆍ수익하지 않으면 전세권설정자는 전세권의 소멸을 청구할 수 있다.

#### [2013-60] 유치권자의 권리가 아닌 것은?
① 경매권	② 과실수취권
③ 비용상환청구권④ 간이변제충당권
⑤ 타담보제공청구권

#### [2013-61] 저당권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 저당권설정자가 저당권 설정 후 건물을 축조하였으나 경매 당시 제3자가 그 건물을 소유하는 때에도 일괄경매청구권이 인정된다.
② 채권자, 채무자와 제3자 사이에 합의가 있고 채권이 실질적으로 제3자에게 귀속되었다고 볼 수 있는 사정이 있으면 제3자 명의의 저당권설정등기는 유효하다.
③ 저당권설정행위는 처분행위이므로 처분의 권리 또는 권한을 가진 자만이 저당권을 설정할 수 있다.
④ 특별한 사정이 없으면, 저당권이전을 부기등기 하는 방법으로 무효인 저당권등기를 다른 채권자를 위한 담보로 유용할 수 있다.
⑤ 특별한 사정이 없으면, 저당권의 피담보채권 소멸 후 그 말소등기 전에 피담보채권의 전부명령을 받아 저당권이전등기가 이루어진 때에도 그 저당권은 효력이 없다.

#### [2013-62] 유치권의 소멸사유가 아닌 것은?
① 혼동
② 점유의 상실
③ 유치물의 멸실
④ 제3자에게의 유치물 보관
⑤ 채무자 아닌 유치물 소유자의 변제

#### [2013-63] 甲은 X건물에 1번 저당권을 취득하였고, 이어서 乙이 전세권을 취득하였다. 그 후 丙이 2번 저당권을 취득하였고, 경매신청 전에 X건물의 소유자의 부탁으로 비가 새는 X건물의 지붕을 수리한 丁이 현재 유치권을 행사하고 있다. 다음 설명 중 옳은 것은?
① 甲의 경매신청으로 戊가 X건물을 매수하면 X건물을 목적으로 하는 모든 권리는 소멸한다.
② 乙의 경매신청으로 戊가 X건물을 매수하면 甲의 저당권과 丁의 유치권을 제외한 모든 권리는 소멸한다.
③ 丙의 경매신청으로 戊가 X건물을 매수하면 丁의 유치권을 제외한 모든 권리는 소멸한다.
④ 丁의 경매신청으로 戊가 X건물을 매수하면 乙의 전세권을 제외한 모든 권리는 소멸한다.
⑤ 甲의 경매신청으로 戊가 X건물을 매수하면 乙의 전세권과 丁의 유치권을 제외한 모든 권리는 소멸한다.

#### [2013-64] 근저당권에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 채권최고액은 저당목적물로부터 우선변제를 받을 수 있는 한도액을 의미한다.
② 채무자의 채무액이 채권최고액을 초과하는 경우, 물상보증인은 채무자의 채무 전액을 변제하지 않으면 근저당권설정등기의 말소를 청구할 수 없다.
③ 근저당권의 피담보채권이 확정된 경우, 확정 이후에 새로운 거래관계에서 발생하는 채권은 그 근저당권에 의하여 담보되지 않는다.
④ 근저당권자가 경매를 신청한 경우, 그 근저당권의 피담보채권은 경매를 신청한 때 확정된다.
⑤ 근저당권의 후순위 담보권자가 경매를 신청한 경우, 근저당권의 피담보채권은 매수인이 매각대금을 완납한 때 확정된다.

#### [2013-65] 계약에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 계약을 합의해지하기 위해서는 청약과 승낙이라는 서로 대립하는 의사표시가 합치되어야 한다.
② 당사자 사이에 동일한 내용의 청약이 서로 교차된 경우, 양 청약이 상대방에게 도달한 때에 계약은 성립한다.
③ 계약의 합의해제에 관한 청약에 대하여 상대방이 조건을 붙여 승낙한 때에는 그 청약은 효력을 잃는다.
④ 청약자가 ‘일정한 기간 내에 회답이 없으면 승낙한 것으로 본다’고 표시한 경우, 특별한 사정이 없으면 상대방은 이에 구속된다.
⑤ 청약자의 의사표시나 관습에 의하여 승낙의 통지가 필요하지 않은 경우, 계약은 승낙의 의사표시로 인정되는 사실이 있는 때에 성립한다.

#### [2013-66] 甲은 자신의 토지를 乙에게 매도하기로 하고, 매매대금을 자신의 채권자 丙에게 지급하도록 乙과 약정하였다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 丙이 매매대금의 수령여부에 대한 의사를 표시하지 않는 경우, 乙은 상당한 기간을 정하여 丙에게 계약이익의 향수 여부에 대한 확답을 최고할 수 있다.
② 丙은 乙에게 수익의 의사표시를 하면 그에게 직접 매매대금의 지급을 청구할 수 있다.
③ 丙이 매매대금의 지급을 청구하였으나 乙이 이를 지급하지 않으면 丙은 매매계약을 해제할 수 있다.
④ 乙이 丙에게 매매대금을 지급하였는데 계약이 해제된 경우, 특별한 사정이 없는 한 乙은 丙에게 부당이득반환을 청구할 수 없다.
⑤ 甲이 소유권을 이전하지 않으면 乙은 특별한 사정이 없는 한 丙의 대금지급청구를 거절할 수 있다.

#### [2013-67] 계약해제에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 계약을 해제하면 계약은 처음부터 없었던 것으로 된다.
② 계약이 합의해제된 경우, 당사자 일방이 상대방에게 손해배상을 하기로 하는 등 특별한 사정이 없으면 채무불이행으로 인한 손해배상을 청구할 수 없다.
③ 계약해제의 효과로 반환할 이익의 범위는 특별한 사정이 없으면 이익의 현존 여부나 선의ㆍ악의를 불문하고 받은 이익의 전부이다.
④ 해제된 계약으로부터 생긴 법률효과에 기초하여 해제 후 말소등기 전에 양립할 수 없는 새로운 이해관계를 맺은 제3자는 그 선의ㆍ악의를 불문하고 해제에 의하여 영향을 받지 않는다.
⑤ 중도금을 지급한 부동산매수인도 약정해제사유가 발생하면 계약을 해제할 수 있다.

#### [2013-68] 甲은 자신의 토지를 乙에게 매도하였으나 소유권이전등기의무의 이행기가 도래하기 전에 그 토지에 대한 丙의 강제수용(재결수용)으로 보상금을 받게 되었다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲의 乙에 대한 소유권이전의무는 소멸한다.
② 乙은 甲에게 보상금청구권의 양도를 청구할 수 있다.
③ 甲이 丙으로부터 보상금을 수령하였다면 乙은 甲에게 보상금의 반환을 청구할 수 있다.
④ 乙은 소유권이전의무의 불이행을 이유로 甲에게 손해배상을 청구할 수 없다.
⑤ 만일 乙이 甲에게 계약금을 지급하였다면 乙은 그 배액의 반환을 청구할 수 있다.

#### [2013-69] 매매에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 측량비용, 등기비용, 담보권 말소비용 등 매매계약에 관한 비용은 특별한 사정이 없으면 당사자 쌍방이 균분하여 분담한다.
② 매매목적물의 인도와 동시에 대금을 지급할 때에는 특별한 사정이 없으면 그 인도장소에서 대금을 지급하여야 한다.
③ 매매의 일방예약은 상대방이 매매를 완결할 의사를 표시하는 때에 매매의 효력이 생긴다.
④ 당사자 사이에 다른 약정이 없으면 계약금은 해약금으로 추정한다.
⑤ 계약금계약은 매매계약에 종된 계약이고 요물계약이다.

#### [2013-70] 매도인의 담보책임에 관한 설명으로 틀린 것은?
① 변제기에 도달한 채권의 매도인이 채무자의 자력을 담보한 경우, 원칙적으로 매매계약 당시의 자력을 담보한 것으로 추정한다.
② 저당권이 설정된 부동산의 매수인이 그 소유권을 보존하기 위해 출재한 경우, 매수인은 매도인에게 그 상환을 청구할 수 있다.
③ 매매의 목적이 된 부동산에 대항력을 갖춘 임대차가 있는 경우, 선의의 매수인은 그로 인해 계약의 목적을 달성할 수 없음을 이유로 계약을 해제할 수 있다.
④ 매매의 목적인 권리의 일부가 타인에게 속하고 잔존한 부분만이면 매수하지 아니하였을 경우, 악의의 매수인은 그 사실을 안 날로부터 1년 내에 해제권을 행사할 수 있다.
⑤ 매매계약 당시에 그 목적물의 일부가 멸실된 경우, 선의의 매수인은 대금의 감액을 청구할 수 있다.

#### [2013-71] 경매를 통해 X건물을 매수한 甲은 매각대금을 완납하지 않고 X건물을 乙소유의 Y임야와 교환하기로 乙과 약정하였다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲과 乙사이의 교환계약은 유효하게 성립한다.
② 甲이 乙에게 X건물의 소유권을 이전할 수 없는 경우, 선의의 乙은 손해배상을 청구할 수 있다.
③ X건물과 Y임야의 가격이 달라 乙이 일정한 금액을 보충하여 지급할 것을 약정한 때에는 매매계약이 성립한다.
④ 매각대금을 완납한 甲이 乙에게 X건물의 소유권을 이전한 경우, 甲은 X건물의 하자에 대하여 담보책임을 진다.
⑤ 乙이 시가보다 높은 가액을 Y임야의 시가로 고지한 때에도 특별한 사정이 없으면 甲은 사기를 이유로 교환계약을 취소하지 못한다.

#### [2013-72] 임대인과 임차인 모두에게 인정될 수 있는 권리는?
① 임차권	
② 계약해지권
③ 보증금반환채권
④ 비용상환청구권
⑤ 부속물매수청구권

#### [2013-73] 토지임차인의 지상물매수청구권에 관한 설명으로 옳은 것은?(다툼이 있으면 판례에 의함)
① 매수청구권의 대상이 되는 지상물은 임대인의 동의를 얻어 신축한 것에 한정된다.
② 임차인이 지상물의 소유권을 타인에게 이전한 경우, 임차인은 지상물매수청구권을 행사할 수 없다.
③ 임차인이 임대인에게 계약의 갱신을 청구하지 않더라도 특별한 사정이 없으면 임차인은 지상물의 매수를 청구할 수 있다.
④ 임대인의 해지통고로 기간의 정함이 없는 토지임차권이 소멸한 경우에는 임차인은 지상물의 매수를 청구할 수 없다.
⑤ 임대인과 임차인 사이에 임대차기간이 만료하면 임차인이 지상건물을 철거하기로 한 약정은 특별한 사정이 없으면 유효하다.

#### [2013-74] 임차인 乙은 임대인 甲의 동의 없이 丙과 전대차계약을 맺고 임차건물을 인도해 주었다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 의함)
① 甲과 乙사이의 합의로 임대차계약이 종료하더라도 丙은 甲에게 전차권을 주장할 수 있다.
② 丙은 乙에 대한 차임의 지급으로 甲에게 대항할 수 없으므로, 차임을 甲에게 직접 지급하여야 한다.
③ 甲은 임대차계약이 존속하는 한도 내에서는 丙에게 불법점유를 이유로 한 차임상당의 손해배상청구를 할 수 없다.
④ 임대차계약이 해지통고로 종료하는 경우, 丙에게 그 사유를 통지하지 않으면 甲은 해지로써 丙에게 대항할 수 없다.
⑤ 전대차가 종료하면 丙은 전차물 사용의 편익을 위하여 乙의 동의를 얻어 부속한 물건의 매수를 甲에게 청구할 수 있다.

#### [2013-75] 주택임대차보호법에 관한 설명으로 틀린 것은?(다툼이 있으면 판례에 의함)
① 임대차계약이 묵시적으로 갱신되면 그 임대차의 존속기간은 2년으로 본다.
② 주택의 전부를 일시적으로 사용하기 위한 임대차인 것이 명백한 경우에도「주택임대차보호법」이 적용된다.
③ 임대차보증금의 감액으로「주택임대차보호법」상 소액임차인에 해당하게 된 경우, 특별한 사정이 없으면 소액임차인으로서 보호받을 수 있다.
④ 임대차 성립 시에 임차주택과 그 대지가 임대인의 소유인 경우, 대항력과 확정일자를 갖춘 임차인은 대지만 경매되더라도 그 매각대금으로부터 우선변제를 받을 수 있다.
⑤ 「주택임대차보호법」상 대항력을 갖춘 임차인의 임대차보증금반환채권이 가압류된 상태에서 주택이 양도된 경우, 양수인은 채권가압류의 제3채무자 지위를 승계한다.

#### [2013-76] 집합건물의 소유 및 관리에 관한 법률에 관한 설명으로 틀린 것은?
① 관리단에는 규약으로 정하는 바에 따라 관리위원회를 둘 수 있다.
② 관리인은 매년 회계연도 종료 후 3개월 이내에 정기 관리단집회를 소집하여야 한다.
③ 관리인은 구분소유자일 필요가 없으며, 그 임기는 2년의 범위에서 규약으로 정한다.
④ 관리인에게 부정한 행위가 있을 때에는 각 구분소유자는 관리인의 해임을 법원에 청구할 수 있다.
⑤ 규약에 다른 정함이 없으면 관리위원회의 위원은 전유부분을 점유하는 자 중에서 관리단집회의 결의에 의하여 선출한다.

#### [2013-77] 집합건물의 소유 및 관리에 관한 법률상 재건축을 하기 위해서는 구분소유자의 ( ) 이상 및 의결권의 ( ) 이상의 결의가 있어야 한다. 빈 칸에 공통으로 알맞은 것은?
① 2분의 1
② 3분의 1
③ 3분의 2
④ 4분의 3
⑤ 5분의 4

#### [2013-78] 甲은 乙에게 1억원을 빌려주고 이를 담보하기 위해 乙소유의 부동산(시가 3억원)에 가등기를 하였다. 乙이 변제기에 채무를 이행하지 않자 甲은 즉시 담보권을 실행하여 부동산의 소유권을 취득하고자 한다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲은 청산금의 평가액을 乙에게 통지하여야 한다.
② 甲이 乙에게 청산금의 평가액을 통지한 후에도 甲은 이에 관하여 다툴 수 있다.
③ 乙은 甲이 통지한 청산금액에 묵시적으로 동의함으로써 청산금을 확정시킬 수 있다.
④ 甲이 乙에게 담보권 실행통지를 하지 않으면 청산금을 지급하더라도 가등기에 기한 본등기를 청구할 수 없다.
⑤ 乙은 甲이 통지한 청산금액을 다투고 정당하게 평가된 청산금을 지급받을 때까지 부동산의 소유권이전등기 및 인도채무의 이행을 거절할 수 있다.

#### [2013-79] 甲은 乙로부터 1억원을 빌리면서 자신의 X건물(시가 5억원)에 저당권을 설정해 준 다음 丙으로부터 2억원을 빌리면서 X건물을 양도담보로 제공하고 丙명의로 소유권이전등기를 해 주었다. 다음 설명 중 틀린 것은?(다툼이 있으면 판례에 의함)
① 甲이 乙에게 피담보채무를 전부 변제한 경우, 甲은 저당권설정등기의 말소를 청구할 수 있다.
② 丙이 甲에게 청산금을 지급함으로써 X건물의 소유권을 취득하면 丙의 양도담보권은 소멸한다.
③ X건물이 멸실ㆍ훼손되면 그 범위 내에서 丙의 양도담보권과 피담보채권은 소멸한다.
④ 乙의 담보권실행을 위한 경매로 X건물이 丁에게 매각된 경우, 丙의 양도담보권은 소멸한다.
⑤ 만일 선의의 戊가 丙으로부터 X건물의 소유권을 취득하였다면, 甲은 丙명의의 소유권이전등기의 말소를 청구할 수 없다.

#### [2013-80] 甲은 2013년에 친구 乙과 명의신탁약정을 하고 丙소유의 X부동산을 매수하면서 丙에게 부탁하여 乙명의로 소유권이전등기를 하였다. 다음 설명 중 옳은 것은?(다툼이 있으면 판례에 의함)
① 乙이 X부동산의 소유자이다.
② 甲은 명의신탁해지를 원인으로 乙에게 소유권이전등기를 청구할 수 있다.
③ 甲은 부당이득반환을 원인으로 乙에게 소유권이전등기를 청구할 수 있다.
④ 丙은 진정명의회복을 원인으로 乙에게 소유권이전등기를 청구할 수 있다.
⑤ 만약 甲과 乙이 사실혼 관계에 있다면 甲과 乙사이의 명의신탁약정은 유효이다.