= 31회 공인중개사법 기출문제
:author: 정주성
:description: 31회 공인중개사법 기출문제
:keywords: 공인중개사법

==== 1. 내용으로 옳은 것은? [해설]

① 중개보조원은 중개대상물에 관한 확인 설명의무가 있다. +
② 소속공인중개사는 그 소속 개업공인중개사인 법인의 임원이 될 수 없다. +
③ 외국인은 공인중개사가 될 수 없다. +
④ 개업공인중개사가 성실 정확하게 중개대상물의 확인·설명을 하지 않은 경우 과태료 처분사유에 해당한다. +
⑤ 토지이용계획은 주거용 건축물 매매계약의 중개 의뢰를 받은 개업공인중개사가 확인·설명해야 할 사항에 포함되지 않는다.

////
☞ 정답 : ④

==== ☞ 해설
****
① 중개대상물에 관한 확인 설명의무는 개업공인중개사와 소속공인중개사에게만 있다. 중개보조원은 중개대상물에 대한 현장안내 및 일반서무 등 개업공인중개사의 중개업무와 관련된 단순한 업무를 보조하는 일만 할 수 있다. +
② 개업공인중개사인 법인은 대표자를 제외한 임원 ·사원의 3분의 1 이상이 공인중개이어야 한다. 그러므로 그 소속공인중개사는 그 소속 개업공인중개사인 법인의 임원이 될 수 있다. +
③ 공인중개사가 되려는 자는 이 법에서 정한 자격시험에 합격하여야 한다고 명시하고 있다 (법 제4조), 내국인·외국인 여부는 명시하지 않았으므로, 외국인도 시험에 합격하면 공인중개사가 될 수 있다. +
④ 개업공인중개사가 성실·정확하게 중개대상물의 확인·설명을 하지 않은 경우에는 500만원의 과태료 처분사유에 해당한다. +
⑤ 토지이용계획은 임대차의 경우에만 생략할 수 있다고 확인·설명서 작성방법에 명시되어 있다. 즉 토지이용계획은 매매로 인한 소유자에게는 그 제한여부가 매매계약을 체결하는데 동기 및 이유가 될 수 있으므로 확인·설명하여야 할 사항이다. +
****
////

==== 2. 중개사무소의 개설등록에 관한 설명으로 옳은 것은? (단, 다른 법률의 규정은 고려하지 않음)

① 합명회사가 개설등록을 하려면 사원 전원이 실무교육을 받아야 한다. +
② 자본금이 1,000 만원 이상인 『협동조합기본법』상 협동조합은 개설등록을 할 수 있다. +
③ 합명회사가 개설등록을 하려면 대표자는 공인중개사이어야 하며, 대표자를 포함하여 임원 또는 사원의 3분의 1 이상이 공인중개사여야 한다. +
④ 법인 아닌 사단은 개설등록을 할 수 있다. +
⑤ 개설등록을 하려면 소유권에 의하여 사무소의 사용권을 확보하여야 한다.

////
​☞ 정답 : ① +
☞ 키워드 : 중개사무소 개설등록 +

==== ☞ 해설
****
① 중개법인의 개설등록은 상법상의 회사이면 가능하다. 상법상의 회사에는 합자회사, 합명회사, 유한회사, 주식회사가 있다. 법인의 경우에는 대표자, 임원, 사원 전원이 실무교육을 받아야 한다. 참고로 개업공인중개사의 중개보조원은 실무교육이 아닌 직무교육을 받아야 한다. +
② 상법상의 회사 또는 협동조합기본법상 협동조합은 모두 자본금이 5천만원 이상이어야 한다. 이 둘은 업무보증 설정금액에서 차이가 있다. 즉, 상법상의 회사인 법인은 2억원 이상이고, 협동조합(지역농업협동조합)은 1천만원 이상이다. +
③ 법인의 경우 대표자를 ​제외한 임원 또는 사원의 3분의 1 이상이 공인중개사여 야한다. (법 제9조 제3항 및 시행령 제13조 제1항 제2호 다목) 
④ 개설등록을 할 수 있는 자는 공인중개사나 법인이어야 한다. (법 제9조 제3항) 따라서 법인이 아닌 사단은 법인이 아니므로 개설등록을 할 수 없다. +
⑤ 개설등록을 하려면 건축물 대장에 기재된 건물에 중개사무소를 확보해야한다. (시행령 제13조 제1항 제1호 나목). 가설건축물대장은 안된다. 준공검사, 사용승인, 사용검사등을 받은 건물로서 건축물 대장에 기재되기 전의 건물은 포함한다. 그리고 사용권확보는 소유, 전세, 임대차, 사용대차의 방법으로 가능하므로, 꼭 소유권을 확보할 필요는 없다. 
****
////

==== 3. 중개사무소의 개설등록의 결격사유를 모두 고른 것은?

****
ㄱ. 파산선고를 받고 복권되지 아니한 자 +
ㄴ. 피특정후견인 +
ㄷ. 공인중개사 자격이 취소된 후 3년이 지나지 아니한 임원이 있는 법인 +
ㄹ. 개업공인중개사인 법인의 해산으로 중개사무소 개설등록이 취소된 후 3년이 지나지 않은 경우 그 법인의 대표이었던 자
****

① ㄱ +
② ㄱ, ㄷ +
③ ㄴ, ㄷ +
④ ㄴ, ㄹ +
⑤ ㄱ, ㄷ, ㄹ +

////
​☞ 정답 : ②
☞ 키워드 : 개설등록 결격사유

==== ☞ 해설
****
특정후견은 피특정후견인에 대한 후원만을 내용으로 한다. 피특정후견인의 행위능력에 대해서는 어떠한 제한도 없다. 특정 법률행위를 위하여 특정후견인이 선임되고 그에게 대리권 수여가 있더라도 그 법률행위와 관련된 피특정후견인의 행위능력이 제한되는 것이 아니다. 그러므로 피성년후견인아 피한정후견인과 달리 피특정후견인은 정상적인 행위능력이 인정되므로 공인중개사 개설등록의 결격사유에 해당하지 않는다. +

개업공인중개사의 사망이나 개업공인중개사인 법인이 해산한 경우에는 절대적 등록취소 사유이다. 그러나 사망과 해산의 경우에는 위반행위등의 사유로 취소되는 것이 아니라, 사망, 해산으로 권리능력이 상실되어 취소하는 경우이다. 그래서 개인인 개업공인중개사의 사망으로 권리관계등이 종료되지만, 법인의 경우에는 해산되더라도 그에 소속된 대표, 임원, 사원등은 공인중개사에게는 결격사유가 적용되지 않는다. 그래서 법인이 해산된 후에, 그 대표, 임원, 사원등이 요건에 맞게 법인을 설립하거나 요건에 맞게 개업공인중개사 등록을 할 수 있다. +

​ 
**등록 결격사유 법 제10조 제1항**

1. 개설등록의 결격사유로는 미성년자
2. 피성년후견인 또는 피한정후견인
3. 파산선고를 받고 복권되지 아니한 자
4. 금고 이상의 선고를 받고 그 집행이 종료되거나 집행이 면제된 날부터 3년이 경과되지 아니한 자
5. 금고 이상의 형의 집행유예를 받고 그 유예기간 중에 있는 자
6. 자격취소 후 3년이 경과되지 아니한 자
7. 자격정지처분을 받고 자격정지기간 중에 있는 자
8. 이 법 위반으로 등록취소처분을 받고 등록취소 후 3년이 경과되지 아니한 자
9. 업무정지처분을 받고 폐업신고를 한 자로서 업무정지기간이 경과되지 아니한 자
10. 업무정지처분을 받은 개업공인중개사인 법인의 업무정지의 사유가 발생한 당시의 사원 또는 임원이었던 자로서 당해 개업공인중개사에 대한 업무정지기간이 경과되지 아니한 자
11. 공인중개사법을 위반하여 300만원 이상의 벌금형의 선고를 받고 3년이 경과되지 아니한자
12. 법인의 사원 또는 임원 중 위 1~11 중 어느 하나에 해당하는 자가 임원 또는 사원으로 있는 법인

****
////

==== 4. 중개대상에 해당하는 것을 모두 고른 것은 ? (다툼이 있으면 판례에 따름)

****
ㄱ. 『공장 및 광업재단 저당법』에 따른 공장재단 +
ㄴ. 영업용 건물의 영업시설·비품 등 유형물이나 거래처, 신용 등 무형의 재산적 가치 +
ㄷ. 가압류된 토지 +
ㄹ. 토지의 정착물인 미등기 건축물. +
****

① ㄱ ② ㄱ, ㄴ ③ ㄱ, ㄷ, ㄹ ④ ㄴ, ㄷ, ㄹ ⑤ ㄱ, ㄴ, ㄷ, ㄹ. +

////
☞ 정답 : ③
☞ 키워드 : 중개대상물

==== ☞ 해설
****
ㄱ. 공장재단은 시행령에 따른 중개대상물에 해당하고 +
ㄴ. 무형의 재산적 가치는 법에서 정한 대상물의 범위에 해당하지 않는다. +
ㄷ. 가압류된 토지도 거래가 가능하므로, 중개대상물에 해당된다. +
ㄹ. 건축물은 현존하는 건축물이면 등기, 미등기 건물 모두 중개대상물이 되며, 무허가 건축물도 중개대상물이 된다. 현존하지 않는 장래에 건축될 건축물은 중개대상물이 되며 실물이 없기 때문에 입주자로 선정된 지위인 분양권을 중개대상물로 한다. +

**중개대상물의 범위**

1. 토지
2. 건축물 그 밖의 토지의 정착물
3. 입목에 관한 법률에 따른 입목
4. 공장 및 광업재단 저당법에 따른 광업재단 및 공장재단이 중개대상물에 속한다 (법 제3조 및 시행령 제2조)
****

=== ​5. 공인중개사 등에 관한 설명으로 틀린 것은? ::4

① 공인중개사의 자격이 취소된 후 3년이 지나지 아니한 자는 중개보조원이 될 수 없다. +
② 공인중개사는 자기의 공인중개사자격증을 무상으로도 대여해서는 안된다. +
③ 자격정지처분을 받은날부터 6월이 경과한 공인중개사는 법인인 개업공인중개사의 임원이 될 수 있다. +
④ 다른 사람에게 자기의 성명을 사용하여 중개업무를 하게 한 경우에는 자격정지 처분 사유에 해당한다. . +
⑤ 공인중개사가 아닌 자는 공인중개사 또는 이와 유사한 명칭을 사용하지 못한다.​. +

☞ 정답 : ④
☞ 키워드 : 자격취소

==== ☞ 해설
****
① 11가지 결격사유에 해당하는 자는 소속공인중개사나 중개보조원이 될 수 없다고 법 제10조 제2항에 명시하고 있다. 공인중개사의 자격이 취소된 후 3년이 지나지 않은 자는 결격사유에 해당하며 따라서 중개보조원도 될 수 없다. +

② 공인중개사자격증을 양도하거나 대여할 수 없다. (법 제 7조), 양도하거나 대여하면 자격취소사유에 해당한다. (법 제35조). 양도나 대여는 유상이나 무상을 구분하지 않는다. 따라서 무상으로도 대여해서는 안된다. +

③ 자격정지처분은 소속공인중개사를 대상으로 한다. 그 기간도 6월을 경과할 수 없다 (법 제36조). 또한 자격정지처분기간중에 있는 자는 중개법인의 사원이나 임원도 될 수 없는 결격사유에 해당한다(법 제10조 제1항 12호). 따라서 자격정지처분을 받고 6월을 경과하면 결격사유가 해소되어 법인인 개업공인중개사의 임원이 될 수 있다. 
④ 다른 사람에게 자기의 성명을 사용하여 중개업무를 하게 한 경우에는 자격정지 처분 사유가 아니라 자격취소 사유에 해당된다(법 제35조). 또한 자기의 성명을 사용하여 중개업무를 하게 한 경우에는 1년이하 징역 또는 1천만원 이하의 벌금에 처하게 된다(법 제49조). 
⑤ 공인중개사가 아닌 자는 공인중개사 또는 이와 유사한 명칭을 사용하지 못한다(법 제8조). 이를 위반하면 1년 이하의 징역 또는 1천만원 이하의 벌금형에 처하게 된다(법 제49조). +
. +
****
////

==== 6. 분사무소의 설치에 관한 설명으로 옳은 것은?

① 군(郡)에 주된 사무소가 설치된 경우 동일 군(郡)에 분사무소를 둘 수 있다. +
② 개업공인중개사가 분사무소를 설치하기 위해서는 등록관청으로부터 인가를 받아야 한다. +
③ 공인중개사인 개업공인중개사는 분사무소를 설치할 수 없다. +
④ 다른 법률의 규정에 따라 중개업을 할 수 있는 법인의 분사무소에도 공인중개사를 책임자로 두어야 한다. +
⑤ 분사무소의 책임자인 공인중개사는 등록관청이 실시하는 실무교육을 받아야 한다. +

////
☞ 정답 : ③
☞ 키워드 : 분사무소 설치
☞ 해설
① 법인의 경우에는 주된 사무소의 소재지가 속한 시·군·구를 제외한 시·군·구별로 1개소까지만 설치할 수 있다(법 제 13조 제3항, 시행령 제15조 제1항). 따라서 주된 사무소가 설치된 동일군에 분사무소를 설치 할 수 없다. +

② 개업공인중개사는 분사무소를 설치할 수 없다. 그리고 법인의 경우에 분사무소를 설치하기 위해서는 등록관청에 신고를 하면 되고, 인가를 받을 필요는 없다 (법 제13조 제3항). +

③ 공인중개사인 개업공인중개사는 분사무소를 설치할 수 없다는 명시적인 법조항은 없지만, 법 제13조의 해석상 공인중개사인 개업공인중개사는 분사무소를 설치 할 수 없다고 해석함이 타당하다. +

④ 법인인 개업공인중개사의 분사무소에는 공인중개사를 책임자로 두어야 하지만, 다른 법률의 규정에 따라 중개업을 할 수 있는 법인의 분사무소의 경우에는 그러하지 아니하다고 한다. 즉 이 경우에는 공인중개사를 책임자로 두지 않아도 된다 (시행령 제15조 제2항) 
⑤ 실무교육은 시·도지사가 실시한다 (법 제34조 제1항). 등록관청은 실무교육의 실시자가 아니다. . +
. +
////

==== 7. 법인인 개업공인중개사가 겸업할 수 있는 것을 모두 고른 것은 ? (단, 다른 법률의 규정은 고려하지 않음).

****
ㄱ. 주택용지의 분양 대행 +
ㄴ. 주상복합 건물의 분양 및 관리의 대행 +
ㄷ. 부동산의 거래에 관한 상담 및 금융의 알선 +
ㄹ. 국세징수법상 공매대상 동산에 대한 입찰신청의 대리 +
ㅁ. 법인인 개업공인중개사를 대상으로 한 중개업의 경영기법 제공. +
****

① ㄱ, ㄴ +
② ㄴ, ㅁ +
③ ㄷ, ㄹ +
④ ㄱ, ㄴ, ㅁ +
⑤ ㄴ, ㄷ, ㄹ, ㅁ

////
☞ 정답 : ②
☞ 키워드 : 법인인 개업공인중개사의 업무범위
☞ 해설
법인인 개업공인중개사의 업무범위는 다음과 같다. (법 제14조 제1항)
1. 중개업
2. 상업용 건축물 및 주택의 임대관리 등 관리대행
3. 부동산의 이용·개발 및 거래에 관한 상담
4. 개업공인중개사를 대상으로 한 중개업의 경영기법 및 경영정보의 제공
5. 상업용 건축물 및 주택의 분양대행
6. 중개의뢰인의 의뢰에 따른 도배ㆍ이사업체의 소개 등 주거이전에 부수되는 용역의 알선 (시행령 제17조 제2항)
7. 경매 및 공매대상 부동산에 대한 권리분석 및 취득의 알선과 매수신청 또는 입찰의 대리 . +

따라서 주택의 분양대행은 할 수 있으나, 주택용지의 분양대행(ㄱ)은 할 수 없다. 주상복합건물(ㄴ)은 상업용 건축물과 주택 모두에 해당하므로 이에 대한 분양 및 관리대행은 가능하다. 부동산 거래에 관한 상담은 가능하나 금융의 알선(ㄷ)은 허용되지 않는다. 부동산에 관한 경매, 공매에 대한 입찰신청의 대리는 가능하나, 동산(ㄹ)에 대한 입찰신청 대리는 허용되지 않는다. 개업공인중개사를 대상으로 중개업의 경영기법 제공은 가능하며, 그 대상에는 법인 또는 공인중개사인 개업공인중개사를 불문한다. +
. +
. +
////

==== 8. 법인인 개업공인중개사의 중개사무소등록증 원본 또는 사본이 첨부되어야 하는 경우에 해당하지 않는 것은?

① 중개사무소 이전신고 +
② 중개사무소 폐업신고 +
③ 분사무소 설치신고 +
④ 분사무소 폐업신고 +
⑤ 3개월을 초과하는 중개사무소 휴업신고 +

////
☞ 정답 : ③
☞ 키워드 : 휴업·폐업·이전 신고시 중개사무소 등록증 첨부
☞ 해설
중개사무소나 분사무소의 이전신고를 할 경우에는 중개사무소등록증이나 분사무소신고필증을 첨부하여 신고하여야 한다 (법 제20조 및 시행규칙 제11조). 휴업이나 폐업을 할 경우에는 중개사무소 등록증을 첨부하여 신고하여야 한다 (법 제21조 및 시행령 제18조). 따라서 분사무소 설치신고를 할 때에는 등록증을 첨부할 필요가 없다. 그러나 법 제18조에서는 법인의 분사무소의 경우에도 같다고 하면서 휴업·폐업시 등록증을 첨부하는 것으로 해석된다. 그렇다고 법인의 등록증을 첨부하는건 아닐테고, 분사무소 신고필증을 첨부하는 것으로 해석된다. 문제에서 ‘중개사무소의 등록증 원본 또는 사본’의 첨부에 관한 것인데 지문 ④의 분사무소 폐업시에는 신고필증을 첨부하는 것으로 해석된다. 법, 시행령, 시행규칙 어디를 봐도 신고필증 외 중개사무소 등록증 원본 또는 사본을 첨부하라는 것은 없다. 그렇다면 지문 ④도 답이 될 가능성이 있다. +
////

==== 9. 인장등록 등에 관한 설명으로 옳은 것은?
① 중개보조원은 중개업무를 보조하기 위해 인장등록을 하여야 한다. +
② 개업공인중개사가 등록한 인장을 변경한 경우 변경일부터 10일 이내에 그 변경된 인장을 등록관청에 등록하면 된다. +
③ 분사무소에서 사용할 인장은 분사무소 소재지 시장·군수 또는 구청장에게 등록해야 한다. +
④ 분사무소에서 사용할 인장은 「상업등기규칙」에 따라 신고한 법인의 인장이어야 하고,「상업등기규칙」에 따른 인감증명서의 제출로 갈음할 수 없다. +
⑤ 법인의 소속공인중개사가 등록하지 아니한 인장을 사용한 경우, 6개월의 범위 안에서 자격정지 처분을 받을 수 있다. +

////
☞ 정답 : ⑤
☞ 키워드 : 인장등록
☞ 해설
① 중개보조원은 중개업무를 보조하기 위해 인장등록을 할 필요는 없다. 개업공인중개사나 소속공인중개사가 인장등록을 하고, 중개계약서, 거래계약서, 확인설명서등에 날인을 한다 (법 제16조). +

② 개업공인중개사가 등록한 인장을 변경한 경우 변경일부터 10일 이내가 아니고, 7일 이내에 그 변경된 인장을 등록관청에 등록하면 된다 (법 제16조 및 시행규칙 제9조 제2항)
③ 분사무소에서 사용할 인장은 분사무소 소재지 시장·군수 또는 구청장에게 등록하는 것이 아니고, 법인의 주사무소 소재지 등록관청에 등록해야 한다. 참고로 분사무소에 관련한 신고, 등록사항 등은 모두 주사무소 소재지 등록관청에 하여야 한다. 
④ 분사무소가 아니라 주사무소에서 사용할 인장은 「상업등기규칙」에 따라 신고한 법인의 인장이어야 하고,「상업등기규칙」에 따른 인감증명서의 제출로 갈음할 수 있다. 분사무소의 인장은 「상업등기규칙」에 따라 법인의 대표자가 보증하는 인장을 등록할 수 있다 (시행규칙 제9조 제3항, 제4항). +

⑤ 등록하지 아니한 인장을 사용하거나 인장을 등록하지 않는 경우에는 6월 이내의 자격정지 처분을 받을 수 있다 (법 제36조 제1항 제2호). +
////

==== 10. 중개사무소 명칭에 관한 설명으로 옳은 것은?
① 공인중개사인 개업공인중개사는 그 사무소의 명칭에 “공인중개사사무소” 또는 “부동산중개”라는 문자를 사용하여야 한다. +
② 공인중개사가 중개사무소의 개설등록을 하지 않을 경우, 그 사무소에 “공인중개사사무소”라는 명칭을 사용할 수 없지만, “부동산중개”라는 명칭은 사용할 수 있다. +
③ 공인중개사인 개업공인중개사가 관련 법령에 따른 옥외 광고물을 설치하는 경우, 중개사무소등록증에 표기된 개업공인중개사의 성명을 표기할 필요는 없다. +
④ 중개사무소 개설등록을 하지 않은 공인중개사가 “부동산중개”라는 명칭을 사용한 경우, 국토교통부장관은 그 명칭이 사용된 간판등의 철거를 명할 수 있다. +
⑤ 개업공인중개사가 의뢰받은 중개대상물에 대하여 표시·광고를 하려는 경우, 중개사무소의 명칭은 명시하지 않아도 된다. +

////
☞ 정답 : ①
☞ 키워드 : 중개사무소 명칭
☞ 해설
① 공인중개사인 개업공인중개사는 그 사무소의 명칭에 “공인중개사사무소” 또는 “부동산중개”라는 문자를 사용하여야 한다고 법 제 18조 제1항에 명시하고 있다. +

② 공인중개사가 중개사무소의 개설등록을 하지 않을 경우에는 개업공인중개사가 아니다. 개업공인중개사가 아닌 경우에는 그 사무소에 “공인중개사사무소” 또는 “부동산중개”라는 명칭을 사용할 수 없다 (법 제18조 제2항). +

③ 공인중개사인 개업공인중개사가 관련 법령에 따른 옥외 광고물을 설치하는 경우, 중개사무소등록증에 표기된 개업공인중개사의 성명을 표기하여야 한다 (법 제18조 제3항). +

④ 중개사무소 개설등록을 하지 않은 공인중개사가 “부동산중개”라는 명칭을 사용한 경우, 국토교통부장관이 아니라 등록관청이 철거를 명할 수 있다. +

⑤ 개업공인중개사가 의뢰받은 중개대상물에 대하여 표시·광고를 하려는 경우, 중개사무소의 명칭, 소재지, 연락처 및 등록번호, 개업중개사의 성명 등을 명시하여야 한다 (법 제18조의 2 제1항 및 시행령 제17조의 2 제1항). +
. +
. +
////

==== 11. 개업공인중개사가 의뢰받은 중개대상물에 대하여 표시·광고를 하는 경우에 관한 설명으로 옳은 것은?

① 중개보조원이 있는 경우 개업공인중개사의 성명과 함께 중개보조원의 성명을 명시할 수 있다. +
② 중개대상물에 대한 표시·광고를 위하여 대통령령으로 정해진 사항의 구체적인 표시·광고 방법은 국토교통부장관이 정하여 고시한다. +
③ 중개대상물의 내용을 사실과 다르게 거짓으로 표시·광고한 자를 신고한 자는 포상금 지급 대상이다. +
④ 인터넷을 이용하여 표시·광고를 하는 경우 중개사무소에 관한 사항은 명시하지 않아도 된다. +
⑤ 인터넷을 이용한 중개대상물의 표시·광고 모니터링 업무 수탁 기관은 기본계획서에 따라 6개월마다 기본 모니터링 업무를 수행한다. +

////
☞ 정답 : ②
☞ 키워드 : 중개대상물 표시·광고
☞ 해설
① 중개보조원이 있더라도 개업공인중개사의 성명과 중개사무소 명칭, 소재지, 연락처, 등록번호 등만 명시하면 된다 (법 제18조의2 제1항 및 시행령 제17조의 2 제1항). +

② 중개대상물에 대한 표시·광고를 위하여 대통령령으로 정해진 사항의 구체적인 표시·광고 방법은 국토교통부장관이 정하여 고시한다고 시행령 제17조의2 제3항에 명시되어 있다. +

③ 포상금 지급대상은 무등록중개업자, 부정한 방법으로 등록한 자, 등록증을 양도·대혀하거나 양수·대여받은 자, 공인중개사 자격증을 양도·대여하거나 양수·대여 받은자를 신고한 경우에 등록관청이 포상금을 지급할 수 있다 (법제46조 참조). 따라서 중개대상물의 내용을 사실과 다르게 거짓으로 표시·광고한 자는 포상금 지급대상이 아니다. 
④ 인터넷을 이용하여 표시·광고를 하는 경우에도 법 제18조의2 규정을 준수하고 있는지 모이터링 하고 있다. 따라서 인터넷의 경우에도 인터넷 외의 경우와 동일한 방식으로 표시·광고 사항을 준수하여야 한다. 
⑤ 인터넷을 이용한 중개대상물의 표시·광고 모니터링 업무 수탁 기관은 기본계획서에 따라 6개월마다가 아니고 분기별로 기본 모니터링 업무를 수행한다 (시행규칙 제10조의 3 제1항). +
////

==== 12. 개업공인중개사가 중개사무소 안의 보기 쉬운 곳에 게시해야 하는 것은?
① 개업공인중개사의 실무교육 수료확인증 원본
② 소속공인중개사가 있는 경우 소속공인중개사의 실무교육 수료확인증 사본
③ 사업자등록증 원본
④ 소속공인중개사가 있는 경우 소속공인중개사의 공인중개사자격증 사본
⑤ 분사무소의 경우 분사무소설치신고필증 원본. +

////
☞ 정답 : ⑤. +

☞ 키워드 : 중개사무소등록증 등의 게시
☞ 해설
법 제17조 및 시행규칙 제10조에서는 중개사무소등록증 등의 게시에 대해서 명시하고 있다. 게시할 사항은. +

1. 중개사무소 등록증 원본 (분사무소의 경우에는 분사무소설치신고필증 원본)
2. 중개보수ㆍ실비의 요율 및 한도액표
3. 개업공인중개사 및 소속공인중개사가 있는 경우 그의 공인중개사자격증 원본
4. 보증의 설정을 증명할 수 있는 서류
따라서 실무교육 수료확인증이나 사업자등록증은 게시할 사항이 아니다. 그리고 사무소등록증이나 자격증은 사본이 아니라 원본을 게시하여야 한다. 원본 등을 게시하게 함으로써 양도·대여 등을 방지하는 효과가 있어 보인다. +
////

==== 13. 개업공인중개사의 휴업과 폐업 등에 관한 설명으로 틀린 것은?
① 폐업신고 전의 개업공인중개사에 대하여 위반행위를 사유로 행한 업무정지처분의 효과는 폐업일부터 1년간 다시 개설등록을 한 자에게 승계된다. +
② 개업공인중개사가 폐업신고를 한 후 1년 이내에 소속공인중개사로 고용신고되는 경우, 그 소속공인중개사는 실무교육을 받지 않아도 된다. +
③ 손해배상책임의 보장을 위한 공탁금은 개업공인중개사가 폐업한 날부터 3년 이내에는 회수할 수 없다. +
④ 분사무소는 주된 사무소와 별도로 휴업할 수 있다. +
⑤ 중개업의 폐업신고는 수수료 납부사항이 아니다. +


////
☞ 정답 : ①
☞ 키워드 : 휴업과 폐업
☞ 해설
① 폐업신고 전의 개업공인중개사에 대하여 위반행위를 사유로 행한 업무정지처분의 효과는 폐업일부터가 아니고 처분일로부터 1년간 다시 개설등록을 한 자에게 승계된다 (법 제40조 제2항). +

② 개업공인중개사가 폐업신고를 한 후 1년 이내에 소속공인중개사로 고용신고되는 경우, 그 소속공인중개사는 실무교육을 받지 않아도 된다 (법 제34조 제1항 제1호). 즉 실무교육의 유효기간은 1년으로 이해하면 된다. +

③ 손해배상책임의 보장을 위한 공탁금은 개업공인중개사가 폐업한 날부터 3년 이내에는 회수할 수 없다 (법 제30조 제3항)
④ 분사무소는 주된 사무소와 별도로 휴업할 수 있다 (시행령 제18조 제1항). 
⑤ 수수료 납부사항은 1.중개사 시험 응시할 때, 2.자격증 재교부 신청할 때, 3.등록증 재교부 신청할 때, 4.분사무소 설치 신고 할 때, 5.분사무소 설치 신고확인서 재교부 신청할 때이다 (법 제47조). 따라서 중개업의 폐업신고는 수수료 납부사항이 아니다. +
////

==== 14. 법인인 개업공인중개사가 등록관청 관할지역 외의 지역으로 중개사무소 또는 분사무소를 이전하는경우에 관한 설명으로 옳은 것은?

① 중개사무소 이전신고를 받은 등록관청은 그 내용이 적합한 경우, 중개사무소등록증의 변경사항을 기재하여 교부하거나 중개사무소등록증을 재교부하여야 한다. +
② 건축물대장에 기재되지 않은 건물에 중개사무소를 확보한 경우, 건축물대장의 기재가 지연된 사유를 적은 서류는 첨부할 필요가 없다. +
③ 중개사무소 이전신고를 하지 않은 경우 과태료 부과대상이 아니다. +
④ 분사무소 이전신고는 이전한 날부터 10일 이내에 이전할 분사무소의 소재지를 관할하는 등록관청에 하면 된다. +
⑤ 등록관청은 분사무소의 이전신고를 받은 때에는 지체 없이 그 분사무소의 이전 전 및 이전 후의 소재지를 관할하는 시장·군수 또는 구청장에게 이를 통보하여야 한다. +

////
☞ 정답 : ⑤
☞ 키워드 : 사무소 이전
☞ 해설
① 기존 등록관청의 관할지역외로 이전한 경우에는 등록증을 재교부하여야 한다. 다만 관할내로 이전한 경우에는 등록증에 변경사항을 기재하여 교부할 수 있다 (시행규칙 제11조 제2항). +

② 건축물대장에 기재되지 않은 건물에 중개사무소를 확보한 경우, 건축물대장의 기재가 지연된 사유를 적은 서류를 함께 제출해야 한다 (시행규칙 제11조 제1항 제2호). +

③ 중개사무소 이전신고를 하지 않은 경우 100만원 이하의 과태료 부과대상이다 (법 제51조 제3항 제3호). +

④ 분사무소 이전신고는 이전한 날부터 10일 이내에 이전할 분사무소의 소재지를 관할하는 등록관청이 아니라 주된 사무소 소재지 관할 등록관청에 하여야 한다 (시행규칙 제11조 제1항). 분사무소의 경우에는 신고 등에 대해서는 주된 사무소를 기준으로 한다. 
⑤ 등록관청은 분사무소의 이전신고를 받은 때에는 지체 없이 그 분사무소의 이전 전 및 이전 후의 소재지를 관할하는 시장·군수 또는 구청장에게 이를 통보하여야 한다 (시행규칙 제11조 제3항). +
////

==== 15. 개업공인중개사가 거래계약서를 작성하는 경우에 관한 설명으로 틀린 것은? (다툼이 있으면 판례에 따름)

① 개업공인중개사는 중개가 완성된 때에만 거래계약서를 작성·교부하여야 한다. +
② 개업공인중개사는 거래계약서에 서명 및 날인하여야 한다. +
③ 중개대상물 확인·설명서 교부일자는 거래계약서의 필수 기재사항에 해당한다. +
④ 개업공인중개사의 거래계약서 보존기간 (공인전자문서센터에 보관된 경우는 제외함)은 5년이다. +
⑤ 개업공인중개사가 하나의 거래계약에 대하여 서로 다른 둘 이상의 거래계약서를 작성한 경우, 등록관청은 중개사무소의 개설등록을 취소하여야 한다. +


////

☞ 정답 : ⑤
☞ 키워드 : 거래계약서 작성
☞ 해설
① 개업공인중개사는 중개가 완성된 때에만 거래계약서를 작성·교부하여야 한다 (법 제26조 제1항)
② 법 제26조 제2항에서는 법 제25조 제4항을 준용한다고 명시하고 있다. 즉 거래계약서를 작성할때에는 확인·설명서의 작성방법과 같이 개업공인중개사가 서명 및 날인을 하여야 한다. 즉, 거래계약서나 확인·설명서에는 서명과 날인을 같이 하여야 한다. 따라서 서명 또는 날인을 하는 방식으로 서명이나 날인을 하나만 하여서는 안된다. +

③ 거래계약서의 필수개재사항은 시행령 제22조 제1항에 명시하고 있다. 즉
1. 거래당사자의 인적 사항, 2. 물건의 표시, 3. 계약일, 4. 거래금액ㆍ계약금액 및 그 지급일자 등 지급에 관한 사항, 5. 물건의 인도일시, 6. 권리이전의 내용, 7. 계약의 조건이나 기한이 있는 경우에는 그 조건 또는 기한, 8. 중개대상물확인ㆍ설명서 교부일자, 9. 그 밖의 약정내용을 필수사항으로 기재하여야 한다. 따라서 중개대상물 확인·설명서 교부일자는 거래계약서의 필수 기재사항에 해당한다. +

④ 개업공인중개사의 거래계약서 보존기간 (공인전자문서센터에 보관된 경우는 제외함)은 5년이다 (시행령 제22조 제2항)
⑤ 개업공인중개사가 하나의 거래계약에 대하여 서로 다른 둘 이상의 거래계약서를 작성한 경우, 등록관청은 중개사무소의 개설등록을 취소하여야 하는 것이 아니고, 개설등록을 취소할 수 있다 (법 제38조 제2항). 즉 상대적 등록취소사유에 해당한다. +
////

==== 16. 개업공인중개사 甲의 손해배상책임의 보장에 관한 설명으로 틀린 것은? 
① 甲은 업무를 개시하기 전에 손해배상책임을 보장하기 위하여 보증보험 또는 공제에 가입하거나 공탁을 하여야 한다. +
② 甲이 설정한 보증을 다른 보증으로 변경하려는 경우 이미 설정한 보증의 효력이 있는 기간 중에 다른 보증을 설정하여야 한다. +
③ 甲이 보증보험 또는 공제에 가입한 경우 보증기간의 만료로 다시 보증을 설정하려면, 그 보증기간 만료일까지 다시 보증을 설정하여야 한다. +
④ 甲이 손해배상책임을 보장하기 위한 조치를 이행하지 아니하고 업무를 개시한 경우 등록관청은 개설등록을 취소할 수 있다. +
⑤ 甲이 공제금으로 손해배상을 한 때에는 30일 이내에 공제에 다시 가입하여야 한다. +
. +
////
☞ 정답 : ⑤
☞ 키워드 : 손해배상책임 보장
☞ 해설
① 개업공인중개사는 업무를 개시하기 전에 손해배상책임을 보장하기 위하여 보증보험 또는 공제에 가입하거나 공탁을 하여야 한다 (법 제30조 제3항). +

② 이미 설정한 보증을 다른 보증으로 변경하려는 경우 이미 설정한 보증의 효력이 있는 기간 중에 다른 보증을 설정하여야 한다 (시행령 제25조 제1항). +

③ 보증보험 또는 공제에 가입한 경우 보증기간의 만료로 다시 보증을 설정하려면, 그 보증기간 만료일까지 다시 보증을 설정하여야 한다 (시행령 제25조 제2항). +

④ 손해배상책임을 보장하기 위한 조치를 이행하지 아니하고 업무를 개시한 경우 등록관청은 개설등록을 취소할 수 있다 (법 제38조 제2항 8호). +

⑤ 공제금으로 손해배상을 한 때에는 30일 이내가 아니라 15일 이내에 공제에 다시 가입하여야 한다 (시행령 제26조 제2항). +
////

==== 17. 공인중개사인 개업공인중개사 甲의 소속공인중개사 乙의 중개행위로중개가 완성되었다. 이에 관한 설명으로 틀린 것은? 

① 乙의 업무상 행위는 甲의 행위로 본다. +
② 중개대상물 확인·설명서에는 甲과 乙이 함께 서명 및 날인하여야 한다. +
③ 乙은 甲의 위임을 받아 부동산거래계약 신고서의 제출을 대행할 수 있다. +
④ 乙의 중개행위가 금지행위에 해당하여 乙이 징역형의 선고를 받았다는 이유로 甲도 해당 조(條)에 규정된 징역형을 선고받는다. +
⑤ 甲은 거래당사자에게 손해배상책임의 보장에 관한 사항을 설명하고 관계 증서의 사본을 교부하거나 관계 증서에 관한 전자문서를 제공하여야 한다. +

////

☞ 정답 : ④
☞ 키워드 : 소속공인중개사의 중개행위
☞ 해설
① 소속공인중개사의 업무상 행위는 그를 고용한 개업공개사의 행위로 본다 (법 제15조 제2항)
② 중개대상물 확인·설명서에는 개업공인중개사와 해당 중개행위를 한 소속공인중개사가 함께 서명 및 날인하여야 한다 (법 제25조 제4항). +

③ 소속공인중개사는 개업공인중개사의 위임을 받아 부동산거래계약 신고서의 제출을 대행할 수 있다 (부동산거래신고등에관한법률 시행규칙 제5조 제2항). +

④ 소속공인중개사의 중개행위가 금지행위에 해당하여 소속공인중개사가 징역형의 선고를 받았다는 이유로 소속공인중개사는 해당 조(條)에 규정된 벌금형을 선고받는다 (법 제50조). +

⑤ 개업공인중개사는 거래당사자에게 손해배상책임의 보장에 관한 사항을 설명하고 관계 증서의 사본을 교부하거나 관계 증서에 관한 전자문서를 제공하여야 한다 (법 제30조 제5항). 비록 소속공인중개사의 중개행위라고 할지라도 소속공인중개사가 손해배상책임 관련 서류를 제공할 수 없다. 손해배상책임 관련한 증서 등의 교부는 개업공인중개사만 할 수 있다. +
////

==== 18. 乙이 개업인중개사 甲에게 중개를 의뢰하여 거래계약이 체결된 경우 중개보수에 관한 설명으로 틀린 것은? (다툼이 있으면 판례에 따름) 

① 甲의 고의와 과실없이 乙의 사정으로 거래계약이 해제된 경우라도 甲은 중개보수를 받을 수 있다. +
② 주택의 중개보수는 국토교통부령으로 정하는 범위 안에서 시·도의 조례로 정하고, 주택 외의 중개대상물의 중개보수는 국토교통부령으로 정한다. +
③ 甲이 중개보수 산정에 관한 지방자치단체의 조례를 잘못 해석하여 법정 한도를 초과한 중개보수를 받은 경우 공인중개사법 제33조의 금지행위에 해당하지 않는다. +
④ 법정한도를 초과하는 甲과 乙의 중개보수 약정은 그 한도를 초과하는 범위내에서 무효이다. +
⑤ 중개보수의 지급시기는 甲과 乙의 약정이 없을 때에는 중개대상물의 거래대금 지급이 완료된 날이다.

////

☞ 정답 : ③
☞ 키워드 : 중개보수
☞ 해설
① 개업공인중개사의 고의와 과실없이 중개의뢰인의 사정으로 거래계약이 해제된 경우에는 중개보수를 받을 수 있다 (법 제32조 제1항). +

② 주택의 중개보수는 국토교통부령으로 정하는 범위 안에서 시·도의 조례로 정하고, 주택 외의 중개대상물의 중개보수는 국토교통부령으로 정한다 (법 제32조 제4항). +

③ 개업공인중개사가 중개보수 산정에 관한 지방자치단체의 조례를 잘못 해석하여 법정 한도를 초과한 중개보수를 받은 경우 공인중개사법 제33조의 금지행위에 해당한다. 법에서는 어떠한 명목으로도(조례를 잘못 해석하는 것도 포함) 초과하여 받은 경우에는 동법의 적용을 받는 것으로 규정하고 있다. +

④ 법정한도를 초과하는 중개보수 약정은 그 한도를 초과하는 범위내에서 무효이다 (판례 2005다32159)
⑤ 중개보수의 지급시기는 약정이 없을 때에는 중개대상물의 거래대금 지급이 완료된 날이다 (시행령 27조의 2). +
////

==== 19. 거래정보사업자의 지정취소 사유에 해당하는 것을 모두 고른 것은? . +

****
ㄱ. 부동산거래정보망의 이용 및 정보제공방법 등에 관한 운영규정을 변경하고도 국토교통부장관의 승인을 받지 않고 부동산거래정보망을 운영한 경우 +
ㄴ. 개업공인중개사로부터 공개를 의뢰 받지 아니한 중개대상물 정보를 부동산거래정보망에 공개한 경우 +
ㄷ. 정당한 사유없이 지정받은 날부터 6개월 이내에 부동산거래정보망을 설치하지 아니한 경우 +
ㄹ. 개인인 거래정보사업자가 사망한 경우 +
ㅁ. 부동산거래정보망의 이용 및 정보제공방법 등에 관한 운영규정을 위반하여 부동산거래정보망을 운영한 경우. +
****

① ㄱ, ㄴ ② ㄷ, ㄹ
③ ㄱ, ㄴ, ㅁ ④ ㄱ, ㄴ, ㄹ, ㅁ
⑤ ㄱ, ㄴ, ㄷ, ㄹ, ㅁ'

////
☞ 정답 : ④
☞ 키워드 : 거래정보사업자 지정취소
☞ 해설
거래정보 사업자 지정취소 사유 (법 제24조 제5항)
1. 거짓이나 그 밖의 부정한 방법으로 지정을 받은 경우
2. 제3항의 규정을 위반하여 운영규정의 승인 또는 변경승인을 받지 아니하거나 운영규정을 위반하여 부동산거래정보망을 운영한 경우 (ㄱ,ㅁ)
3. 제4항의 규정(거래정보사업자는 개업공인중개사로부터 공개를 의뢰받은 중개대상물의 정보에 한정하여 이를 부동산거래정보망에 공개하여야 하며, 의뢰받은 내용과 다르게 정보를 공개하거나 어떠한 방법으로든지 개업공인중개사에 따라 정보가 차별적으로 공개되도록 하여서는 아니된다)을 위반하여 정보를 공개한 경우 (ㄴ)
4. 정당한 사유 없이 지정받은 날부터 1년 이내에 부동산거래정보망을 설치ㆍ운영하지 아니한 경우
5. 개인인 거래정보사업자의 사망 또는 법인인 거래정보사업자의 해산 그 밖의 사유로 부동산거래정보망의 계속적인 운영이 불가능한 경우 (ㄹ)
따라서 ㄷ. 정당한 사유없이 지정받은 날부터 6개월이 아니라 1년 이내에 부동산거래정보망을 설치하지 아니한 경우가 취소사유에 해당된다. . +
////

==== 20. 개업공인중개사등의 금지행위에 해당하지 않는 것은?

① 무등록 중개업을 영위하는 자인 사실을 알면서 그를 통하여 중개를 의뢰받는 행위 +
② 부동산의 매매를 중개한 개업공인중개사가 당해 부동산을 다른 개업공인중개사의 중개를 통하여 임차한 행위 +
③ 자기의 중개의뢰인과 직접 거래를 하는 행위 +
④ 제3자에게 부당한 이익을 얻게 할 목적으로 거짓으로 거래가 완료된 것처럼 꾸미는 등 중개대상물의 시세에 부당한 영향을 줄 우려가 있는 행위 +
⑤ 단체를 구성하여 단체 구성원 이외의 자와 공동중개를 제한하는 행위. +

////

☞ 정답 : ②
☞ 키워드 : 금지행위
☞ 해설
개업공인중개사등의 금지행위 (법 제33조 제1항)
1. 중개대상물의 매매를 업으로 하는 행위
2. 중개사무소의 개설등록을 하지 아니하고 중개업을 영위하는 자인 사실을 알면서 그를 통하여 중개를 의뢰받거나 그에게 자기의 명의를 이용하게 하는 행위 (①)
3. 사례ㆍ증여 그 밖의 어떠한 명목으로도 보수 또는 실비를 초과하여 금품을 받는 행위
4. 해당 중개대상물의 거래상의 중요사항에 관하여 거짓된 언행 그 밖의 방법으로 중개의뢰인의 판단을 그르치게 하는 행위
5. 양도ㆍ알선 등이 금지된 부동산의 분양ㆍ임대 등과 관련 있는 증서 등의 매매ㆍ교환 등을 중개하거나 그 매매를 업으로 하는 행위
6. 중개의뢰인과 직접 거래를 하거나 거래당사자 쌍방을 대리하는 행위 (③)
7. 탈세 등 관계 법령을 위반할 목적으로 소유권보존등기 또는 이전등기를 하지 아니한 부동산이나 관계 법령의 규정에 의하여 전매 등 권리의 변동이 제한된 부동산의 매매를 중개하는 등 부동산투기를 조장하는 행위
8. 부당한 이익을 얻거나 제3자에게 부당한 이익을 얻게 할 목적으로 거짓으로 거래가 완료된 것처럼 꾸미는 등 중개대상물의 시세에 부당한 영향을 주거나 줄 우려가 있는 행위 (④)
9. 단체를 구성하여 특정 중개대상물에 대하여 중개를 제한하거나 단체 구성원 이외의 자와 공동중개를 제한하는 행위 (⑤)
따라서 ②의 개업공인중개사가 의뢰인과 직접거래가 아닌, 다른 개업공인중개사의 중개로 임차를 하는 행위는 금지행위에 해당되지 않는다. +
////

==== 21. 개업공인중개사등의 교육에 관한 설명으로 옳은 것은? (단, 다른 법률의 규정은 고려하지 않음)

① 중개사무소 개설등록을 신청하려는 법인의 공인중개사가 아닌 사원은 실무교육 대상이 아니다. +
② 개업공인중개사가 되려느 자의 실무교육시간은 26시간 이상 32시간 이하이다. +
③ 중개보조원이 받는 실무교육에는 부동산 중개 관련 법·제도의 변경사항이 포함된다. +
④ 국토부장관, 시·도지사, 등록관청은 개업공인중개사등에 대한 부동산거래사고 예방 등의 교육을 위하여 교육 관련 연구에 필요한 비용을 지원할 수 있다. +
⑤ 소속공인중개사가는 2년마다 국토교통부장관이 실시하는 연수교육을 받아야 한다. +

////

☞ 정답 : ④
☞ 키워드 : 실무교육
☞ 해설
① 법인의 공인중개사는 임원, 사원 모두 실무교육을 받아야 한다 (법 제34조 제1항)
② 실무교육시간은 28시간 이상 32시간 이하이다 (시행령 제28조 제1항 2호)
③ 중개보조원은 실무교육이 아니라 직무교육을 받으며, 교육내용은 중개보조원의 직무수행에 필요한 직업윤리 등이다 (시행령 제28조 제2항). +

④ 국토부장관, 시·도지사, 등록관청은 개업공인중개사등에 대한 부동산거래사고 예방 등의 교육을 위하여 교육 관련 연구에 필요한 비용을 지원할 수 있다 (법 제34조의2 제1항). +

⑤ 소속공인중개사가는 2년마다 국토교통부장관이 아니라 시·도지사가 실시하는 연수교육을 받아야 한다 (법 제34조 제4항). +
. +
. +
////

==== 22. 부동산거래정보망을 설치·운영할 자로 지정받기 위한 요건의 일부이다. ( )안에 들어갈 내용으로 옳은 것은?

****
* 부동산거래정보망의 가입·이용신청을 한 (ㄱ)의 수가 500명 이상이고 (ㄴ)개 이상의 특별시·광역시·도 및 특별자치도에서 각각 (ㄷ)인 이상의 ( ㄱ)가 가입·이용신청을 하였을 것 +
* 정보처리기사 1명 이상을 확보할 것
* 공인중개사 (ㄹ)명 이상을 확보할 것. +
****

① ㄱ : 공인중개사 ㄴ : 2, ㄷ : 20, ㄹ : 1 +
② ㄱ : 공인중개사 ㄴ : 3, ㄷ : 20, ㄹ : 3 +
③ ㄱ : 개업공인중개사 ㄴ : 2, ㄷ : 20, ㄹ : 3 +
④ ㄱ : 개업공인중개사 ㄴ : 2, ㄷ : 30, ㄹ : 1 +
⑤ ㄱ : 개업공인중개사 ㄴ : 3, ㄷ : 30, ㄹ : 3 +

////
☞ 정답 : ④
☞ 키워드 : 부동산거래정보망
☞ 해설
부동산거래정보망 지정 요건 (시행령 제15조 제2항)
1. 그 부동산거래정보망의 가입ㆍ이용신청을 한 개업공인중개사의 수가 5백명 이상이고 2개 이상의 특별시ㆍ광역시ㆍ도 및 특별자치도(이하 "시ㆍ도"라 한다)에서 각각 30인 이상의 개업공인중개사가 가입ㆍ이용신청을 하였을 것
2. 정보처리기사 1명 이상을 확보할 것
3. 공인중개사 1명 이상을 확보할 것
4. 부동산거래정보망의 가입자가 이용하는데 지장이 없는 정도로서 국토교통부장관이 정하는 용량 및 성능을 갖춘 컴퓨터설비를 확보할 것. +

////

==== 23. 과태료의 부과대상자와 부과기관이 바르게 연결된 것을 모두 고른 것은?
****
ㄱ. 부동산거래정보망의 이용 및 정보제공방법 등에 관한 운영규정 내용을 위반하여 부동산 거래정보망을 운영한 거래정보사업자 - 국토교통부장관 +
ㄴ. 공인중개사법령에 따른 보고의무를 위반하여 보고를 하지 아니한 거래정보업자 - 국토교통부장관 +
ㄷ. 중개사무소등록증을 게시하지 아니한 개업공인중개사 - 등록관청 +
ㄹ. 공인중개사 자격이 취소된 자로 공인중개사 자격증을 반납하지 아니한 자 - 등록관청 +
ㅁ. 중개사무소 개설등록이 취소된 자로 중개사무소등록증을 반납하지 아니한 자 - 시·도지사. +
****

① ㄱ, ㄷ +
② ㄱ, ㄴ, ㄷ +
③ ㄴ, ㄹ, ㅁ +
④ ㄱ, ㄴ, ㄷ, ㄹ +
⑤ ㄱ, ㄴ, ㄷ, ㄹ, ㅁ

////
☞ 정답 : ②
☞ 키워드 : 과태료 부과기관
☞ 해설
ㄹ. 자격증 관련한 과태료는 자격증을 발급해준 시·도지사가 부과한다 (법 제51조 제5항 2호)
ㅁ. 중개사무소등록증 관련한 과태료는 등록증을 발급해준 등록관청이 부과한다 (법 제51조 제5항 4호). +
////

==== 24. 공인중개사의 자격 취소사유와 소속공인중개사의 자격 정지사유에 관한 구분으로 옳은 것을 모두 고른 것은?

****
ㄱ. 다른 사람에게 자기의 성명을 사용하여 중개업무를 하게 한 경우 - 취소사유
ㄴ. 공인중개사법을 위반하여 징역형의 집행유예를 받은 경우 - 취소사유
ㄷ. 거래계약서를 작성할 때 거래금액 등 거래내용을 거짓으로 기재한 경우 - 정지사유
ㄹ. 중개대상물의 매매를 업으로 하는 경우 - 정지사유. +
****

① ㄱ +
② ㄱ, ㄹ +
③ ㄷ, ㄹ +
④ ㄱ, ㄴ, ㄷ +
⑤ ㄱ, ㄴ, ㄷ, ㄹ

////
☞ 정답 : ⑤
☞ 키워드 : 자격취소 및 자격정지사유
☞ 해설
공인중개사의 자격취소 사유 (법 제35조 제1항)
1. 부정한 방법으로 공인중개사의 자격을 취득한 경우
2. 제7조제1항의 규정을 위반하여 다른 사람에게 자기의 성명을 사용하여 중개업무를 하게 하거나 공인중개사자격증을 양도 또는 대여한 경우 (ㄱ)
3. 제36조에 따른 자격정지처분을 받고 그 자격정지기간 중에 중개업무를 행한 경우(다른 개업공인중개사의 소속공인중개사ㆍ중개보조원 또는 법인인 개업공인중개사의 사원ㆍ임원이 되는 경우를 포함한다)
4. 이 법을 위반하여 징역형의 선고를 받은 경우 (ㄴ : 징역형의 집행유예도 징역형의 선고에 해당한다) . +

소속공인중개사 자격정지사유 (법 제36조 제1항)
1. 제12조제2항의 규정을 위반하여 둘 이상의 중개사무소에 소속된 경우
2. 제16조의 규정을 위반하여 인장등록을 하지 아니하거나 등록하지 아니한 인장을 사용한 경우
3. 제25조제1항의 규정을 위반하여 성실ㆍ정확하게 중개대상물의 확인ㆍ설명을 하지 아니하거나 설명의 근거자료를 제시하지 아니한 경우
4. 제25조제4항의 규정을 위반하여 중개대상물확인ㆍ설명서에 서명 및 날인을 하지 아니한 경우
5. 제26조제2항의 규정을 위반하여 거래계약서에 서명 및 날인을 하지 아니한 경우
6. 제26조제3항의 규정을 위반하여 거래계약서에 거래금액 등 거래내용을 거짓으로 기재하거나 서로 다른 둘 이상의 거래계약서를 작성한 경우 (ㄷ)
7. 제33조제1항 각 호에 규정된 금지행위를 한 경우 (ㄹ : 금지행위에는 중개대상물의 매매를 업으로 하는 경우가 포함된다). +
////

==== 25. 벌금부과기준에 해당하는 자를 모두 고른 것은? . +

****
ㄱ. 중개사무소 개설등록을 하지 아니하고 중개업을 한 공인중개사 +
ㄴ. 거짓으로 중개사무소의 개설등록을 한 자 +
ㄷ. 등록관청의 관할 구역 안에 두 개의 중개사무소를 개설등록한 개업공인중개사 +
ㄹ. 임시 중개시설물을 설치한 개업공인중개사 +
ㅁ. 중개대상물이 존재하지 않아서 거래할 수 없는 중개대상물을 광고한 개업공인중개사. +
****

① ㄱ + 
② ㄱ, ㄴ +
③ ㄴ, ㄷ, ㅁ + 
④ ㄱ, ㄴ, ㄷ, ㄹ +
⑤ ㄱ, ㄴ, ㄷ, ㄹ, ㅁ

////
☞ 정답 : ④
☞ 키워드 : 벌금부과기준
☞ 해설
ㄱ. 중개사무소 개설등록을 하지 아니하고 중개업을 한 공인중개사 – 3년이하 또는 3천만원 이하 (법 제48조)
ㄴ. 거짓으로 중개사무소의 개설등록을 한 자 – 3년이하 또는 3천만원 이하 (법 제48조)
ㄷ. 등록관청의 관할 구역 안에 두 개의 중개사무소를 개설등록한 개업공인중개사 – 1년이하 또는 1천만원 이하(법 제49조)
ㄹ. 임시 중개시설물을 설치한 개업공인중개사 – 1년이하 또는 1천만원 이하 (법 제49조)
ㅁ. 중개대상물이 존재하지 않아서 거래할 수 없는 중개대상물을 광고한 개업공인중개사 – 이는 벌금부과대상이 아니라 500만원 이하 과태료 부과대상이다 (법 제51조 제2항 1호). +
////

==== 26. 부동산 거래신고 등에 관한 법령상 이행강제금에 관한 설명으로 옳은 것은? 

① 이행명령은 구두 또는 문서로 하며 이행기간은 3개월 이내로 정하여야 한다. +
② 토지거래계약허가를 받아 토지를 취득한 자가 당초의 목적대로 이용하지 아니하고 방치하여 이행명령을 받고도 정하여진 기간에 이를 이행하지 아니한 경우, 시장·군수 또는 구청장은 토지 취득가액의 100분의 10에 상당하는 금액의 이행강제금을 부과한다. +
③ 이행강제금 부과처분에 불복하는 경우 이의를 제기할 수 있으나, 그에 관한 명문의 규정을 두고 있지 않다. +
④ 이행명령을 받은 자가 그 명령을 이행하는 경우 새로운 이행강제금의 부과를 즉시 중지하며, 명령을 이행하기 전에 부과된 이행강제금도 징수할 수 있다. +
⑤ 최초의 이행명령이 있었던 날을 기준으로 1년에 두 번씩 그 이행명령이 이행될 때까지 반복하여 이행강제금을 부과·징수할 수 있다. +

////

☞ 정답 : ②
☞ 키워드 : 이행강제금
☞ 해설
① 이행명령은 문서로 하여야 하며, 이행기간은 3개월 이내로 정하여야 한다 (시행령 제17조 제1항). 따라서 이행명령은 구두로 할 수 없다. +

② 토지거래계약허가를 받아 토지를 취득한 자가 당초의 목적대로 이용하지 아니하고 방치하여 이행명령을 받고도 정하여진 기간에 이를 이행하지 아니한 경우, 시장·군수 또는 구청장은 토지 취득가액의 100분의 10에 상당하는 금액의 이행강제금을 부과한다 (시행령 제17조 제3항 1호). +

③ 이행강제금 부과처분에 불복하는 경우 시장·군수 또는 구청장에게 이의를 제기할 수 있다 (법 제18조 제6항). 따라서 불복에 대한 명문의 근거 규정이 있다. +

④ 이행명령을 받은 자가 그 명령을 이행하는 경우 새로운 이행강제금의 부과를 즉시 중지하며, 명령을 이행하기 전에 이미 부과된 이행강제금은 징수하여야 한다 (법 제18조 제5항). 따라서 이행하기 전에 이미 부과된 이행강제금은 징수할 수 없는게 아니라, 징수하여야 한다. +

⑤ 최초의 이행명령이 있었던 날을 기준으로 1년에 한 번씩 그 이행명령이 이행될 때까지 반복하여 이행강제금을 부과·징수할 수 있다 (법 제18조 제3항). +
////

==== 27. 부동산 거래신고 등에 관한 법령상 외국인등의 부동산 취득등에 관한 설명으로 옳은 것을 모두 고른 것은? . +

****
ㄱ. 국제연합도 외국인등에 포함된다. +
ㄴ. 외국인등이 대한민국 안의 부동산에 대한 매매계약을 체결하였을 때에는 계약체결일부터 60일 이내에 신고관청에 신고하여야 한다. +
ㄷ. 외국인이 상속으로 대한민국 안의 부동산을 취득한 때에는 부동산을 취득한 날부터 1년 이내에 신고관청에 신고하여야 한다. +
ㄹ. 외국인이 「수도법」에 따른 상수원보호구역에 있는 토지를 취득하려는 경우 토지취득계약을 체결하기 전에 신고관청으로부터 토지취득의 허가를 받아야 한다. +
****

① ㄱ +
② ㄱ, ㄹ +
③ ㄴ, ㄷ +
④ ㄱ, ㄴ, ㄹ +
⑤ ㄱ, ㄴ, ㄷ, ㄹ. +

////
☞ 정답 : ①
☞ 키워드 : 외국인등의 부동산취득
☞ 해설
ㄱ. 국제연합도 외국인등에 포함된다 (시행령 제2조)
ㄴ. 외국인등이 대한민국 안의 부동산등에 대한 취득계약을 체결하였을 때에는 계약체결일부터 60일 이내에 신고관청에 신고하여야 한다 (법 제8조 제1항). 단, 매매계약등은 제외한다. +

ㄷ. 외국인이 상속으로 대한민국 안의 부동산을 취득한 때에는 부동산을 취득한 날부터 1년이 아니라 6개월 이내에 신고관청에 신고하여야 한다 (법 제8조 제2항). +

ㄹ. 외국인의 토지거래허가대상은 「군사기지 및 군사시설 보호법」에 따른 군사기지 및 군사시설 보호구역, 「문화재보호법」에 따른 지정문화재와 이를 위한 보호물 또는 보호구역, 「자연환경보전법」에 따른 생태ㆍ경관보전지역, 「야생생물 보호 및 관리에 관한 법률」에 따른 야생생물 특별보호구역이다 (법 제9조 제1항). 따라서 「수도법」에 따른 상수원보호구역은 허가대상이 아니다. +
////

==== 28. 부동산 거래신고 등에 관한 법령상 토지거래허가구역에 관한 설명으로 옳은 것은? 

① 국토교통부장관은 토지의 투기적인 거래가 성행하는 지역에 대해서는 7년의 기간을 정하여 토지거래계약에 관한 허가구역을 지정할 수 있다. +
② 시·도지사가 토지거래허가구역을 지정하려면 시·도도시계획위원회의 심의를 거쳐 인접 시·도지사의 의견을 들어야 한다. +
③ 시·도지사가 토지거래허가구역을 지정할 때에는 이를 공고하고 그 공고내용을 국토교통부장관, 시장·군수 또는 구청장에게 통지하여야 한다. +
④ 허가구역의 지정은 허가구역의 지정을 공고한 날부터 3일 후에 효력이 발생한다. +
⑤ 「국토의 계획 및 이용에 관한 법률」에 따른 도시지역중 주거지역의 경우 600제곱미터 이하의 토지에 대해서는 토지거래계약허가가 면제된다. +

////

☞ 정답 : ③
☞ 키워드 : 토지거래허가구역
☞ 해설
① 국토교통부장관은 토지의 투기적인 거래가 성행하는 지역에 대해서는 7년이 아니라 5년의 기간을 정하여 토지거래계약에 관한 허가구역을 지정할 수 있다 (법 제10조 제1항). +

② 시·도지사가 토지거래허가구역을 지정하려면 시·도도시계획위원회의 심의를 거쳐야 하고(법 제10조 제2항), 인접 시·도지사의 의견을 들을 필요는 없다. 다만, 지정기간이 끝나는 허가구역을 계속하여 지정하려면 시장ㆍ군수 또는 구청장의 의견을 들어야 한다(법 제10조 제2항 단서). +

③ 법 제10조 제3항 내용임. +

④ 허가구역의 지정은 허가구역의 지정을 공고한 날부터 3일이 아니라 5일 후에 효력이 발생한다 (법 제10조 제5항). +

⑤ 「국토의 계획 및 이용에 관한 법률」에 따른 도시지역중 주거지역의 경우 600제곱미터가 아니라 180제곱미터 이하의 토지에 대해서는 토지거래계약허가가 면제된다(시행령 제9조 제1항). +
////

==== 29. 공인중개사인 개업공인중개사 甲의 중개사무소 폐업 및 재등록에 관한 설명으로 옳은 것은? 

① 甲이 중개사무소를 폐업하고자 하는 경우, 국토교통부장관에게 미리 신고하여야 한다. +
② 甲이 폐업 사실을 신고하고 중개사무소 간판을 철거하지 아니한 경우, 과태료 부과처분을 받을 수 있다. +
③ 甲이 공인중개사법령 위반으로 2019.2.8. 1월의 업무정지처분을 받았으나 2019.7.1. 폐업신고를 하였다가 2019.12.11. 다시 중개사무소 개설등록을 한 경우, 종전의 업무정지처분의 효과는 승계되지 않고 소멸한다. +
④ 甲이 공인중개사법령 위반으로 2019.1.8. 1월의 업무정지처분에 해당하는 행위를 하였으나 2019.3.5. 폐업신고를 하였다가 2019.12.5. 다시 중개사무소 개설등록을 한 경우, 종전의 위반행위에 대하여 1월의 업무정지처분을 받을 수 있다. +
⑤ 甲이 공인중개사법령 위반으로 2018.2.5. 등록취소처분에 해당하는 행위를 하였으나 2018.3.6. 폐업신고를 하였다가 2020.10.16. 다시 중개사무소 개설등록을 한 경우, 그에게 종전의 위반행위에 대한 등록취소처분을 할 수 없다. +
////

☞ 정답 : ④
☞ 키워드 : 중개사무소 폐업 및 재등록
☞ 해설
① 중개사무소를 폐업하고자 하는 경우, 국토교통부장관이 아니라 등록관청에 미리 신고하여야 한다 (법 제21조 제1항). +

② 폐업 사실을 신고하고 중개사무소 간판을 철거하지 아니한 경우, 등록관청은 과태료 부과처분을 하는게 아니라 「행정대집행법」에 따라 대집행을 할 수 있다 (법 제21조 제2항). +

③ 폐업신고후 다시 개설등록을 한 경우에는 폐업전의 지위를 승계하고 (법 제40조 제1항), 폐업신고전의 행정처분의 효과는 처분일로부터 1년간 개설등록을 한 경우에 승계된다 (법 제40조 제2항). 따라서 甲이 공인중개사법령 위반으로 2019.2.8. 1월의 업무정지처분을 받았고 2019.7.1. 폐업신고를 하였다가 2019.12.11. 다시 중개사무소 개설등록을 한 경우에는 처분일로부터 1년이 경과되지 않았으므로, 종전의 업무정지처분의 효과는 승계된다. +

④ 폐업 전의 위반행위로 인하여 재등록한 경우에 행정처분을 할 수 있다. 업무정지를 할 경우에는 폐업기간이 1년 이내이어야 한다 (법 제40조 제3항). 따라서 甲의 폐업기간이 1년 이내이므로 종전의 위반행위에 대하여 1월의 업무정지처분을 받을 수 있다. +

⑤ 폐업 전의 위반행위로 인하여 재등록한 경우에 행정처분을 할 수 있다. 등록취소를 할 경우에는 폐업기간이 3년 이내이어야 한다 (법 제40조 제3항). 따라서 甲의 폐업기간이 3년 이내이므로 종전의 위반행위에 대하여 등록취소처분을 할 수 있다. +
////

==== 30. 개업공인중개사 甲은 소속공인중개사 乙과 중개보조원 丙을 고용하고자 한다. 이에 관한 설명으로 옳은 것을 모두 고른 것은? . +

****
ㄱ. 丙은 외국인이어도 된다. +
ㄴ. 乙에 대한 고용신고를 받은 등록관청은 乙의 직무교육 수료 여부를 확인하여야 한다. +
ㄷ. 甲은 乙의 업무개시 후 10일 이내에 등록관청에 고용신고를 하여야 한다. +
****

① ㄱ ② ㄱ, ㄴ +
③ ㄱ, ㄷ ④ ㄴ, ㄷ +
⑤ ㄱ, ㄴ, ㄷ. +

////
☞ 정답 : ①
☞ 키워드 : 중개보조원
☞ 해설
ㄱ. 중개보조원은 내외국인을 불문한다. +

ㄴ. 소속공인중개사는 직무교육이 아니라, 실무교육을 받아야 한다. (법 제34조 제2항)
ㄷ. 소속공인중개사에 대한 고용신고는 업무개시전에 하여야 한다. (시행령 제8조 제1항). +
////

==== 31. 개업공인중개사 甲의 중개로 乙은 丙소유의 서울 특별시 소재 X상가건물에 대하여 보증금 10억원에 1년기간으로 丙과 임대차계약을 체결하였다. 乙은 X건물을 인도받아 2020.3.10. 사업자등록을 신청하였으며 2020.3.13. 임대차계약서상의 확정일자를 받았다. 이 사례에서 상가건물 임대차보호법령의 적용에 관한 甲의 설명으로 틀린 것은? 

① 乙은 2020.3.11. 대항력을 취득한다. +
② 乙은 2020.3.13. 보증금에 대한 우선변제권을 취득한다. +
③ 丙은 乙이 임대차기간 만료되기 6개월 전부터 1개월 전까지 사이에 계약갱신을 요구할 경우, 정당한 사유없이 거절하지 못한다. +
④ 乙의 계약갱신요구권은 최초의 임대차기간을 포함한 전체 임대차기간이 10년을 초과하지 아니하는 범위에서만 행사할 수 있다. +
⑤ 乙의 계약갱신요구권에 의하여 갱신되는 임대차는 전 임대차와 동일한 조건으로 다시 계약된 것으로 본다. +

////
☞ 정답 : ②
☞ 키워드 : 상가건물 임대차보호법, 대항력
☞ 해설
① 대항력은 건물의 인도와 사업자등록 신청 다음날에 생기므로 (상가건물임대차보호법 제3조 제1항), 인도와 사업자등록 신청 다음날인 2020.3.11.에 대항력이 생긴다. +

② 서울시에서 우선변제를 받으려면 보증금이 6억5천만원 이하여야 한다.(시행령 제6조). 따라서 사례의 보증금은 10억원이므로 乙은 우선변제권이 없다. +

③ 丙은 乙이 임대차기간 만료되기 6개월 전부터 1개월 전까지 사이에 계약갱신을 요구할 경우, 정당한 사유없이 거절하지 못한다. (법 제10조 제1항)
④ 乙의 계약갱신요구권은 최초의 임대차기간을 포함한 전체 임대차기간이 10년을 초과하지 아니하는 범위에서만 행사할 수 있다. (법 제10조 제2항)
⑤ 乙의 계약갱신요구권에 의하여 갱신되는 임대차는 전 임대차와 동일한 조건으로 다시 계약된 것으로 본다. (법 제10조 제3항). +
////

==== 32. A주식회사는 공장부지를 확보하기 위하여 그 직원 甲과 명의신탁약정을 맺고, 甲은 2020.6.19. 개업공인중개사 乙의 중개로 丙 소유 X토지를 매수하여 2020.8.20. 甲명의로 등기하였다. 이에 대한 설명으로 틀린 것은? 

① A와 甲사이의 명의신탁약정은 丙의 선의, 악의를 묻지 아니하고 무효이다. +
② 丙이 甲에게 소유권이전등기를 할 때 비로소 A와 甲 사이의 명의신탁약정 사실을 알게 된 경우 X토지의 소유자는 丙이다. +
③ A는 甲에게 X토지의 소유권이전등기를 청구할 수 없다. +
④ 甲이 X토지를 丁에게 처분하고 소유권이전등기를 한 경우 丁은 유효하게 소유권을 취득한다. +
⑤ A와 甲의 명의신탁 약정을 丙이 알지 못하는 경우, 甲은 X토지의 소유권을 취득한다. +

////
☞ 정답 : ②
☞ 키워드 : 명의신탁약정
☞ 해설
① 명의신탁 약정은 무조건 무효이다. (부동산실권리자명의등기에관한 법률 제4조 제1항)
② 매도인(丙)의 선의, 악의 판단시기는 매매계약시기인 것으로 보인다. 매매계약시에 매도인이 선의이면 수탁자는 소유권을 취득한다고 본다는 취지 같다. 소유권이전등기는 계약의 이행단계로 선의, 악의가 이행에 영향을 미치지 않는다고 보는 취지 같다. +

③ 사례는 계약명의신탁이다. 수탁자로의 등기는 유효하므로, 신탁자는 소유권이전등기를 청구할 수 없고, 매매대금에 대한 부당이득금반환 청구만 할 수 있다. (법 제4조 제2항 단서)
④ 명의신탁 약정의 무효는 제3자(선·악 불문)에게 대항하지 못한다. (법 제4조 제3항). 따라서 丁은 유효하게 소유권을 취득한다. +

⑤ 계약명의 신탁에서 수탁자의 상대방이 선의이면 수탁자는 부동산의 소유권을 취득한다. (법 제4조 제2항 단서). +
////

==== 33. 개업공인중개사 甲의 중개로 丙은 2018.10.17. 乙소유의 용인시 소재 X주택에 대하여 보증금 5,000 만원에 2년 기간으로 乙과 임대차계약을 체결하고, 계약 당일 주택의 인도와 주민등록 이전, 임대차계약증서상의 확정일자을 받았다. 丙이 임차권등기명령을 신청하는 경우 주택임대차보호법령의 적용에 관한 甲의 설명으로 옳은 것은? 

① 丙은 임차권등기명령 신청서에 신청의 취지와 이유를 적어야 하지만, 임차권등기의 원인이 된 사실을 소명할 필요는 없다. +
② 丙이 임차권등기와 관련하여 든 비용은 乙에게 청구할 수 있으나, 임차권등기명령 신청과 관련하여 든 비용은 乙에게 청구할 수 없다. +
③ 임차권등기명령의 집행에 따른 임차권등기를 마치면 丙은 대항력을 유지하지만 우선변제권은 유지하지 못한다. +
④ 임차권등기명령의 집행에 따른 임차권등기 후에 丙이 주민등록을 서울특별시로 이전한 경우 대항력을 상실한다. +
⑤ 임차권등기명령의 집행에 따라 임차권등기가 끝난 X주택을 임차한 임차인 丁은 소액보증금에 관한 최우선변제를 받을 권리가 없다. +

////
☞ 정답 : ⑤
☞ 키워드 : 임차권등기명령
☞ 해설
① 임차권등기명령 신청서에 신청의 취지와 이유뿐만 아니라, 임차권등기의 원인이 된 사실을 소명해야 한다. (주택임대차보호법 제3조의3 제2항)
② 임차권등기와 관련하여 든 비용과 임차권등기명령 신청과 관련하여 든 비용을 임대인에게 청구할 수 있다. (법 제3조의 3 제8항)
③ 임차권등기명령의 집행에 따른 임차권등기를 마치면 대항력과 우선변제권을 유지한다. (법 제3조의 3 제5항)
④ 임차권등기명령의 집행에 따른 임차권등기 후에 丙이 주민등록을 서울특별시로 이전한 경우에도 대항력은 유지된다. (법 제3조의 3 제5항 단서)
⑤ 임차권등기명령의 집행에 따라 임차권등기가 끝난 X주택을 임차한 임차인 丁은 소액보증금에 관한 최우선변제를 받을 권리가 없다. (법 제3조의 3 제6항). +
////

==== 34. 일반중개계약서와 전속중개계약서의 서식에 공통으로 기재된 사항이 아닌 것은? 

① 첨부서류로서 중개보수 요율표 +
② 계약의 유효기간 +
③ 개업공인중개사의 중개업무 처리상황에 대한 통지의무 +
④ 중개대상물의 확인·설명에 관한 사항 +
⑤ 개업공인중개사가 중개보수를 과다 수령한 경우 차액 환급. +

////

☞ 정답 : ③
☞ 키워드 : 일반중개계약, 전속중개계약
☞ 해설
시행규칙 별표 서식 14호와 15호에 해당하는 내용이다. ③ 개업공인중개사의 중개업무 처리상황에 대한 통지의무는 15호 전속중개계약에만 있는 사항이다. +
////

==== 35. 매수신청대리인으로 등록한 개업공인중개사가 매수신청대리 위임인에게 민사집행법에 따른 부동산경매에 관하여 설명한 내용으로 틀린 것은? 

① 매수인은 매각 대상 부동산에 경매개시결정의 기입등기가 마쳐진 후 유치권을 취득한 자에게 그 유치권으로 담보하는 채권을 변제할 책임이 있다. +
② 차순위매수신고는 그 신고액이 최고가매수신고액에서 그 보증액을 뺀 금액을 넘는 때에만 할 수 있다. +
③ 매수인은 매각대금을 다 낸 때에 매각의 목적인 권리를 취득한다. +
④ 재매각절차에서 전(前)의 매수인은 매수신청을 할 수 없으며 매수신청의 보증을 돌려 줄 것을 요구하지 못한다. +
⑤ 후순위 저당권자가 경매신청을 하였더라도 매각부동산위의 모든 저당권은 매각으로 소멸된다. +

////

☞ 정답 : ①
☞ 키워드 : 매수신청대리
☞ 해설
① 매수인은 매각 대상 부동산에 경매개시결정의 기입등기가 마쳐진 후 유치권을 취득한 자에게 그 유치권으로 담보하는 채권을 변제할 책임이 없다. (대법원 2006다22050)
② 차순위매수신고는 그 신고액이 최고가매수신고액에서 그 보증액을 뺀 금액을 넘는 때에만 할 수 있다. (민사집행법 제114조)
③ 매수인은 매각대금을 다 낸 때에 매각의 목적인 권리를 취득한다. (민사집행법 제135조)
④ 재매각절차에서 전(前)의 매수인은 매수신청을 할 수 없으며 매수신청의 보증을 돌려 줄 것을 요구하지 못한다. (민사집행법 제138조)
⑤ 후순위 저당권자가 경매신청을 하였더라도 매각부동산위의 모든 저당권은 매각으로 소멸된다. (민사집행법 제91조 제2항). +
////

==== 36. 부동산 거래신고 등에 관한 법령상 부동산 매매계약에 관한 신고사항 및 신고서의 작성에 관한 설명으로 옳은 것은? 

① 「국토의 계획 및 이용에 관한 법률」에 따른 개발제한사항은 신고사항에 포함되지 않는다. +
② 「주택법」에 따라 지정된 투기과열지구에 소재하는 주택으로서 실제 거래가격이 3억원 이상인 주택의 거래계약을 체결한 경우 신고서를 제출할 때 매수인과 매도인이 공동으로 서명 및 날인한 자금조달·입주계획서를 함께 제출하여야 한다. +
③ 부동산거래계약 신고서의 물건별 거래가격란에 발코니 확장 등 선택비용에 대한 기재란은 없다. +
④ 부동산거래계약 신고서를 작성할 때 건축물의 면적은 집합건축물의 경우 연면적을 적고, 그 밖의 건축물의 경우 전용면적을 적는다. +
⑤ 개업공인중개사가 거짓으로 부동산거래계약 신고서를 작성하여 신고한 경우에는 벌금형 부과사유가 된다. +

////

☞ 정답 : ①
☞ 키워드 : 부동산거래신고사항
☞ 해설
① 「국토의 계획 및 이용에 관한 법률」에 따른 개발제한사항은 신고사항에 포함되지 않는다. 신고대상은 부동산의 매매 또는 공급계약시, 입주권 등의 매매계약시에 해당된다. +

② 「주택법」에 따라 지정된 투기과열지구에 소재하는 주택으로서 실제 거래가격이 3억원 이상인 주택의 거래계약을 체결한 경우 신고서를 제출할 때 매수인과 매도인이 공동으로 하는게 아니라 매수인이 단독으로 하며, 서명 및 날인하는게 아니라 서명 또는 날인하며, 자금조달·입주계획서를 함께 제출하는지 아니면 매수인이 별도 제출하는지 체크하여야 한다. (신고서 작성방법 ③ 참조)
③ 부동산거래계약 신고서의 물건별 거래가격란에 발코니 확장 등 선택비용에 대한 기재란이 있다. (시행규칙 별지1호 서식 참조)
④ 부동산거래계약 신고서를 작성할 때 건축물의 면적은 집합건축물의 경우 호수별 전용면적을 적고, 그 밖의 건축물의 경우 연면적을 적는다. (신고서 작성방법 ⑥ 참조)
⑤ 개업공인중개사가 거짓으로 부동산거래계약 신고서를 작성하여 신고한 경우에는 벌금형 부과사유가 아니라 과태료가 부과된다. (법 제28조). +
////

==== 37. 공인중개사의 매수신청대리인 등록 등에 관한 규칙에 따라 甲 은 매수신청대리인으로 등록하였다. 이에 관한 설명으로 틀린 것은?

① 甲이 매수신청대리의 위임을 받은 경우 민사집행법으 규정에 따라 차순위매수신고를 할 수 있다. +
② 甲은 매수신청대리권의 범위에 해당하는 대리행위를 할 때 매각장소 또는 집행법원에 직접 출석해야 한다. +
③ 매수신청대리 보수의 지급시기는 甲과 매수신청인의 약정이 없을 때에는 매각대금의 지급기한일로 한다. +
④ 甲이 중개사무소를 이전한 경우 그 날부터 10일 이내에 관할 지방법원장에게 그 사실을 신고하여야 한다. +
⑤ 甲이 매수신청대리 업무의 정지처분을 받을 수 있는 기간은 1월 이상 6월 이하이다. +

////
☞ 정답 : ⑤
☞ 키워드 : 매수신청대리
☞ 해설
① 甲이 매수신청대리의 위임을 받은 경우 민사집행법으 규정에 따라 차순위매수신고를 할 수 있다. (규칙 제2조)
② 甲은 매수신청대리권의 범위에 해당하는 대리행위를 할 때 매각장소 또는 집행법원에 직접 출석해야 한다. (규칙 제14조 제3항)
③ 매수신청대리 보수의 지급시기는 甲과 매수신청인의 약정이 없을 때에는 매각대금의 지급기한일로 한다. (규칙 제17조 제5항)
④ 甲이 중개사무소를 이전한 경우 그 날부터 10일 이내에 관할 지방법원장에게 그 사실을 신고하여야 한다. (규칙 제18조 제4항)
⑤ 甲이 매수신청대리 업무의 정지처분을 받을 수 있는 기간은 1월 이상 2년 이하이다. (규칙 제22조 제3항). +
////

==== 38. 개업공인중개사가 확인·설명하여야 할 사항 중 중개대상물 확인·설명서 [Ⅰ](주거용 건축물), [Ⅱ](비주거용 건축물), [Ⅲ](토지), [Ⅳ](입목·광업재단·공장재단) 서식에 공통적으로 기재되어 있는 것을 모두 고른 것은? . +

****
ㄱ. 권리관계 (등기부 기재사항) +
ㄴ. 비선호시설 +
ㄷ. 거래예정금액 +
ㄹ. 환경조건 (일조량·소음) +
ㅁ. 실제 권리관계 또는 공시되지 않은 물건의 권리사항. +
****

① ㄱ, ㄴ +
② ㄴ, ㄹ +
③ ㄱ, ㄴ, ㅁ +
④ ㄱ, ㄷ, ㄹ, ㅁ +
⑤ ㄱ, ㄴ, ㄷ, ㄹ, ㅁ. +

////
☞ 정답 : ③
☞ 키워드 : 확인·설명서 기재사항
☞ 해설
ㄴ. 비선호시설은 [Ⅰ](주거용 건축물), [Ⅲ](토지)에만 기재사항이고, ㄹ. 환경조건 (일조량·소음)은 [Ⅰ](주거용 건축물)에만 기재사항이다. +

ㄱ. 권리관계 (등기부 기재사항), ㄷ. 거래예정금액, ㅁ. 실제 권리관계 또는 공시되지 않은 물건의 권리사항은 네가지 확인·설명서의 공통 기재사항이다. +

////

==== 39. A시에 중개사무소를 둔 개업공인중개사 甲은 B시에 소재하는 乙 소유의 건축물 (그 중 주택의 면적은 3분의 1임)에 대하여 乙과 丙사이의 매매계약과 동시에 乙을 임차인으로 하는 임대차계약을 중개하였다. 이 경우 甲이 받을 수 있는 중개보수에 관한 설명으로 옳은 것을 모두 고른 것은? . +

****
ㄱ. 甲은 乙과 丙으로부터 각각 중개보수를 받을 수 있다. +
ㄴ. 甲은 B시가 속한 시·도의 조례에서 정한 기준에 따라 중개보수를 받아야 한다. +
ㄷ. 중개보수를 정하기 위한 거래금액의 계산은 매매계약에 관한 거래금액만을 적용한다. +
ㄹ. 주택의 중개에 대한 보수 규정을 적용한다. +
****

① ㄷ +
② ㄱ, ㄷ +
③ ㄴ, ㄹ +
④ ㄱ, ㄴ, ㄷ +
⑤ ㄱ, ㄴ, ㄹ. +

////
☞ 정답 : ②
☞ 키워드 : 중개보수
☞ 해설
ㄱ. 중개보수는 중개의뢰인 쌍방으로부터 받으므로 (시행규칙 제20조 제1항), 사례에서 의뢰인은 乙과 丙 두명이므로 이들로 부터 각각 중개보수를 받을 수 있다. +

ㄴ. 중개대상물 소재지와 중개사무소 소재지가 다른 경우에은 중개사무소 소재지 관할 시·도 조례에 다른다. (시행규칙 제20조 제3항) 따라서 甲은 A시가 속한 시·도의 조례에서 정한 기준에 따라 중개보수를 받아야 한다. +

ㄷ. 동일한 중개대상물에 대하여 동일 당사자간에 매매를 포함한 둘 이상의 거래가 동일 기회에 이루어지는 경우에는 매매계약에 관한 거래금액만을 적용한다. (시행규칙 제20조 제5항 3호) 따라서 사례는 매매와 임차 중개를 동시에 하므로 중개보수를 정하기 위한 거래금액의 계산은 매매계약에 관한 거래금액만을 적용한다. +

ㄹ. 중개대상물인 건축물 중 주택의 면적이 2분의 1이상인 경우에는 주택에 관한 규정을 적용하고, 주택의 면적이 2분의 1미만인 경우에는 주택외 건축물에 관한 규정을 적용한다. (시행규칙 제20조 제6항) 따라서 본건은 주택외 건축물의 중개에 대한 보수 규정을 적용한다. +

////

==== 40. 부동산 거래신고 등에 과난 법령상 부동산 거래신고에 관한 설명으로 옳은 것은?

① 부동산매매매계약을 체결한 경우 거래당사자는 거래계약의 체결일부터 3개월 이내에 신고관청에 단독 또는 공동으로 신고하여야 한다. +
② 「주택법」에 따라 지정된 조정대상지역에 소재하는 주택으로서 실제 거래가격이 5억원이고, 매수인이 국가인 경우 국가는 매도인과 공동으로 실제거래가격 등을 신고하여야 한다. +
③ 권리대상인 부동산 소재지를 관할하는 특별자치도 행정시의 시장은 부동산 거래신고의 신고관청이 된다. +
④ 개업공인중개사가 거래계약서를 작성·교부한 경우에는 거래당사자 또는 해당 개업공인중개사가 신고할 수 있다. +
⑤ 부동산 거래계약을 신고하려는 개업공인중개사는 부동산거래계약 신고서에 서명 또는 날인하여 관할 등록관청에 제출하여야 한다. +

////

☞ 정답 : ③
☞ 키워드 : 거래신고 관청
☞ 해설
① 부동산매매매계약을 체결한 경우 거래당사자는 거래계약의 체결일부터 3개월이 아니라 30일 이내에 신고관청에 단독 또는 공동으로 신고하여야 한다. (법 제3조 제1항)
② 투기과열지구나 조정대상지역의 주택은 금액 상관없이 자금조달계획 및 입주여부 등을 신고하여야 한다.(시행령 별표#1) 매수인이 국가인 경우 국가가 단독으로 신고하여야 한다. (법 제3조 제1항 단서)
③ 권리대상인 부동산 소재지를 관할하는 특별자치도 행정시의 시장은 부동산 거래신고의 신고관청이 된다. (법 제3조 제1항)
④ 개업공인중개사가 거래계약서를 작성·교부한 경우에는 해당 개업공인중개사가 신고해야 한다. (법 제3조 제3항) 따라서 이 경우에는 매수인은 신고의무자가 아니다. +

⑤ 부동산 거래계약을 신고하려는 개업공인중개사는 부동산거래계약 신고서에 서명 또는 날인하여 관할 등록관청이 아니라 신고관청에 제출하여야 한다. (시행규칙 제2조 제4항)
////