== 03 선사 시대의 전개

=== 1. 인류의 출현과 선사 문화

인류의 출현과 진화::

****
오스트랄로 피테쿠스 아파렌시스

호모 에렉투스

호모 네안데르탈렌시스

호모 사피엔스

****

구석기인들의 생활::

① 약 250만 년 전(호모 하빌리스)부터 시작 +
② 사냥감을 따라 이동하며 동굴이나 막집에 살았고, 짐승 가죽으로 의복 +

****
㉠ 호모 에렉투스：불을 사용하여 음식을 조리하고, 언어를 사용 +
㉡ 네안데르탈인：내세관을 가지고 죽은 사람을 매장 +
㉢ 크로마뇽인：현생 인류로, 동굴 벽화와 조각(풍만한 여인상)을 남김
****

신석기인들의 생활 - 신석기 혁명::

① 농경과 목축의 시작 +
② 새로운 도구의 사용 (간석기, 토기, 의복) +
③ 취락의 형성과 종교 등 생활의 변화

****
㉠ 야생 곡류를 주기적으로 채집하다가, 기원전 9000년경 티그리스·유프라테스강 유역의 이른바 비옥한 초승달 지대에서 직접 씨를 뿌려 수확하는 농경이 시작되었다. 최초의 작물은 보리, 밀, 콩, 아마 등이었다. +
㉡ 최초의 가축인 개를 시작으로, 경작에 쓰이는 소·양 등에 이어 고기를 얻기 위한 돼지와 닭 등이 차례로 가축화되었다.


㉠ 돌을 갈아 도구를 만들게 되었다. 벌목용 도끼와 낫, 농사를 위한 괭이, 가래, 갈돌 등이 사용되었다. +
㉡ 사냥·어로 지역은 빗살무늬 토기가, 농경 지역에서는 칠무늬 토기가 주로 제작되었다. +
㉢ 가락바퀴(실 제작), 베틀(천 제작) 등이 발명되어 옷감을 짜 입었다.


㉠ 생산성 향상으로 인구 규모가 커져 취락이 만들어졌다. 공동 노동의 필요로 혈연의 씨족 사회가 형성되고, 정착 생활로 인해 농경·저장·주거 등을 향상시키는 도구와 기술의 개선이 이루어졌다. +
㉡ 애니미즘, 영혼 신앙, 조상 숭배, 거석 숭배 등이 발생하였다. +
****


청동기 문명의 발생::

① 청동기 사용, 도시 발전, 사유 재산제, 계급 분화, 도시 국가 출현, 종교 발전, 문자 사용 등의 특징을 가지고 있다. +
② 기후가 따뜻하고 관개 농업에 유리한 큰 하천 지역에서 문명이 시작되었다. +
③ 메소포타미아, 이집트, 인도, 중국 문명

=== 2. 우리 민족의 기원

(1) 구석기 시대 사람들을 우리의 직접적인 조상으로는 볼 수 없다::

구석기 시대부터 여러 인류가 중국 만주와 한반도를 중심으로 한 동북아시아 지역에 널리 분포하였다. 몇 차례의 빙기와 간빙기를 거치면서 구석기인은 대부분 멸종하였거나 다른 곳으로 이동한 것으로 보인다

(2) 신석기부터 청동기 시대를 거치면서 민족의 기틀이 형성::

① 마지막 빙하기 이후 등장한 신석기 문화는 청동기 문화까지 연속적으로 발전하는 모습을 보인다. +
② 중국 문헌에 동이족, 예족, 맥족, 예맥족, 한족 등으로 기록되어 있다. +
③ 언어학상으로 알타이 어족에 속한다. 농경으로 정착 생활을 하면서 독자 문화를 형성하여, 점차 하나의 민족으로 형성해 갔다. +


=== 3. 구석기 시대의 시기 구분과 유물·유적

(1) 약 70만 년전부터 한반도와 중국 동북 지역에 구석기인이 거주::

① 현존 가장 오래된 구석기 유적지는 단양 도담리 금굴 유적이며, 약 70만 년 전의 것으로 추정된다. +
② 석기를 다듬는 수법에 따라 전기, 중기, 후기의 세 시기로 나눌 수 있다.

(2) 구석기 시대 유적 분포와 주요 유적::

① 큰 강가에서는 야외 유적, 석회암 지대에서는 동굴 유적이 주로 나타나며 전국적으로 분포되어 있다. 그 중 대동강 유역과 남한강 일대에서 집중 출토되고 있다. +
② 1933년 함경북도 종성군 동관진(오늘날 온성군 강안리)에서 처음 발견된 이래 지금까지 70여 곳을 발굴·조사하였다. 남한에서는 1964년에 공주 석장리에서 구석기 시대 유적을 찾아낸 뒤로, 1978년에는 연천 전곡리, 1988년에는 파주 가월리와 주월리에서 대규모의 구석기 시대 유적을 찾아냈다. 구석기 시대 유적은 전국에 고루 분포되어 있어 구석기 문화가 한반도 전역에서 발달하였음을 알 수 있다. +

㉠ 북한 웅기 굴포리(1960~1964년 발굴) 유적, 공주 석장리(1964~1974년 발굴) 유적이 처음으로 구석기 시대 유적으로 인정받았다. +

㉡ 최초 및 최고 유적
****
• 최초 발견：함북 종성 동관진(오늘날 강안리 유적) +
• 최초 발굴(북)：웅기 굴포리(1960~1964) +
• 최초 발굴(남)：공주 석장리(1964~1974) +
• 최초 동굴 유적 발굴(남)：제천 점말 동굴(1973) cf 제주 빌레못 동굴(1973) +
• 최초 아슐리안형 석기 발굴：경기 연천 전곡리(1978) +

가장 오래된 유적: 단양 도담리 금굴：70만 년 전 추정 cf 상원 검은모루 동굴：60만~40만 년 전 추정

****

③ 우리나라에서 인골이 발견된 지역::

㉠ 역포아이：평양 역포 대현동 동굴에서 발견되었으며, 10만 년 전에 살았던 7세의 어린아이로 추정하고 있다. +
㉡ 만달인：평양 만달리 유적에서 발견되었으며, 호모 사피엔스의 두개골이 발견되었다. +
㉢ 승리산인：평남 덕천 승리산 동굴에서 발견되었으며, 한반도에서 최초로 발견된 인골 화석이다. +
㉣ 흥수아이：충북 청원 두루봉 동굴에서 출토된 어린아이 인골 화석이다. +
㉤ 상시인：단양 상시리 바위그늘에서 남한 최초로 발견된 인류 화석이다. +

==== 전기 유적

단양 도담리 금굴(1983)::

• 가장 오래된 구석기 유적지(기원전 70만 년경)
• 전기 구석기 ~ 청동기 유적이 연속적으로 발견되는 표준 유적의 하나

공주 석장리(1964)::
• 남한 최초로 발굴된 구석기 유적지 → 구석기 시대의 존재 확정
• 전기 ~ 후기 구석기 유적 모두 출토
• 다양한 찍개·주먹도끼 등 출토
• 처음으로 잔석기 확인
• 후기 막집터와 고래 선각화, 개·멧돼지 조각 등 예술품 발견

상원 검은모루동굴(1966)::
• 주먹도끼와 흡사한 석기, 찍개 등 출토
• 빙기의 큰쌍코뿔이 뼈와 간빙기의 작은 포유류 뼈 발견

경기 연천 전곡리(1978)::
• 전기 ~ 후기 구석기 유적 추정
• 아시아 최초로 아슐리안형 주먹도끼 발견 → 모비우스 이론 부정

제천 점말 동굴(1973)::
• 전기 ~ 후기 구석기 시대 유적
• 털코뿔이뼈에 새긴 사람 얼굴 조각 발견
• 단양 상시리 바위그늘(1981)보다 앞서 인골 출토 보고 → 극소량이라 연구되지 않음.

웅기 굴포리 (1960)::
• 전기 ~ 후기 구석기 시대 유적
• 북한 최초로 발굴된 구석기 유적지
• 전기 구석기 시대의 막집 자리 발견, 모루와 격지 석기 발견

=== 중기

덕천 승리산 동굴(1972)::
• 우리나라 최초 인골 출토
• 덕천인(슬기사람, 중기 구석기), 승리산인(슬기슬기사람, 후기 구석기)

평양 역포 대현동 동굴(1977)::
10세 미만 아이의 인골 출토 → 역포인(슬기사람)
단양 상시리 바위그늘(1981)
• 중기 구석기 ~ 청동기 시대 유적, 말뼈 치레걸이와 뼈 도구 출토
• 남한 최초 인골 출토 → 상시인(슬기사람)

동해 발한동 유적(1995)::
• 강원 명주 심곡리 유적과 함께 동해안의 전기~ 중기 구석기 연구 자료
• 제4빙하기에 우리나라 동·남해안 → 쓰시마, 규슈 이동 가능성 입증

양구 상무룡리 유적(1987)::
• 중기 ~ 후기 구석기, 석기 제작소 및 백두산계 흑요석 출토
• 남한 최북단 구석기 유적 → 북한 구석기와 진부령 이남 구석기의 징검다리
기타 승주 곡천 유적(호남 지방에서 처음 발견). 상원 용곡동굴(사람 머리뼈 출토)

=== 후기

함북 종성 동관진(1933)::
• 한반도 구석기 시대의 존재 최초 확인
• 뼈 도구, 흑요석 석기, 포유류(매머드) 화석 발견

청원 두루봉 동굴 (1976)::
• 제2굴, 15굴, 새굴, 처녀굴, 흥수굴 등 여러 동굴 유적 발견
• 동굴 입구 꽃가루로 장식, 치레걸이, 의식 집행 흔적(동물뼈를 동쪽에 배열)
• 흥수굴：소년 2명의 완전한 인골 발견, 장례 의식 확인
• 사람 얼굴을 새긴 사슴 뼈 발견

단양 수양개(1983)::
• 중기 구석기 ~ 청동기 시대 유적
• 후기 구석기：소뼈에 물고기 모양 조각, 아시아 최초의 눈금 새김돌 발견
• 50곳 이상의 석기 제작소, 일본 규슈 및 사할린 구석기와 교류 가능성

홍천 하화계리::
석영 석기와 흑요석 석기 별도의 제작장(분업 존재), 잔석기 출토


=== 4. 구석기 시대 사람들의 생활

(1) 동물을 사냥하거나 나무 열매와 뿌리를 채집::
사냥 도구로 주먹도끼와 찍개, 조리 도구로 긁개와 밀개 등을 사용하였다. 점차 뗀석기 제작 기술이 발전하였으며, 동물의 뼈나 뿔로 만든 뼈 도구를 만들기도 하였다. => 구석기 시대 후기에는 슴베찌르개를 사용하였다.

(2) 평등한 무리 사회와 동굴과 막집 형태::
① 기후에 따라 사냥감을 쫓아 이동 생활을 하였으며, 수십 명 내외의 무리 사회를 이루었다. +
② 무리 중에 경험이 많고 지혜로운 사람(연장자)이 지도자가 되었으나 권력을 갖지는 못하였다. 모든 사람이 평등한 공동체 생활을 하였다. +
③ 고정된 거주지를 건설하지 않았고, 동굴(검은모루 동굴) 및 바위그늘(단양 상시리)이나 강가에 막집(공주 석장리)을 짓고 거주하였다. 공주 석장리 유적에는 막집의 기둥 자리나 불을 피운 흔적이 있으며, 대체로 3~4명이 생활할 수 있는 규모이다.

(3) 사냥감의 번성을 비는 주술적 의미로서의 예술::
① 석회암이나 동물의 뼈로 만든 조각품이 만들어졌다. +
② 공주 석장리와 단양 수양개에서 고래와 물고기 등을 새긴 조각이, 청원 두루봉 동굴에서는 사람 얼굴을 새긴 사슴 뼈가, 단양 수양개에서 4mm 간격으로 눈금이 새겨진 돌이 발견되었다.


=== 5. 중석기 시대의 생활

(1) 기원전 1만년경 간빙기가 되면서 기온이 올라가고 해수면이 상승::
기후 변화에 따라 빙하가 후퇴하고 털코뿔이나 매머드 등의 대형 포유류가 사라졌으며, 토끼·여우·사슴·새 등 비교적 작고 날쌘 동물들이 많아졌다.

(2) 원거리 사냥 도구와 작고 섬세하게 가공된 잔석기를 제작::
① 사냥에 활과 투창이 사용되고 물고기와 조개류 등 고기잡이 비중이 커졌다. +
② 작고 섬세하게 가공된 잔석기, 잔석기를 나무나 뼈에 꽂아 쓰는 이음 도구를 만들기도 하였다. 이음 도구에는 톱, 활, 창, 작살 등이 있었다. 또한, 슴베를 나무 자루에 박아 창의 기능을 하는 슴베찌르개가 후기 구석기 시대부터 중석기 시대에 이르기까지 사용되었다.

(3) 중석기 시대를 구석기 시대와 신석기 시대 간의 과도기로 인식::
① 식량 채집 단계에서 생산 단계로 넘어가는 과도기로 볼 수 있으며, 잔석기의 대량 생산이 가능해졌음을 의미한다. +
② 제주 고산리 유적지에서는 잔석기와 함께 신석기 시대의 산물인 토기가 발굴되었다.


=== 6.신석기 시대의 유물과 유적

(1) 우리나라의 신석기 시대는 기원전 8000년경::

제주도 한경 고산리 유적 최하층에서 이른 민무늬 토기가 출토됨에 따라 우리나라의 신석기 시대는 기원전 8000년경, 즉 지금부터 약 1만년 전에 시작되었다는 것을 알게 되었다

2) 간석기 제작과 사용::

① 석기 제작 기술이 발전하여 용도가 분화되고 정교한 도구를 만들 수 있었다. +
② 간석기의 종류 +
****
㉠ 경작을 위한 괭이, 삽, 보습, 낫 등과 곡식을 가공·조리하기 위한 갈돌, 갈판 등이 있다. +
㉡ 돌도끼, 자귀, 대팻날, 끌 등으로 나무를 베거나 목재를 가공할 수 있었다. +
㉢ 사냥·고기잡이에 화살촉, 창, 검 등과 그물추 등이 제작되었다. +
㉣ 생활 도구로는 가락바퀴, 뼈바늘, 숫돌 등이 있다. +
****
③ 농경과 정착 생활이 시작되면서 주거지 건설과 개간에 규격화된 간석기가 확산되고 재활용이 가능해서 더욱 중요해졌다.


(3) 토기 사용으로 음식물 조리나 저장이 가능::

① 이른 민무늬, 덧무늬, 눌러찍기무늬 토기 등이 제주 한경 고산리, 강원도 고성 문암리, 강원도 양양 오산리, 부산 동삼동 등에서 발견되었다. +
② 빗살무늬 토기는 신석기 시대의 대표적인 토기로 다양한 크기가 발견되었다. 서울 암사동, 평양 남경, 김해 수가리, 양양 오산리 등 전국적으로 출토되고 있다. +

▲ 이른 민무늬 토기(부산 동삼동)
▲ 덧무늬 토기 
▲ 첨저형 빗살무늬토기(서울 암사동)
▲ 평저형 빗살무늬 토기(양양 오산리)

(4) 조개더미(조개무지, 패총)::

강가나 바닷가에 살면서 어패류도 많이 채취하였다. 이들이 남긴 조개껍데기가 쌓인 것을 조개더미라고 하는데, 조개의 칼슘 성분 때문에 보존 상태가 좋다. 강가나 해안에 전국적으로 분포하며 웅기 굴포리 서포항, 부산 동삼동 등이 유명하다.


=== 7. 신석기 시대의 생활

(1) 조, 기장, 피, 수수가 주요 작물::

① 황해도 봉산 지탑리와 평양 남경, 경기 김포 가현리, 진주 상촌리 등의 유적에서는 탄화된 좁쌀과 기장 등이 발견되었다. 또한 가축을 길러 고기를 먹거나 가죽으로 옷을 만들어 입었다. +
② 강원도 고성 문암리에서 동아시아 최초로 신석기 시대의 밭 유적이 발견되었다. 청동기 시대와 비교할 때 밭고랑의 너비와 방향이 일정하지 않은 초기 형태이며, 집자리와 함께 발견되었다. 대체로 신석기 시대에는 집 근처의 텃밭을 이용하거나 강가의 퇴적지를 소규모로 경작하였을 것으로 보인다. +
③ 땅을 파는 도구(✚굴지구)로 돌괭이·돌삽·돌보습·뿔괭이 등이 있다. 수확을 위한 도구로 돌낫 등이 있으며 대부분 청동기 시대까지 이어지며 사용되었다. 나무로 만든 농기구도 사용된 것으로 보이나 유물로 출토된 것은 대부분 동물의 뼈나 뿔 및 돌로 만든 농기구이다. +
④ 식량 생산이 증대되면서 인구가 크게 늘어났다. 그러나 생산력 수준이 아직 높지 않아, 자급자족적 공동체를 이루어 도구를 공동으로 소유하고 공동으로 경작하거나 사냥 등의 활동을 하였으며, 생산물을 공평하게 분배하였다.

(2) 사냥과 고기잡이도 병행::

① 농경이 발달하면서 사냥과 고기잡이 비중이 줄었지만, 여전히 식량을 얻는 중요한 수단이었다. +
② 주로 활이나 창으로 사슴류와 멧돼지 등을 사냥하였다. +
③ 통나무 배와 낚시 도구, 작살과 그물을 만들었다. 고기잡이 과정에서 일본과 교류하기도 하였다. 부산 동삼동, 통영 상노대도, 김해 수가리 등에서 일본산 흑요석이 발견되고, 일본 서북 규슈 지역 및 쓰시마 섬의 패총 등에서 한반도의 것과 유사한 빗살무늬 토기와 장신구가 출토된 것을 통해 이를 짐작할 수 있다.

(3) 원시 수공업::
가락바퀴(방추차)를 통해 실을 뽑고, 뼈바늘로 바느질을 하여 옷이나 그물을 만들었다. 이외에도 그물을 가라앉히기 위한 그물추가 발견되었다.

(4) 주거는 물과 식량 자원이 풍부한 해안이나 큰 강가에 위치::
① 움집 바닥은 대개 원형이나 모서리가 둥근 사각형이며, 움집의 내부는 취사 및 일상적 작업 공간, 잠자리, 대형 토기를 비치한 저장 공간 등으로 분할하여 사용되었다. 취사와 난방을 위한 화덕은 움집의 중앙에 있었으며, 화덕이나 출입문 옆에 별도의 저장 구덩을 설치하기도 하였다. 출입문은 대체로 햇볕을 받을 수 있는 남쪽으로 냈다. +
② 움집은 4~5명 크기였다. 10여 기 미만의 소규모 취락도 많지만, 서울 사동에서는 30여 기 이상의 움집터가 발견되었다.

(5) 씨족사회가 결합한 부족사회와 평등 사회::
① 혈역 중심의 씨족 단위로 부족 사회를 이루고 있었다. 씨족마다 일정한 영역이 있어 다른 씨족의 영역을 침범하지 못했다. 씨족은 족외혼을 통해 다른 씨족과 연결되었고, 일정 지역의 몇 개의 씨족이 모여 부족을 이루었다. +
② 연장자나 경험이 많은 자가 자기 부족을 이끌어 나가는 평등 사회였다. 중대한 일은 씨족 사회에서 만장일치로 결정하였고(신라의 화백 회의에 영향), 사회적 분업은 없으나 연령이나 성별에 따라 분업이 존재하였다. +
③ 채집에서는 여성의 역할이 컸기 때문에 모계 중심 사회지만 신석기 시대 말부터 청동기 시대에 걸쳐 농경과 전쟁 등에서 남성의 역할이 커지면서 부계 사회로 전환되었다

6) 농경과 정착 생활을 하게 되면서 자연의 섭리를 생각::
① 애니미즘：농사에 큰 영향을 끼치는 자연 현상이나 자연계의 사물에 영혼이 깃들어 있다고 생각하고 이를 숭배하는 신앙이다. 특히 태양과 물에 대한 숭배가 으뜸이었다.  영혼 불멸 사상, 태양신, 지모신 사상 등에 영향을 끼쳤다. +
② 샤머니즘：인간과 영혼 또는 하늘을 연결시켜 주는 존재인 무당(샤먼)과 그 주술을 믿는 신앙이다.  고조선의 단군, 삼한의 천군, 신라의 차차웅 등에 영향을 끼쳤다 +
③ 토테미즘：자기 부족의 기원을 특정 동식물과 연결시켜 이를 숭배하는 신앙이다. 신석기 시대 사람들은 어떤 특정한 동물과 식물을 공동 조상으로 받들고 자신들이 다른 집단과 다르다는 것을 과시하였다.  단군 신화의 곰과 호랑이, 박혁거세의 말, 석탈해의 까치, 김알지의 닭, 금와왕의 개구리 등에 영향을 끼쳤다. +
④ 영혼 숭배, 조상 숭배：사람은 죽어도 영혼은 없어지지 않는다는 믿음에서 출발하였다. 그래서 사람이 죽으면 정성스럽게 묻는 풍습이 생겨났으며, 생전에 아끼던 물건을 함께 묻기도 하였다.

(7) 예술::
원시 신앙과 함께 종교적 의례와 이를 위한 예술 활동이 행해졌다. 빗살무늬 토기에 나타났던 직선과 곡선, 번개무늬 등의 기하학적 형태가 점차 물이나 식물(곡물), 태양을 상징하는 주술적 성격을 띠게 되었다. 지모신 사상의 영향을 받은 여성 형상의 토우(울산 신암리, 웅기 굴포리 서포항, 청진 농포동 등), 얼굴 모양 토제품(양양 오산리, 울진), 조개껍데기 가면, 동물의 뼈나 뿔 또는 조개껍데기로 치레걸이 등을 만들었다.

(8) 무덤::
① 흙을 파서 관 없이 매장하는 토묘, 구덩이를 파서 매장하는 토장묘(구덩무덤), 씨족 공동묘, 시신의 머리를 동쪽으로 두고 얼굴을 위로 향하게 한 동침신전앙와장(東枕伸展仰臥葬) 등이 있었다. +
② 신석기 시대의 무덤으로는 춘천 교동의 동굴 유적, 시흥 시도 및 부산 동삼동 조개더미의 돌무
덤, 부산 범방의 토장묘, 통영 연대도·욕지도 산등조개더미에서 보이는 집단 토장묘 등이 있다.