= 01 선사 문화와 국가의 형성

== 5 고조선의 형성과 발전

=== 1 단군과 고조선

[#고조선:건국]
==== (1) 고조선의 건국
① **성립**: 농경과 청동기 문화를 배경으로 한 군장 국가로 성립되었다. 지배자의 칭호는 단군왕검이었고, 이후 철기 문화를 수용하면서 점차 세력이 강대해져 주변 지역을 통합하여 연맹체 국가로 성장하였다. +

② 고조선 관련 사료::
[#고조선:중국사료]
* 중국 사료::
* <삼국유사>에서는 중국의 <고기(古記)>와 <위서(魏書)>를 인용하였는데, <고기(古記)>는 현재 전하지 않으며, 현재의 <위서(魏書)>에서도 기록을 찾을 수 없다. 
* 고조선에 대한 언급은 전국 시대의 <관자>와 <산해경>에 언급되고 있다. 
* 후한의 역사서인 <한서>에는 고조선의 8조법 중 3개 조항이 남아 있다. +

[#고조선:우리나라사료]
* 우리나라의 관련 사료::

* <삼국유사> 일연 충렬왕 7년(1281) 우리나라 사서로는 단군이야기가 수록된 가장 오래된 문헌, <고기>를 인용함.
* <제왕운기> 이승휴 충렬왕 13년(1287) <본기>를 인용하여 단군이야기 소개, 웅녀
와 곰, 호랑이 이야기가 없음.
* <세종실록지리지> 조선 단종 2년(1454) 평양조에 단군이야기 소개, 단군의 아들 부루가 북부여 왕이 되고 중국 우왕의 도산회맹에 참가했다는 내용 기록
* <응제시주> 권람 조선 세조 8년(1462) <세종실록지리지>와 비슷한 내용
* <삼국사절요> 서거정 등 조선 성종 7년(1476) 단군의 건국 사실을 간략히 기록
* <(신증)동국여지승람> 노사신 조선 성종 12년(1481),중종 25년(1530) 평양 서쪽 단군묘에 대한 기록
* <동국통감> 서거정 조선 성종 16년(1485) <삼국사절요>와 비슷한 내용

③ 세력 범위::
재요녕성설·재평양설·이동설로 크게 구분된다. 남한 학계의 다수는 이동설에 중점을 두어 요령 지방을 중심으로 성장하여 한반도까지 발전하였다고 본다. 한편, 고조선의 세력 범위는 비파형 동검과 탁자식 고인돌의 출토 범위와 대체로 일치한다.

[#단군의건국이야기]
==== (2) 단군의 건국 이야기
① 건국의 의미::
* 고조선 건국 배경：청동기 문화를 배경으로 한 고조선 성립이라는 역사적 사실을 반영하고 있다. +
* 선민사상：하늘에서 내려 왔다는 내용은 환웅 부족이 이주민 집단임을 나타내며, 스스로 하늘의 자손임을 내세운 천손사상을 반영하고 있다. +
* 홍익인간의 이념：널리 인간을 이롭게 한다는 통치 이념이 제시되어 있는데, 이는 지배층의 권위를 내세우고자 하는 의도가 담겨 있다. +
㉣ 샤머니즘：태백산 신단수는 원시 신앙인 ✚신목(神木) 신앙의 일종으로 애니미즘 및 샤머니즘과의 관련성을 보여 준다. 또한 신목은 북방계 샤머니즘에서 하늘과 통하는 통로로서, 단군(환웅)이 제천 행사를 주관했음을 의미하기도 한다. +
㉤ 농경 사회：풍백(風伯), 우사(雨師), 운사(雲師)가 바람, 비, 구름 등을 주관하였다는 기록은 농경의 발달을 반영한다. +
㉥ 엄격한 신분 사회：지배 계급이 농사와 형벌 등의 사회 생활을 주도하였다는 내용은 청동기 시대에 들어와 새롭게 성립된 사회 질서를 반영하고 있다. +
㉦ 토테미즘：이주민 집단인 환웅 부족이 곰을 토템으로 삼은 부족과 연합하여 고조선을 형성하였으며, 호랑이 토템 부족은 배제되었다는 사실이 반영되어 있다. +
㉧ 제정일치：단군왕검의 단군은 제사장, 왕검은 정치적 지배자로 당시가 제정일치 사회였음을 알 수 있다.

② 건국의 의의::
* 고조선 건국 연대가 중국 하나라와 비견된다는 점에서 우리 민족 역사의 유구성을 찾을 수 있다. +
* 천손사상과 홍익인간 정신 등 우리 고유의 사상을 반영하고 있다. +
* 외적의 침략 등 국가적 위기 때 이를 극복하고 민족적 전통과 자주성을 되새기는 구심점이 되어 왔다.

[#고조선:발전]
==== (3) 고조선의 발전
① **발전**：고조선은 요령 지방과 대동강 유역을 중심으로 독자적인 문화를 이룩하면서 발전하였는데, 기원전 4세기경에는 요서 지방을 경계로 하여 중국 연나라와 대립하고 왕을 칭할 만큼 강성하였다. +
② **영토 변화**：기원전 300년경 연나라 진개의 공격을 받아 서쪽 2천여 리의 영토를 상실하고 중심지가 평양으로 옮겨졌다. +
③ **정치 체제**：기원전 3세기경에는 부왕, 준왕 같은 강력한 왕이 등장하여 왕위의 부자 세습이 이루어졌다. 관직으로 중앙에서 정치를 보좌하는 대부(大夫), 일정한 지방을 다스리는 박사(博士)의 존재를 확인할 수 있다. +

=== 2. 위만의 집권

[#고조선::위만조선의성립]
==== (1) 위만 조선의 성립(기원전 194)
① **배경**: 중국이 전국 시대 이후로 혼란에 휩싸이자 유이민들이 대거 고조선으로 넘어왔다. 그 뒤 진·한 교체기에 또 한 차례의 유이민 집단이 이주해 왔는데, 그중 위만은 1,000여 명의 무리를 이끌고 고조선으로 들어왔다.

② **위만의 집권**：위만은 준왕의 신임을 받아 서쪽 변경을 수비하는 임무를 맡게 되었는데, 그곳에 거주하는 이주민 세력을 통솔하면서 자신의 세력을 확대하여 나갔다. 그후 위만은 왕을 보호한다는 구실로 왕검성으로 들어와 준왕을 몰아 내고 스스로 왕이 되었다(기원전 194).

[#고조선::위만조선의발전]
==== (2) 위만 조선의 발전
① 철기 문화의 수용::
유이민과 함께 철기 문화를 본격적으로 수용하였다. 철기의 사용은 농업과 무기 생산을 중심으로 한 수공업을 더욱 융성하게 하였고, 상업과 무역도 발달하였다. +
② 정치 체제::
* 태자(太子) 칭호 사용：우거왕의 아들을 태자라 칭하여 이전보다 강화된 왕권을 보여 준다. +
* 관직：부왕적 성격을 보이는 비왕(裨王), 내정과 군사의 정무를 담당하는 상(相)·장군(將軍) 등이 중앙 정치를 운영하였고, 지방에서는 중앙의 통치력을 대변하는 박사와 지역 기반을 바탕으로 한 상·경(卿) 등이 통치하였다. 상은 왕 밑에서 국무를 관장하던 직책으로, 왕과 함께 국가의 중요한 일을 처리하는 회의에 참여하였으며, 자신이 직접 다스리는 영역과 주민이 있었다. 한편 궁인(宮人)이라는 지배 체제의 하층을 담당하는 중간층도 등장하였다. +
③ 정복 사업::
철기 기술의 발전과 경제력 향상으로 중앙 정치 조직을 갖춘 강력한 국가로 성장하였다. 우세한 무력을 바탕으로 활발한 정복 사업을 전개하여 진번·임둔 등 주변 지역을 복속시키며 광대한 영토를 차지하였다. +
④ 중계 무역::
지리적인 이점을 이용하여 동방의 예나 남방의 진(辰)이 직접 중국의 한과 교역하는 것을 막고, 중계 무역의 이득을 독점하려 하였다. 고조선은 이러한 경제적·군사적 발전을 기반으로 한(漢)과 대립하였다.

[#고조선:한의침략과멸망]
==== (3) 한의 침략과 멸망
① 한 무제의 침략::
대외 팽창 정책을 펴고 있던 한 무제는 흉노와 남월을 복속시키고, 위만의 손자 우거왕 때 수륙 양면으로 대규모의 군대를 보내 고조선을 침략하였다. +
② 고조선 멸망::
고조선은 1차의 접전(패수)에서 대승을 거두었다. 이후 약 1년에 걸쳐 한의 군대에 맞서 완강하게 대항하였으나, 결국 장기간의 전쟁으로 지배층의 내분이 일어나 왕검성이 함락되어 멸망하였다(기원전 108). +
③ 한 군현 설치::
한(漢)은 고조선의 일부 지역에 4개의 군(임둔·진번·현도·낙랑군)을 설치하여 지배하고자 하였으나, 토착민의 강력한 반발에 부딪혔다. 이후 3개 군은 토착민의 저항으로 쫓겨가거나 폐지되었고, 낙랑군은 313년 고구려의 공격을 받아 축출되었다. +

[#고조선:위만조선의의미]
==== (4) 위만 조선의 의미
위만은 고조선으로 들어올 때 상투를 틀고 조선인의 옷을 입고 있었고, 왕이 된 뒤에도 나라 이름을 그대로 조선이라 하였다. 그의 정권에는 토착민(조선인) 출신으로 높은 지위에 오른 자가 많았다. 이를 통해 위만 조선이 단군 조선을 계승하였음을 알 수 있다.

=== 3. 고조선의 사회

[#고조선:생활모습]
==== (1) 생활 모습
① 시대 배경::
청동기 문화를 기반으로 성립되어 철기 문화를 수용하며 발전하였다. 초기에는 돌무지무덤이나 고인돌, 후기에는 널무덤과 돌널무덤을 축조하였다. 특히 비교적 초기의 것으로 보이는 요동 반도의 강상 무덤과 누상 무덤에서는 대규모 순장의 흔적이 발견되었다.
② 생활::
채소를 소금에 절여먹었고, 농민들은 대나무 그릇을 사용하였다. 도시의 관리나 상인은 술잔 같은 그릇을 사용했다고 하여 도시가 형성되었음을 알 수 있다. 한편 우리나라 최초의 시가인 공무도하가가 이 시기에 불려졌다.

[#고조선:8조법]
==== (2) 8조법
① 후한 때 편찬된 반고의 <한서(漢書)> 지리지(地理志)에 고조선의 8조법 중 3개 조목의 내용을 전하고 있다. +
② 발달된 생산력을 기초로 사유 재산제가 확립되었고, 노동력과 사유 재산을 보호하였다. 노비의 존재와 형벌권을 행사하는 통치자 계급이 분화되었고, 가족 제도에서는 가부장적 성향이 강화되고 있었다.

[#고조선:한군현설치이후]
==== (3) 한 군현 설치 이후
① 고조선 유민들이 한의 지배에 반발했고, 고구려의 공격으로 진번과 임둔은 금방 폐지되었다. 이런 상황에서 한 군현은 엄한 율령을 시행하여 자신들의 생명과 재산을 보호하려 하였다. 그에 따라 법 조항도 60여 조로 증가하였고, 풍속도 각박해져 갔다. +
② 비교적 오래 존속한 낙랑에서는 중국과 고조선 문화가 융합하여 합장묘나 박산로(중국 산둥 성에 있는 박산의 모양을 본뜬 향로) 등 독특한 특징이 나타나기도 하였다. 그리고 가장 오래된 금석문인 점제현 신사비가 발견되었다.