= 06 여러 나라의 성장

=== 1 연맹 왕국

군장 국가로 출발했던 소국 중 우세한 부족이 주변 지역을 복속시키며 연맹 왕국으로 발전하였다. 유력 부족의 지배자가 연맹장으로서 왕이 되지만, 각 부족의 군장은 왕실에 예속되면서도 독자적으로 자신의 부족을 통치하였다. 족장들은 회의를 통해 국가 중대사를 합의하였고, 왕의 폐위까지 결정할 정도였다. 그러나 왕은 군사와 외교의 대표자였고, 자기 부족의 시조신을 국가 제의의 대상으로 삼으며 권력을 강화해 갔다.

=== 2 부여

[#부여:건국]
==== (1) 건국

부여에 관한 최초의 기록은 <사기>이며, 기원전 4세기경 건국된 것으로 추정된다. 부여는 만주 길림시 일대를 중심으로 송화강(쑹화 강) 유역의 평야 지대에서 성장하였다.

[#부여:정치]
==== (2) 정치적 발전

① **발전**:
1세기 초에 왕호를 사용하였고, 중국과 외교 관계를 맺는 등 발전된 국가의 모습을 보였다. 서쪽으로는 선비족, 남쪽으로는 고구려와 접하고 있었다. +

② **5부족 연맹체 형성**
왕 아래에 가축의 이름을 딴 마가, 우가, 저가, 구가와 대사자, 사자 등의 관리가 있었다. 이들 가(加)는 따로 행정 구획인 사출도(四出道)를 다스리고 관리(사자)도 독자적으로 임명하면서 왕이 직접 통치하는 중앙과 합쳐 5부를 이루었다. +

③ **왕의 지위**:
부여는 왕권이 미약한 연맹 왕국이었다. 부족장인 가(加)들은 왕을 추대하기도 하고, 수해나 한해로 곡식이 잘 익지 않으면 왕에게 책임을 묻기도 하였다. 그러나 왕을 배출하는 부족의 세력은 매우 강해서 궁궐, 감옥, 창고 등의 시설을 갖추었다. +

④ **외교**: 서쪽으로는 북방 유목 민족인 선비족과 남쪽으로는 고구려와 대립하였으며, 선비족과 고구려를 견제하기 위해 중국의 한과 친선 관계를 유지하였다.

[#부여:경제]
==== (3) 경제
농경과 목축이 발달하였으며, 특산물로는 말, 주옥, 모피 등이 유명하여 이를 중국에 수출
하기도 하였다. 농사는 밭농사 위주이고 과실은 나지 않았다.

[#부여:사회와문화]
==== (4) 사회와 문화

① **신분**: 왕·제가(족장들)·호민(경제적으로 부유한 계층)이 지배층을 이루었고, 피지배층은 하호(평민)와 노비로 구성되었다.

② 풍속::
* **생활 모습**: 흰옷을 입는 풍습이 있었다. 지배층은 금·은으로 치장하고 식사할 때 제사용 그릇인 조두를 사용하였다. 유목 사회의 풍습인 ✚**형사취수제**가 있었다. +
* **장례 풍습**: 사망 후 시신을 오래 두었다가 묻는 정장(停葬) 풍습이 있어 여름에는 얼음을 사용하였다. 껴묻거리를 많이 묻는 후장을 지냈고, 왕이 죽으면 많은 사람들을 껴묻거리와 함께 순장하였다. +
* **우제점복**: 전쟁이 일어났을 때에는 제천 의식을 행하고, 소를 죽여 그 굽으로 길흉을 점치기도 하였다. +
* **제천 행사**: 12월에 **영고**라는 제천 행사를 열었는데, 이것은 수렵 사회의 전통을 보여준다. 이때 하늘에 제사를 지내고 노래와 춤을 즐기고, 죄수를 풀어 주기도 하였다. 제천 행사인 영고는 전쟁 중에도 행해졌다. +

③ **법률**: 부여의 법률에는 **4조목**이 전하고 있다.

법률 조항 의미::
1. 살인한 자는 사형에 처하고 그 가족은 노비로 한다.(보복적 성격, 엄격한 법 적용, 노비 소유 인정) +
2. 남의 물건을 훔쳤을 때에는 물건값의 12배를 배상해야 한다. (1책 12법, 사유 재산 보호) +
3. 간음한 자는 사형에 처한다. (가부장적 사회) +
4. 부인이 질투하면 사형에 처하되, 그 시체는 산 위에 버리며, 그 시체를 가져가려면 소·말을 바쳐야 한다.(가부장적 사회, 일부다처제, 사유 재산 중시) +

[#부여:멸망]
==== (5) 멸망
3세기 말 선비족의 침략을 받아 크게 쇠퇴하였고, 4세기에는 전연의 침략으로 왕이 포로가 되기도 하였다. 물길(勿吉)의 위협을 받자 고구려에 투항하여 편입되었다(494).

[#부여:역사적의미]
==== (6) 부여의 역사적 의미
부여는 비록 연맹 왕국 단계에서 멸망하였지만, 고구려나 백제의 건국 세력이 부여의 한 계통임을 자처하였다는 점과 또 이들의 건국 신화도 같은 원형을 바탕으로 하고 있다는 점에서 역사적 의미는 매우 크다.

=== 2. 고구려

[#고구려:건국]
==== (1) 건국
<삼국사기>에 따르면 부여에서 남쪽으로 내려온 주몽이 고구려를 건국하였다고 한다(기원전 37). 주몽은 부여 지배 계급 내의 분열·대립 과정에서 박해를 피해 남하하여 독자적으로 고구려를 건국하였다.

[#고구려:수도의변천]
==== (2) 수도의 변천

① **초기**
고구려는 압록강의 지류인 동가강 유역의 졸본(환인) 지방에 자리잡았다. 이 지역은 산악 지대였기 때문에 농토가 부족하여 힘써 일해도 양식이 부족하였다. +
② **유리왕 이후**
건국 초기부터 주변 소국들을 정복하고 평야 지대로 진출을 꾀하였다.
유리왕 때 압록강가의 국내성(집안)으로 천도한 뒤 5부족 연맹을 토대로 발전하였다.

[#고구려:정복활동]
==== (3) 정복 활동
한의 군현을 공략하여 요동 지방으로 진출하였으며, 동쪽으로는 부전고원을 넘어 옥저를 정복하여 공물을 받았다. 정복 활동을 통해 지배층은 집집마다 부경이라는 창고를 가지고 피정복민에게서 획득한 곡식, 소금 등을 저장하였다.

[#고구려:정치조직]
==== (4) 정치 조직
① **5부족 연맹체**: 계루부(왕족), 절노부(왕비족), 소노부, 순노부, 관노부 등 5부족 연맹을 토대로 발전하였다. +
② 대가들의 존재: 초기 고구려도 부여와 마찬가지로 왕 아래에 상가, 고추가 등의 대가들이 있었으며, 각기 사자, 조의, 선인 등 관리를 거느리고 있었다. 즉 고구려도 초기에는 연맹체 국가적 성격을 띠었으며, 왕권도 미약하였다고 볼 수 있다. +
③ **제가(諸加) 회의**: 대가들이 모여 국가의 주요 사항을 결정하였다. 중대한 범죄자가 있으면 제가 회의를 통하여 사형에 처하고, 그 가족을 노비로 삼았다.

[#고구려:경제]
==== (5) 경제
산악 지대로 토지가 척박하여 약탈 경제에 의존하였다. 농업에 종사하는 평민인 하호(下戶)가 생산 활동을 담당하였으며 국가에 세금을 바쳤다.

[#고구려:사회모습][#고구려:사회]
==== (6) 사회 모습

① **신분**: 초기의 고구려는 왕·제가(부족장들)·호민(경제적으로 부유한 계층)이 지배층을 이루었고, 피지배층은 하호, 노비로 구성되었다. +
② **풍속**: 지배층 사이에 모계 사회의 유습인 ✚**서옥제**의 풍속과 형사취수제의 혼인 풍속이 있었다. 또한 법률이 엄격하여 큰 죄를 지으면 사형에 처하고 그 가족을 노비로 삼았다. +
③ **조상신 숭배**: 건국 시조인 주몽과 그 어머니 유화 부인을 조상신으로 제사를 지냈으며, 사직(社稷, 곡식 신)과 영성(靈星)에게도 제사를 지냈다. +
④ **제천 행사**: 10월에는 추수 감사제인 **동맹(東盟)**이라는 제천 행사를 성대하게 치르고, 아울러 왕과 신하들이 국동대혈에 모여 함께 제사를 지냈다. +
⑤ **장례 풍속**: 장례를 금·은 재물을 쓰며 후하게 치렀고, 돌을 쌓아 봉분을 만들고 주변에 소나무와 잣나무를 많이 심었다. 사람이 죽으면 집안에서 일정 기간 상을 치르고
장사를 지냈는데, 부모와 남편은 3년상을 치렀다.

=== 3 옥저

[#옥저:위치]
==== (1) 위치
함경남도 북부에서 두만강 유역 일대에 걸쳐 있었다. 함경산맥과 태백산맥 등 높은 산
이 남북으로 펼쳐져 있어서 외부의 영향이 적었으며, 상대적으로 국가 발전 단계도 늦
었다. 또한 고구려의 압력과 수탈로 크게 성장하지 못하였다.

[#옥저:정치]
==== (2) 정치
읍군 또는 삼로라고 불린 군장이 자기 부족을 통치하였고, 통합된 큰 정치 세력
(연맹 왕국)을 형성하지 못하였다. 소와 말이 적어 전쟁 때에는 보병 위주로 창을 갖고
전투를 치렀다.

[#옥저:경제]
==== (3) 경제
어물과 소금 등 해산물이 풍부하였고, 토지가 비옥하여 농사가 잘 되었다. 그러나고 구
려의 수탈에 시달려 소금, 어물 등을 공납으로 바치고 미인을 상납하였다.

[#옥저:풍습]
==== (4) 풍속
① **민며느리제**: 고구려와 같이 부여족의 한 갈래였으나 풍속이 달랐는데, 혼인 풍속으로 민며느리제가 있었다. 민며느리제는 일종의 매매혼으로, 혼인할 어린 여자아이를 남자 집에다 데려다 키우다가 그 아이가 성장하면 남자가 여자 집에 재물을 주고 신부로 맞는 결혼 형태였다. +
② **가족 공동묘제**: 골장제(세골장)라고도 하는데, 가족이 죽으면 시체를 가매장하였다가 나중에 그 뼈를 추려서 가족 공동 무덤인 커다란 목곽에 안치하였다. 또 목곽 입구에는 죽은 자의 양식으로 쌀을 담은 항아리를 매달아 놓기도 하였다.

=== 4 동예

[#동예:위치]
==== (1) 위치
함경남도 원산·안변 일대에서 경상북도 영덕에 이르는 동해안 지대 및 강원도 중부 이북 내륙 지대에 걸쳐 있었다. 동해안에 치우쳐 있어서 선진 철기 문화의 수용이 그만큼 늦었다. 그리하여 일찍부터 고구려의 압력을 받아 큰 정치 세력을 형성하지 못하다가 훗날 흡수되었다.

[#동예:정치]
==== (2) 정치
옥저와 마찬가지로 읍군, 삼로라 불리는 군장이 있었으나 이를 통합한 왕권은 형성되지 않았다.

[#동예:경제]
==== (3) 경제
토지가 비옥하고 해산물이 풍부하여 경제생활이 윤택하였다. 특히 명주와 삼베를 짜는 기술이 발달하였다. 특산물로는 단궁이라는 활과 일종의 조랑말인 과하마, 바다표범의 가죽인 반어피 등이 유명하였다.

[#동예:풍속]
==== (4) 풍속: 질병으로 사람이 죽으면 살던 집을 폐기하였다.

① **족외혼**: 씨족 사회의 전통인 족외혼(族外婚)을 엄격하게 지켰다. +
② **책화**: 각 씨족의 영역을 함부로 침범하지 못하게 하였다. 만약 다른 씨족의 생활권을 침범하면 책화라 하여 노비나 소, 말로 변상하게 하였다. +
③ **제천 행사**: 매년 10월에 무천(舞天)이라는 제천 행사를 열었다.
④ **호신 숭배 제사**: 호랑이를 산신으로 숭배하였으며, 사회 내부의 결속과 규범을 유지하는 역할을 하였다.

=== 5 삼한

[#삼한:성립]
==== (1) 성립
① **진(辰)의 성장**: 고조선과 같은 시기에 한반도 남부에는 일찍부터 진(辰)이 성장하고 있었다. 진은 기원전 2세기경 고조선의 방해로 중국과의 교통이 저지되기도 하였다. +
② **삼한의 성립**: 고조선 사회의 변동에 따라 유이민이 대거 남하하였다. 이와 함께 철기문화가 유입되고 토착민의 청동기 문화와 융합되면서 사회가 더욱 발전하였다. 그리하여 마한, 변한, 진한의 연맹체들이 나타났다 +

[#삼한:발전]
==== (2) 발전
① **마한**: 천안·익산·나주 지역을 중심으로 하여 경기·충청·전라도 지방에서 발전하였다. 마한은 54개의 소국으로 이루어졌고 모두 10여만 호였으며, 그 중에서 큰 나라는 1만여 호, 작은 나라는 수천 호였다. 이들 소국 중에서 중심국은 **목지국**이었다. +
② **변한**: 김해·마산 지역을 중심으로 발전하였고, 12개국의 소국으로 구성되었다. 이들 소국 중에서 중심국은 구야국이었다. +
③ **진한**: 진한은 대구·경주 지역을 중심으로 발전하였으며, 12개국의 소국으로 구성되었다. 이들 소국 중에서 중심국은 사로국이었다.

[#삼한:정치]
==== (3) 정치
삼한 중에서 마한의 세력이 가장 컸으며, 마한을 이루고 있는 소국의 하나인 목지국의 지배자가 마한왕 또는 진왕으로 추대되어 삼한 전체를 주도하였고, 중국과도 교류하였다. 삼한의 지배자 중 세력이 큰 군장은 신지, 견지 등으로, 작은 군장은 부례, 읍차 등으로 불렸다

[#삼한:제정의분리]
==== (4) 제정의 분리
① **천군의 존재**: 삼한에는 신지·읍차 등의 군장과 별도로 제사장인 천군(天君)이 존재하였다. 천군은 신성 지역인 소도(蘇塗)에서 농경과 종교에 대한 의례를 주관하였다. 제정 분리를 통해 정치권력과 종교적 권위가 분리되었음을 알 수 있다. +
② **소도의 역할**: 소도는 군장의 세력이 미치지 못하는 곳으로, 죄인이라도 도망하여 이곳에 숨으면 잡아가지 못하였다. 철기 문화를 가진 이주민 세력이 정치권력을 장악
하는 가운데, 토착 세력의 문화와 신앙도 완전히 사라지지 않은 상황에서 소도가 두
문화 사이의 완충 지대로 역할을 했을 것으로 추정된다.

[#삼한:경제]
==== (5) 경제
① 농경의 발달::
* 벼농사의 발달: 삼한 사회는 철기 문화를 바탕으로 하는 농경 사회였다. 철제 농기구의 사용으로 농경이 발달하였고 벼농사를 지었다. +
* 저수지의 축조: 벼농사의 발달에 따라 수로, 보, 저수지 등이 축조되었는데, 김제벽골제, 밀양 수산제, 제천 의림지, 상주 공검지 등의 저수지가 대표적이다. +
② **철의 생산**: 삼한 중에서 특히 변한에서 철이 많이 생산되어 낙랑, 왜 등에 수출하였다. 당시 철은 교역에서 화폐처럼 사용되기도 하였다. +
③ 누에치기(양잠)를 하고 뽕나무를 가꾸어 명주와 베를 만들고 그것으로 옷을 지어 입었다.

[#삼한:사회]
==== (6) 사회
① **주거지**: 삼한 지역의 사람들은 초가지붕의 반움집이나 귀틀집에서 살았다. +
② **두레**: 삼한은 평야 지대에 위치해 있어 다른 나라에 비해 농업이 발달하였는데, 두레라는 공동 노동 조직을 통하여 농사일을 비롯한 여러 가지 작업을 하였다. 이는 신석기 시대의 씨족 공동 노동 풍습의 영향이 남은 것으로 볼 수 있다. +
③ **제천 행사**: 해마다 씨를 뿌리고 난 뒤인 5월에 수릿날(단오)과 곡식을 거두어들이는 10월에 계절제(상달)를 열어 하늘에 제사를 지내, 농경에 기반한 사회임을 알 수 있다. 이러한 제천 행사 때에는 온 나라 사람들이 모두 모여서 날마다 음식과 술을 마련하여 노래를 부르고 춤을 추며 즐겼다. +

[#삼한:사회변동]
==== (7) 사회 변동
① **배경**: 철기 시대 후기의 문화 발전은 삼한 사회의 변동을 가져왔다. +
② **내용**: 지금의 한강 유역에서는 백제국이 성장하면서 마한 지역을 통합해 갔다. 또 낙동강 유역에서는 구야국이, 그 동쪽에서는 사로국이 성장하여 중앙 집권 국가의 기반을 마련하면서 각각 가야 연맹체와 신라의 기틀을 다져 나갔다.

* link:#부여:건국[부여의 건국]

link:#부여:정치[부여의 정치]

link:#고구려:사회[고구려 사회]