= 13 문벌 귀족 사회의 성립과 동요

== 1 고려의 성립

=== 1 고려의 건국과 민족의 재통일

===== (1) 고려 건국과 후삼국 통일
① 건국：궁예를 몰아낸 뒤 신하들의 추대를 받아 왕위에 오른 왕건은 고구려를 계승한다는 의미에서 국호를 ‘고려’로 바꾸고, 연호를 ‘천수’라고 하였다(918). 그리고 자신의 세력 근거지였던 송악으로 도읍을 옮겼다.

② 후삼국 통일：고려를 세운 왕건은 안으로는 지방 세력을 흡수·통합하고, 밖으로는 중국의 5대 여러 나라와 외교 관계를 맺어 대외 관계의 안정을 꾀하였다.

* 신라 흡수(935)：태조는 궁예와 달리 신라에 대하여 적극적인 우호 정책을 내세워, 후백제가 신라를 공격하자 신라를 도왔다. 이로 인해 신라인의 신망을 얻었고 신라 경순왕의 항복을 받아 전쟁 없이 신라를 통합하였다.
* 후백제 통합(936)：왕위 계승 문제로 아들 신검에 의해 금산사에 유폐되었던 후백
제의 견훤이 고려에 귀순하였으며, 고려는 신검 군대와의 전투에서 승리하여 후삼
국을 통일하였다(936).

==== (2) 민족의 재통일
발해가 거란에 멸망(926)당했을 때 고구려계 유민을 비롯하여 많은 사람이 고려로 망명해 왔다. 태조는 이들을 우대하여 민족의 완전한 통합을 꾀하였다. 이로써 고려는 후삼국뿐만 아니라, 발해의 고구려계 유민까지 포함한 민족의 재통일을 이룩하였다.

==== (3) 후삼국 통일의 역사적 한계
고구려의 영토를 수복하지 못한 영토상의 한계와 삼국의 분열 의식이 남아 있었다는 점에서 정신적 한계가 있다.

==== (4) 후삼국 통일의 역사적 의의
외세의 개입 없이 민족 내부의 역량으로 이룬 민족 통일로, 이 과정에서 강력한 민족 의식이 형성되어 독자적 민족 문화를 꽃피우게 되었다. 또한 고려의 후삼국 통일은 단순한 왕조의 교체를 의미하는 것이 아니라, 고대 사회에서 중세 사회로의 전환을 의미한다. 고려는 정치적·문화적·사상적으로 신라 사회에 비하여 질적으로 변화·발전된 사회이
기 때문이다.

=== 2. 태조(재위 918~943)의 정책
==== (1) 민생 안정 노력
* 조세 수취 완화：✚취민유도를 내세워 호족이 지나치게 세금을 높게 거두지 못하도록
하고, 조세를 합리적으로 조정하여 세율을 1/10로 낮추었다.
* 흑창 설치：빈민 구제 기관인 흑창을 설치하였다.

==== (2) 정치 개혁
* 정치 제도 정비：태조는 태봉의 관제를 중심으로 신라와 중국의 제도를 참고하여 통
치 제도를 마련하였다.
* 호족 통합과 견제：개국 공신과 지방의 호족을 관리로 등용하였고, 인품과 공로를 기준
으로 역분전을 지급하였으며, 이들에게 왕씨 성을 주는 ✚사성 정책을 시행하여 유대를
강화하였다. 정주 유씨, 충주 유씨 등 유력한 호족과는 혼인을 통하여 관계를 깊게 다졌
다. 또 본관제를 마련하였고, 지방 호족을 견제하고 지방 통치를 보완하기 위하여사 심
관 제도와 기인 제도를 활용하였다.

사심관 제도:: 
신라왕 김부가 항복해 오자 김부를 경주의 사심관으로 삼은 것에서 기
원하였다. 중앙의 관리를 출신 지역의 사심관으로 임명하여 부호장 이하의 관직 등
에 관한 사무를 담당하게 하였는데, 개경에 거주하는 호족 출신 공신들을 통해 출신
지역을 통제하고자 한 것이다.

기인 제도::
신라의 상수리 제도를 계승한 것으로, 지방 호족 세력의 자제를 인질로
삼아 개경에 머물도록 한 것이다.

* <정계>·<✚계백료서>：태조는 <정계>와 <계백료서>를 지어 관리가 지켜야 할 규범을 제
시하였는데, 현재 전하지 않는다.
④ 훈요 10조：태조는 후대 왕들이 지켜야 할 정책 방향을 제시한 훈요 10조를 남겼다.
훈요 10조에는 당시 성행하던 불교, 풍수지리설, 도참사상 등이 반영되어 있다.

==== (3) 북진 정책
* 서경 중시：태조는 고구려의 옛 땅을 되찾고자 하는 의욕으로 강력한 북진 정책을 추
진하여 평양을 서경으로 삼고, 북진 정책의 전진 기지로 적극 개발하였다. 그 결과 청천강
에서 영흥에 이르는 국경선을 확보할 수 있었다.
* 거란에 대한 강경책：거란과 국교를 단절하였고, 만부교 사건이 일어나기도 하였다.

발해 유민 적극 포섭::
발해가 망하자 지배 계층 수만 호가 고려로 넘어왔는데, 고려는 이들에게 관직과
토지 및 가옥을 주었고, 관리, 장군, 학자 등의 유민들을 적재적소에 임명하여 후
삼국 통일에 활용하였다. 발해의 태자 대광현에게 왕계라는 성명을 주고 왕족으로 대우하였다.

=== 3. 광종의 왕권 강화

==== (1) 왕권의 불안정
태조의 뒤를 이은 혜종과 정종 때에는 왕권이 불안정하였다. 혜종 때에는 왕위 계승을
둘러싸고 왕규의 난이 일어났는데, 이는 왕실과 호족 세력, 그리고 호족 출신의 외척이
서로 얽혀 일어난 정변이었다.

혜종(재위 943~945)::
외가인 나주 오씨의 세력이 약했으므로 왕권이 불안정하였다. 태조의 명을 받은 박술희가 보좌했으나, 정종 즉위 후 박술희도 죽임을 당했다.

정종(재위 945~949)::
947년 이후 서경 천도를 계획했으나 개경 세력의 반발로 실패하였다. 거란에 대한 대비와 왕권 강화를 목적으로 광군사를 설치하여 광군을 통할하였다. 또한, 불법을 배우는 사람들을 위한 일종의 장학 재단인 광학보를 설치하였다.

==== (2) 광종(재위 949~975)의 정책
왕권의 안정과 중앙 집권 체제의 확립을 위해 여러 정책을 추진하였다.

* 주현공부법(949)：주현의 세공액을 정하여 국가 재정을 확대하고 지방 호족 세력을 통제하였다.
* ✚노비안검법(956)：왕권이 불안정한 상황에서 즉위한 광종은 후삼국 시대의 혼란기에 불법으로 노비가 된 자를 조사하여 양인으로 해방시켜 주기 위한 노비안검법을 실시하여 호족의 세력을 약화시키고 국가의 수입 기반을 확대하였다.

③ 과거제 시행(958)：광종은 중국 후주에서 귀화한 쌍기의 건의를 받아들여 과거제를 시행하였다. 이를 통해 유교의 학식과 능력을 갖춘 신진 인사를 등용하고 신구 세력의 교체를 도모하였다. 또한 승과 제도도 시행하였다.

④ 공복 제정(960)：광종은 지배층의 위계질서와 관리의 기강을 확립하기 위하여 자색·단색·비색·녹색으로 나누는 백관의 공복(公服)을 제정하였다. 공복이 제정되었다는 것은 광종을 중심으로 하는 새로운 관료 체제가 마련되었음을 의미한다.

⑤ 불교 통합：귀법사의 균여를 우대하고, 중국에서 천태종·법안종 등을 들여와 불교계를 통합하려 하였다. 중국에 36명의 승려를 파견하여 법안종을 배우도록 하였으며, 제관과 의통을 파견하여 천태학에 대한 관심을 보였다. 한편 개경 주위에 사찰을 세워 불교 세력을 통해 호족을 견제하려 하였으며, 국사·왕사 제도를 완성하였다.
⑥ 제위보 설치(963)：광종은 제위보를 설치하여 빈민·행려의 구호와 질병을 맡아보도록 하였다. 보는 기금을 마련하여 그 이자를 가지고 사업을 하는 재단이었다.
⑦ 왕권 강화：일련의 개혁을 통하여 자신감을 가지게 된 광종은 본격적으로 공신과 호
족 세력을 제거하여 왕권을 강화하였다. 국왕의 권위를 높이기 위하여 황제를 칭하
고, ‘광덕’·‘준풍’ 등 독자적인 연호를 사용하였다(칭제건원). 또한 개경을 황도(皇都)로, 서경
을 서도(西道)로 부르게 하였다. 이로써 왕조 성립 초기에 기세를 누리던 공신과 호족
의 세력이 크게 약화되고 왕권이 강화될 수 있었다.
⑧ 송과의 수교(962)：후주의 뒤를 이어 송이 건국(960)되자 광종은 송과 수교하였는데,
이후 송의 연호를 사용하였다.

4 경종(재위 975~981)의 정책
(1) 공신들의 반동 정치
한때 복수법을 실행하여 사적인 복수를 허용했는데, 이때 광종 때 개혁 정치의 주역들
이 다수 제거되었다.
(2) 시정 전시과 실시(976)
국가적 규모로 모든 관리에게 수조지를 차등 지급하였다. 이는 호족을 통제할 수 있었
음을 보여 주는 것이다. 문반과 무반이라는 용어가 시정 전시과의 규정에서 처음 기록
되었다.
(3) 고리대 제한：이자율을 연 1/3로 제한하여 농민의 몰락을 방지하였다.
5 성종(재위 981~997)의 정책
(1) 유교 정치의 실현
① 유교 정치 모색：성종 때에는 신라 6두품 출신의 유학자들이 국정을 주도하면서 유교
정치를 실현하고자 하였다. 성종은 즉위 후 국가의 오랜 폐단을 없애고 국정을 쇄신하
기 위하여 중앙의 5품 이상의 관리들로 하여금 그동안의 정치에 대한 비판과 정책을
건의하는 글을 올리게 하였다. 대표적으로 김심언의 ✚봉사 2조와 최승로의 시무 28
조가 있다.
② 최승로
* 시무 28조를 올려 유교를 진흥하고, 과도한 재정 낭비를 가져오는 불교 행사를 억제
할 것을 건의하였다. 성종은 최승로의 건의를 수용하여 통치 체제를 정비하였으
며, 연등회와 팔관회를 일시적으로 폐지하였다.
* 5조정적평에서 태조로부터 경종에 이르는 5대 왕의 치적에 대한 잘잘못을 평가하
여 교훈으로 삼도록 하였다.

5조정적평에서 최승로는 광종에 대하여 심하게 비판적인 자세를 취했는데, 이는 전제 왕권을
배척하는 귀족 중심의 유교적 이념의 일단을 보여 준다는 점에서 주목된다.

(2) 관제의 정비
① 지방 제도 정비：성종은 12목에 지방관(목사)을 파견하고, 호장·부호장 등의 향리 제도
를 마련하여 지방 세력을 견제하였다(983).
② 교육 기관 정비
* 국자감을 정비하고, 12목에 경학박사와 의학박사를 파견하였으며, 주·군에 향학
(향교)을 세워 유학 교육의 진흥에 노력하였다.
* 과거 제도를 정비하고 과거 출신자들을 우대하여 유학에 조예가 깊은 인재들의 적
극적인 정치 참여를 유도하였다.
* 비서성[개경, 경적(經籍)과 축문(祝文) 작성에 관한 일을 담당하던 관청], 수서원
(서경, 일종의 도서관)을 설치하였고, 관리들에게 매달 시를 짓도록 하였다( ✚문신
월과법). 교육 조서를 반포하였다.
③ 중앙 관제：태봉의 관제 및 당·송의 관제를 참작하여 2성 6부제를 중심으로 하는 중앙
관제를 새로 마련하였다.
④ 문산계(중앙의 문·무관)와 무산계(향리, 귀화한 여진 추장, 악인, 공장, 노병, 탐라
왕족)를 도입하여 귀족적인 성격의 중앙 집권화를 꾀하였다.
(3) 대외 관계
거란의 1차 침입(993)을 받았으나, 서희의 활약으로 오히려 강동 6주를 확보하였다.
(4) 사회 정책
① 노비환천법：귀족 사회의 기강 확립을 위해 해방된 노비가 원주인에게 불손한 행동을
하면 노비로 되돌리는 법으로, 철저히 유교사상에 기반한 것이다.
② 애민 정책
* 의창과 상평창 설치：태조가 설치한 흑창을 의창으로 바꾸고 지방 주군에까지 확대
하였으며, 개경·서경·12목에 상평창을 설치해 물가 조절의 기능을 맡게 하였다.
* ✚재면법 시행：재해로 인한 전답의 피해 면적이 4할이면 조, 6할이면 조·포, 7할이
면 조·포·역을 면제해 주었다.
③ 고리대 제한：고리대를 제한하기 위한 것으로, 원금과 이자가 같은 액수에 달하면 그
이상의 이자는 금지하였다(자모정식).
④ 기타：건원중보(최초의 철전)를 발행하고, 호족의 무기로 농기구를 제작하였다.
6 현종의 체제 정비
(1) 목종(재위 997~1009)
개정 전시과를 실시(998)하고 학문을 장려하였으나, 어머니인 천추태후와 김치양이 전
횡하였다. 강조가 정변(1009)을 일으켜 목종을 죽이고 현종을 즉위시켰다.
(2) 현종(재위 1009~1031)
① 거란의 침입：즉위 초 강조의 정변을 구실로 거란의 2차 침입(1010)이 있자 나주까지
피난을 갔다. 또한 1018년에 거란의 3차 침입이 있었으나 강감찬의 귀주 대첩(1019)
으로 이를 막아냈다.

② 향리 제도 정비：군현의 정(丁) 수를 고려하여 향리의 정원을 정하고(향리 정원제), 향
리 공복제를 시행하여 향리의 공복을 규격화하였다. 한편 향리 자제의 과거 응시 자
격도 군현의 크기에 따라 조정하는 주현공거법을 제정하였다.
③ 지방 제도 정비：종래의 절도사제를 폐지하고, 5도 양계, 4도호부, 8목의 지방 제도를
마련하였다. 개경을 5부 35방 344리로 구획하였다.
④ 문화 정책
* 불교 진흥：개경에 현화사를 건립하고, 성종 때 폐지되었던 연등회와 팔관회를 부
활시켰으며, 거란의 침입을 물리치고자 초조대장경을 간행하였다.
* 역사서 편찬과 유교 진흥：<7대실록>의 편찬을 시작하고, 최치원과 설총을 문묘에 종
사하여 최초로 우리나라 학자를 문묘에 배향하였다.
⑤ 경제 정책：농상을 권장하고 말을 사육하는 감목양마법을 시행하였으며, 조세의 균등
을 꾀했다. 의창을 각지에 확대하는 주창수렴법을 제정하였다.
⑥ 민생 안정책：70세 이상의 노부모가 생존해 있을 경우 군역을 면제하거나 변경으로 발
령되지 않도록 하는 면군급고법을 실시하였다.
7 문종 이후 고려의 전성기
(1) 덕종(재위 1031~1034)
<7대실록>이 완성되었으며, 지방 인재에게도 응시 자격을 주는 국자감시를 시행하였
다. 천리장성을 축조하기 시작하였다.
(2) 정종(재위 1034~1046)
천리장성을 완공하였다. 노비종모법을 부활시키고, 5역·5천·향·부곡인 및 악공과 잡
류의 자손이 과거에 응시하는 것을 금지하였으며, 장자상속법을 제정하였다.
(3) 문종(재위 1046~1083)
① 조세 정책：공음전시법을 시행한 뒤, 현직 관료에게만 수조권을 지급하는 경정 전시과
를 시행하였다(1076). ✚답험손실법과 재면법을 법제화하여 재해시 피해 면적에 따라
조·포·역을 감면해 주었다. 양전보수법으로 세금을 거두는 결의 면적을 확정하였
고, 토지를 품질에 따라 상·중·하로 나누는 3등전품제를 도입하였다.
② 사회 정책：동·서 대비원의 체계를 정비하여 개경 평민의 질병을 치료하도록 하였
다. 사형수를 세 번 재판하는 삼복제와 죄수 심문에 3명 이상의 형관이 입회하는 삼
원신수법을 제정하였다.
③ 왕권 강화 정책：선상기인법으로 기인 제도를 법제화하고, 양주에 남경을 설치하였다.
④ 불교 정책：개성 근처에 흥왕사를 창건하였는데, 의천은 흥왕사의 제1대 주지였다. 의
천은 숙종 때 흥왕사에 교장도감을 설치하고 교장을 간행하였다.
⑤ 교육 정책：과거 시험지에 응시자의 이름을 가리는 봉미법이 제정되고, 국자감 학생
의 재학 연한을 9년(유학부)으로 제한하였다. 한편, 문종 때에는 최충의 문헌공도를
비롯하여 사학 12도가 융성하였다.
⑥ 외교：송과 다시 국교를 맺고 거란과 송 사이에서 균형추 역할을 하였다.


== 2 통치 체제의 정비
=== 1. 중앙 정치 조직

==== (1) 정비 과정
① 초기：태조는 태봉의 광평성을 위시하여 그 관제를 일
부 답습하고, 후삼국 통일 후에는 신라의 것을 절충
하고 당의 관제도 일부 수용하였다.
② 고려의 통치 체제 정비：성종 때 마련한 2성 6부제를 토대
로 하였다. 고려는 당·송의 제도를 받아들이면서도
고려의 실정에 맞게 이를 조정하였다.

당의 영향::
• 2성 6부：당의 3성 6부와 달리 중서성과 문하성을 합쳐서 운영 +
• 2속사(이부의 고공사와 형부의 도관)를 둠. +
• 중서성의 최고 관직(중서령)은 명예직으로 그치고 문하시중이 수상의 역할을 함.

송의 영향::
• 중추원：송의 추밀원(비서 기관)을 본떠 설치  조선의 승정원으로 계승 +
• 삼사：송의 삼사를 본떠 설치, 송과 달리 단순한 출납 회계 기능으로 운영 +

독자적 기구:: 
도병마사(군사), 식목도감(법제)  고관의 회의 기구(합좌 기구)로 운영 +

==== (2) 중앙 정치 조직
① 2성 6부：최고 관서로서 중서문하성을 두었고, 그 장관인 문하시중이 국정을 총괄하였다. 상서성은 실제 정무를 나누어 담당하는 6부를 두고 정책의 집행을 담당하였다.

* 2성

중서문하성::
• 문하성의 장관인 문하시중(종1품)이 국정 총괄, 중서성의 장관인 중서령(종1품)은
명예직임. 종2품 이상의 재신과 정3품 이하의 낭사로 구성 +
• 재신: 종2품 이상으로 중추원의 추밀과 함께 도병마사·식목도감에 참여. 상서성 6부의 판사(장관) 겸임
• 낭사: 정3품 이하로 어사대 관원과 함께 대간(臺諫) 역할 담당

상서성::
• 정책 집행 담당
• 장관인 상서령(종1품)은 명예직임.
• 상서도성과 6부로 구성 → 실제 정무 담당

* 6부：실제 행정 집행을 담당하였다. 장관은 판사(判事)로 중서문하성의 재신이 겸
임하여, 상서성은 중서문하성에 예속되어 운영되었다. 6부의 상서(정3품)는 중추
원의 추밀이 겸임하는 경우가 많았다.

6부::
이부: 문관의 인사, 공훈 +
병부: 무관의 인사, 국방, 우역(郵驛) +
호부: 호구, 공부(貢賦), 전곡(錢穀) +
형부: 법률, 소송, 노비 +
예부: 예의, 제사, 외교, 교육, 과거 + 
공부: 공장, 산택, 영조(營造), 토목 +


② 중추원：중서문하성과 더불어 중앙 최고의 관부로 군사 기밀과 왕명의 출납, 왕실 숙
위를 담당하였다. 군사 기밀을 담당하면서 중서문하성의 재신과 함께 국정을 총괄하는
추밀과 왕명의 출납을 담당하는 3품의 승선으로 구성되었다.

추밀
• 종2품 판원사, 지원사, 동지원사 등과 정3품 부사, 첨서원사, 직학사로 구성
• 군국 기무와 군사 기밀 담당, 도병마사에 참여
• 대체로 6부의 상서직 겸임

승선
• 정3품 지주사, 좌우승선, 좌우부승선 등
• 왕명 출납과 궁궐 숙위 담당

③ 도병마사와 식목도감
* 특징：중서문하성의 재신과 중추원의 추밀이 함께 모여 회의로 국가의 중요한 일을 결정
하는 곳으로, 고려 귀족 정치의 독자성을 보여 주는 관청이다.
* 도병마사：대외적인 국방·군사 관계를 관장하였다. 도병마사는 고려 후기에 도평
의사사(도당)로 명칭이 바뀌었으며, 그 기능도 확대되어 군사 문제를 회의하는 기
구에서 국가의 모든 중대사에 관여하는 중앙 최고 기구가 되었다.
* 식목도감：대내적인 법제·격식 문제를 다루었다.
* 재신과 추밀：6부를 비롯한 주요 관부의 최고직을 겸하여 중앙의 정치 운영에서 가
장 핵심적인 위치를 차지하였다.
④ 어사대：성종 14년(995)에 설치하여, 정치의 잘잘못을 논하고 관리의 비리를 감찰하는
임무를 맡았다.
⑤ 대간：어사대의 관원은 중서문하성의 낭사와 함께 대간으로 불렸다. 대간은 비록 직위는
낮았지만, 왕을 보좌하면서 언관(言官)의 기능을 수행하여 국가의 여러 사무에 관여
하였으므로 정치적 비중이 적지 않았다. 대간은 왕의 잘못을 논하는 간쟁, 잘못된 왕
명을 시행하지 않고 되돌려 보내는 봉박, 관리 임명이나 법령의 개폐에 동의하는 서경
의 권한을 통해 왕이나 고위 관리의 활동을 지원하거나 제약하여 정치 운영에 견제와
균형을 이루었는데, 오늘날 언론 기관과 유사한 역할을 하였다.

⑥ 삼사：송의 삼사와는 달리 단순히 화폐와 곡식의 출납에 대한 회계만 맡았다. 한편, 고려
중앙 관제의 근간은 당의 제도를 수용한 2성 6부 체제로 호부에서 재정을 담당하였
다. 이와 같은 이원적 운영은 지방 세력이 강하여 일원적 재정 체계를 세울 정도로 조
세와 재정의 양이 많지 않았기 때문인 것으로 보인다.
⑦ 문서와 서적을 다루는 관청
문한직：한림원, 춘추관,비서성, 보문각 => 음서 출신자는 등용되지 않았음.

한림원
• 왕의 교서, 외교 문서 등을 작성
• 문장과 학식이 뛰어난 과거 급제자로 구성
• 과거의 고시관이나 경연관 겸직

춘추관 시정의 기록 담당

비서성 
경적이나 축문에 관한 사무 담당

보문각
• 경연과 장서 담당
• 예종 때 궁궐 내에 설치한 청연각을 보완

⑧ 기타 관청
* 사천대：천문 관측을 담당하였으며 조선 시대의 관상감으로 계승되었다. 천문 관
측 외 역법(曆法)·측후(測候, 기상 관측)·각루(刻漏, 물시계) 등의 일도 관장하였다.
* 태의감：왕실의 의약(醫藥)과 질병의 치료를 담당하였으며 조선 시대의 전의감으
로 계승되었다.
* 통문관：외국어 교육과 통역을 담당하였으며 조선의 사역원으로 계승되었다.
(3) 고려 시대의 관직 체계
① 관제의 정비：태조가 개국한 직후에는 신라와 태봉의 제도를 사용하였다. 이후 광종
때 몇몇 제도를 마련하고, 성종 때 고려 나름대로의 관제를 정비하였다. 성종 때 문
산계와 무산계를 도입했으나, 중국와 달리 문산계가 문무 양반을 가리켰고, 무산계
는 귀화한 여진의 추장이나 향리, 탐라 왕족, 공장 등을 관할하는 제도였다.
② 관직의 구분：관직은 정·종 1품에서 9품까지 18단계로 구분되었다.
* 문·무 양반의 품관은 다시 재추직, 참상직, 참하직 등으로 구분되었다.
* 품관 밑에는 품 외의 이속직(吏屬職)이 설치되었다. 이속직을 맡은 서리는 입사직(入
仕職)인 주사(主事)·녹사(錄事)·영사(令史)·사(史) 등과 미입사직(未入仕職)인 장고
(掌固), 주선(注膳) 등이 있었다. 입사직은 권무직이나 동정직을 거쳐 품관으로 진입
할 수 있었다. 미입사직도 승진을 거쳐 품관이 될 수 있었으나 잡류는 제외되었다


* 궁중의 잡무를 보는 남반은 초기에 4품관까지 있었으나, 현종 때 최고 관직이 7품
으로 제한되었다.
③ 실직과 산직
* 의미：관직에는 실제 직임을 맡는 실직과 관계만이 수여되는 산직(散職)이 있었다.
* 산직의 종류：산직은 다시 위계에 따라 문관 5품, 무관 4품 이상의 검교직과 그 이
하에게 주는 동정직으로 나뉘었다. 관직 체계로의 편입뿐 아니라, 명예나 포상의
의미로도 많이 활용되어 실직과 동정직을 함께 가지는 경우도 있었다. 특히 동정
직은 관직에 처음 나갈 때 받는 직임으로 실직에 나가기 위한 일종의 대기 기간 역
할을 하기도 하였다.
④ 첨설직：고려 후기 공민왕 때 홍건적과 왜구의 격퇴 과정에서 군공을 세운 자에게 포
상으로 첨설직을 만들어 수여하였다.

2 지방 행정 조직
(1) 지방 행정 조직의 정비
① 태조~경종：지방 호족의 자치권을 인정하는 가운데, 양전(양전사)과 조세 징수(조
장·금유) 및 운송(전운사) 등을 위해 관리를 파견하였다.
② 성종：최승로의 건의를 받아들여 지방 제도를 정비하기 시작하였다. 12목을 설치하고
지방관을 파견하면서 10도제를 마련하고 양계에 병마사를 파견하였다.
③ 현종：전국을 5도와 양계, 경기로 크게 나누고, 그 안에 3경, 4도호부, 8목을 비롯하여
군·현·진 등을 설치하였다.
④ 예종：5도에 안찰사를 파견하고 속현에도 감무(監務)를 파견하기 시작하였다.
(2) 지방 행정 조직
① 경기：성종 때 개성 인근의 현을 개경부에 편입시켜 경관인 개성 부윤이 다스리도록
하였다. 현종 때 개성부를 폐지하고 경중 5부를 따로 중앙 정부에 직속하게 하였고,
그 외곽인 경기 지역은 지방관이 다스리도록 하였다. 문종 때 개성부가 부활되었으
나 이때는 지방관의 성격이 되었다.

② 5도：양광도, 경상도, 전라도, 서해도, 교주도

* 안찰사 파견：5도에는 상설 행정 기관이 설치되지 않았으며, 임기 6개월의 안찰사가 도내를
순찰하며 수령을 감찰하고 민생과 군사의 업무
를 담당하였다.
* 주·군·현 설치：5도 아래 주·군·현을 설치하
고 주·군에는 자사, 현에는 현령을 파견하였다.
수령을 파견할 때 향리와 비슷한 역할을 하는
보좌원으로 속관을 함께 파견하여 행정 장악력
을 높이고자 하였다. 그러나 수령이 파견된 주현
보다 수령이 파견되지 않은 속현이 더 많았다.
③ 3경：3경은 풍수지리설과 관계 있는 것으로 처음
에는 개경(개성), 서경(평양, 태조), 동경(경주, 성종)을 중시하여 3경이라 불렀으나
뒤에는 동경이 남경(서울, 문종)으로 바뀌었다. 3경에는 지방관인 유수(留守)를 파견
하였다. 서경을 중시하여 서경에는 중앙 부서의 분소(分所)를 두었다(✚분사 제도).

④ 8목, 4도호부：8목은 지방 행정의 중심지, 도호부는 군사적 요충지에 설치되었다. 도호
부의 수는 군사적 필요에 따라 4, 5, 3도호부로 변경되기도 하였다.
⑤ 양계：외적이 침입하기 쉬운 국경 지대에 설치된 군사 행정 구역으로, 동계와 북계로
이루어졌다. 병마사를 파견하여 다스렸는데, 임기는 6개월이었다. 한편, 국방상의 요
충지에는 군사적인 특수 지역으로 진을 설치하였다.
⑥ 촌：말단 행정 구역으로 몇 개의 자연촌을 묶은 지역촌을 하나의 단위로 보았다. 이
는 자연촌에 기초한 신라와 조선 시대 면리제 사이의 과도기로 볼 수 있다.
(3) 지방관 파견
① 파견 범위：중앙에서 지방관이 직접 파견되는 것은 군·현과 진까지였다.
② 특징：지방관이 파견된 ✚주현(主縣)보다 파견되지 않은 ✚속현(屬縣)이 더 많았다. 속현
과 향·부곡·소 등 특수 행정 구역은 주현을 통하여 간접적으로 중앙 정부의 통제를
받고 있었다. 조세나 공물의 징수와 노역 징발 등 실제적인 행정 사무는 호장·부호장 등
향리가 담당하였다.

(4) 특수 행정 조직：군현과는 별도로 향·부곡·소 등 특수 행정 구역을 두었다. 이곳의 주
민은 양민이면서 군현민과 구별되어 차별을 받았다. 향·부곡에 거주하는 사람은 농업에,
소에 거주하는 사람은 수공업과 광업에 종사하였다.
(5) 향리：고려의 향리는 지방 사회의 실질적 지배층이었다. 각 군·현에는 그곳 출신 호
장·부호장 등의 향리가 수령 밑에서 직접 백성을 다스렸다. 원래 호족 출신인 향리는
조세·부역·소송 등 행정 사무를 맡았으므로, 비록 수령의 보좌역이지만 실권은 매우
컸다. 이를 억제하기 위한 조치가 사심관 제도와 기인 제도였다.

(6) 고려 지방 행정의 특징
① 삼원적 구성：행정적 성격의 5도와 군사적 성격의 양계로 이원화되었고, 여기에 경기
가 더해져 크게 삼원적 구조로 운영되었다. 현종 이후로 경기가 지방관제로 개편되
고 고려 말에는 다른 지방과 같이 관찰사를 두었다. 양계는 변경 지역으로서 군사적
성격을 상당히 오래 유지하였으나, 공양왕 때 이르러 관찰사가 파견되는 등 고려 말
에 이르러 일원적 행정 구역으로의 개편이 시작되었다.
② 주현·속현 관계(영속 관계)：지방관이 파견되지 않은 속현이 다수 존재하였다. 따라서
영현(주현, 지방관이 파견된 현)을 중심으로 몇 개의 속현을 묶어 통치하였는데, 영
현과 속현의 관계는 읍사를 중심으로 이루어졌다. 읍사는 향리의 행정 기구로, 이를
통해 영현의 우두머리 향리(호장)가 인근 지역 향리들을 통솔하여 지방을 실질적으
로 통치하면서 영현의 지방관을 통해 중앙과 연결되었다.
③ 중간 체계의 미비：기본적으로 지방관이 파견된 주현들은 중앙 정부(상서도성)와 직접
연결되었으며, 5도가 설치되기 전에는 큰 읍을 계수관이라 하여 관내 주현들의 ✚ 향공
선상과 범죄자 심문 등 특정한 기능에서 상위 행정 구역 역할을 하도록 하였다.5 도
가 정비되고 안찰사가 파견된 후에도 계수관제는 여전히 남아있어 안찰사와 계수관
의 이원적 지방 제도가 운영되었다.
④ 다양한 위계의 행정 구역：도호부(군사적 목적), 목(행정적) 등의 대읍과 주군·현, 속
군·현 및 부곡, 향, 소, 처, 장 등의 행정 구역이 존재하여 행정 구역이 여러 단계로
구분되어 있었다.
⑤ ✚상피제의 미비：고려 시대에도 상피제를 시행하기는 했지만, 대부분의 지방 행정은
향리가 관할했고, 안찰사는 경관직이어서 상피제의 적용을 받지 않아 큰 효과는 없
었다.
3 군사 조직
(1) 중앙군
① 구성：중앙군은 국왕의 친위 부대인 2군과 수도 경비와 국경 방어를 담당하는 6위로 구성
되었다. 상장군, 대장군 등의 무관을 두어 지휘하게 하였는데, 무관들의 합좌 기관인
중방(重房)에서 군사 문제를 논의하였다. 2군이 6위보다 우위에 있었다.
* 응양군：규모는 1령(1천명)으로 가장 적으나 용호군보다 상위에 있었으며, 6위를
통솔하였다. 공학군, 근장이라고도 부르며, 응양군의 상장군은 중방의 수반이 되
었다.
* 용호군：견룡군이라고도 하며, 친위군·시위군의 성격을 가졌다.
* 6위：좌우위·신호위·흥위위 3위는 중앙군의 주력 부대로, 개경과 국경 방위를
맡았다. 이 외에 금오위는 치안·경찰, 천우위는 의장대, 감문위는 궁성문 수비 등
을 담당하였다.
② 중앙군의 지위：중앙군은 직업 군인으로 편성되었는데, 이들은 군적에 올라 군인전을 지
급받고 그 역은 자손에게 세습되었다. 결원이 생기면 농민✚번상병 중에서 충원하였으
며, 이 경우에 군인전을 지급하고 군적에 등록하였다.

(2) 지방군
군적에 오르지 못한 일반 농민으로 16세 이상의 장정들은 지방군으로 조직되었다. 지방
군은 국경 지방인 양계에 주둔하는 주진군(州鎭軍, 상비군)과 5도의 일반 군현에 주둔하는 주
현군(州縣軍, 예비군)으로 이루어졌다.
(3) 고려 시대의 특수 부대
구분 시기 역할
광군 정종
지방 호족의 군대를 연합하여 거란족 방어를 목적으로 편성, 청천강 유역에 배치,
후에 지방군으로 편입
별무반 숙종
윤관이 여진 정벌을 위해 조직, 신기군(기병), 신보군(보병), 항마군(승병), 도탕(跳
盪), 발화(發火)로 구성
삼별초 최우 집권기
야별초가 확대된 좌·우별초(치안 담당), 신의군(몽골에 잡혔던 포로)으로 구성, 대
몽 항쟁 전개
연호군 고려 말 왜구의 침입에 대비하여 설치, 가호별로 차출한 일종의 노비 군대

(4) 무신 합좌 기구
① 중방(重房)：중앙군인 2군 6위의 지휘관은 정3품의 상장군(上將軍)이었고, 부지휘관은
종3품의 대장군(大將軍)이었다. 상장군과 대장군이 무반의 합좌 기관인 중방을 구성하
여(총 16명) 군사 문제에 관한 회의를 하였는데, 가장 서열이 높은 응양군의 상장군
이 의장이 되었으며 반주(班主)라 칭하였다.
② 장군방：45령의 부대장인 정4품의 장군으로 구성되었다.
③ 낭장방：200명 규모의 단위 부대를 지휘하는 중랑장으로 구성되었다.
(5) 고려 말의 군사 제도
① ✚만호부：원나라의 영향을 받은 군사 기구로, 충렬왕 이후 설치되기 시작하였다. 공
민왕 때부터 자체적으로 만호 등의 관직을 내렸으며, 점차 고려의 군사 제도로 편입
되어 갔다. 조선 시대에 만호부는 모두 폐지되었지만, 수군만호·병마만호 등 무반의
종4품 외관직으로 남았다.

② 원수제：종전의 최고 지휘관인 도통사는 군대가 편성될 때의 임시직이었으나, 공민
왕 말부터 각도에 상설직으로 임명된 원수가 관할 도의 군사력을 관할·지휘하는 원
수제가 성립되었다. 각 도의 번상병은 형식상 2군 6위에 배치되었으나, 중앙군의 지
휘 체계가 무너져 사실상 출신도 원수의 지휘를 받게 되었고, 특정 원수가 관할 지역
의 군사를 오래 지휘하면서 사적인 지휘 체계가 형성되었다. 이는 우왕 때 요동 정벌
당시 이성계가 위화도 회군을 단행할 수 있는 배경이 되었다. 이후 공양왕3 년에 삼
군도총제부를 설치하고 이성계 자신이 삼군도총제사를 맡아 원수제를 약화시키면서
군사권을 완전히 장악하였다.
4 관리 등용 제도
(1) 과거 제도
① 시행 및 정비：광종 때 쌍기(최초의 지공거)의 건의로 왕권 강화를 위해 처음 시행하였
다(958). 성종 때 여러 규정이 생기면서 정비되었다.
② 과목
제술업(製述業) 시·부·송·책·논 등 문학적 재능과 대책 등을 시험하였는데, 가장 중시되었다.
명경업(明經業) <시경>, <서경>, <역경>, <춘추> 등 유교 경전에 대한 이해 능력을 시험하였다.
잡업(雜業) 의학·천문·음양지리와 율학·서학·산학 등 기술학을 시험하여 기술관을 채용하였다.
승과 교종시와 선종시로 나누어 시행하였는데, 합격자에게 법계를 주었다.
③ 절차
초시 개경, 서경을 비롯한 각 지역에서 시행하였다.
국자감시 초시 합격자인 상공(개경), 향공(지방), 빈공(외국인)을 대상으로 시행하였다.
예부시(동당시)
국자감시 합격자인 공사(貢士) 또는 진사(進士), 국자감에서 3년 이상 수학한 자, 현직
관리를 대상으로 시행하였다.
복시 국왕이 주재하여 예부시 합격자의 순위를 결정하는 시험으로, 시행이 일정치 않았다.
④ 응시 자격：법제적으로 양인 이상은 과거에 응시할 수 있었다. 실제로 제술업이나 명경업
에는 주로 귀족과 향리의 자제가, 잡업에는 백정 농민이 주로 응시하였다.


(2) ✚음서(蔭敍)
① 내용：공신과 종친 및 5품 이상 고위 관료의 자손 등은 과거를 거치지 않고도 관료가
될 수 있는 음서의 혜택을 받았다. 음서의 범위가 넓어 부계 후손 외에도 사위나 외손
자뿐만 아니라 수양자(收養子) 등에게도 음서가 주어졌다. 음서의 연령은 18세 이상
으로 규정되어 있지만, 대략 15세를 전후하여 관직에 취임하였으며, 10세 미만이 음
직을 받은 경우도 있었다.
② 성격：조선 시대와 달리 음서 출신도 승진에 특별한 한계가 없었고, 가문의 정치적 배경
이 크게 작용하여 대부분 5품 이상에 오를 수 있었다. 이에 따라 누대에 걸쳐 고위 관
료의 지위를 세습할 수 있었다. 이는 고려 관료 체제의 귀족적 특성을 보여 준다.


(3) 기타 방식
① 유일(遺逸)의 천거：고급 관료의 추천(연대 책임제가 수반됨)으로 학식과 재능, 덕행
이 뛰어나면서도 가세(家勢)가 빈약하여 벼슬길에 나가지 못한 인물을 천거하여 특
별히 중용하는 제도이다.
② 성중애마：성중관(내시 등 국왕 측근의 근시직)과 애마(궁중 숙위)는 귀족 자제에서
발탁하였으며, 고관 승진도 가능하였다.
3 문벌 귀족 사회의 성립과 동요 All 필기노트 p.043
1 문벌 귀족 사회의 성립
(1) 새로운 지배층의 등장
성종 이후 중앙 집권 체제가 확립됨에 따라 중앙에서 새로운 지배층이 형성되어 갔다. 이
들은 지방 호족 출신으로 중앙 관료가 된 계열과 신라 6두품 계통의 유학자였다.
(2) 문벌 귀족
① 문벌 귀족의 정치·경제적 독점：문벌 귀족은 과거와 음서를 통해 관직을 독점하고, 중
서문하성과 중추원의 재상이 되어 정국을 주도해 나갔다. 이들은 관직에 따라 과전
을 받고, 또 세습이 허용되는 공음전의 혜택을 받았을 뿐 아니라, 권력을 이용하여 불법
적으로 토지를 확대하여 경제력까지 거의 독점하였다.

② 혼인 관계 형성：귀족들은 비슷한 가문끼리 혼인 관계를 맺어 권력 기반을 더욱 공고
히 하였다. 특히 왕실과 혼인 관계를 맺어 외척으로서의 지위를 이용하여 정권을 장악
하기도 하였다.
(3) 사회적 갈등과 모순의 심화
① 지배층의 내분：문벌 귀족들은 자기 가문의 세력 확대를 위해 노력하였고, 새롭게 관
료로 진출하는 신진 세력과 문벌 귀족이 서로 대립하는 양상을 보이게 되었다.
② 측근 세력의 등장：문벌 귀족 중 특정 가문에 권력이 지나치게 집중되어 왕권을 위협할 정
도에 이르자, 왕은 신진 관료들을 기용하여 왕권을 강화하고 보좌하는 역할을 맡겼
다. 신진 관료들 역시 왕권과 밀착하여 문벌 귀족과 대립하며 성장하였다.
③ 모순의 폭발：이자겸의 난과 묘청의 서경 천도 운동은 이러한 문벌 귀족 사회의 모순으로
인한 정치 세력의 대립과 갈등이 표면으로 드러난 사건이었다.

=== 2. 이자겸의 난(1126)

==== (1) 배경
① 경원 이씨의 성장：11세기 이래 대표적 문벌 귀족인 경원 이씨 가문은 왕실의 외척이
되어 80여 년간 정권을 잡았다.
② 이자겸의 집권
* 권력 장악：이자겸은 예종의 측근 세력인 한안인 등을 몰아내고 자신의 외손자인 인
종을 왕위에 올린 뒤 다시 딸을 인종의 비로 출가시켰다. 왕의 외조부이자 장인인
이자겸의 권세는 왕권을 능가할 정도였다.
* 이자겸의 전횡：이자겸은 조선국공(朝鮮國公)의 책봉을 받고 숭덕부(崇德府)를 세
웠다. 지군국사(국사를 처리하는 사람)를 자칭하고, 사사로이 송과 외교 사절을
왕래하는 등 왕권을 무시하였으며, 나아가 십팔자(十八子= 李의 파자) 위왕설(爲
王說)을 믿어 스스로 왕이 되고자 인종을 독살하려 하였다.
③ 측근 세력의 반발：신진 관료 중심의 측근 세력은 이자겸의 권력 독점에 반발하였고,
인종도 지나치게 권력이 커진 이자겸을 제거하고자 하였다.

==== (2) 이자겸의 난(1126)
① 전개：이자겸을 제거하고자 한 인종의 계획이 사전에 발각되자, 이자겸은 척준경과
함께 난을 일으켜 인종을 가두고 정권을 장악하였다. 그러나 인종에게 회유된 척준
경에 의해 이자겸이 축출되고, 척준경도 정지상 등의 탄핵을 받아 축출되어 이자겸
세력은 몰락하였다.
② 결과：이자겸의 난으로 궁궐이 불타 민심이 흉흉해지고 왕실의 위신이 추락하였고, 중
앙 지배층 사이의 분열을 드러내어 문벌 귀족 사회의 붕괴를 촉진하는 계기가 되었다.

=== 3 묘청의 서경 천도 운동

==== (1) 배경
① 개경파와 서경파의 대립：이자겸의 난 이후 인종은 실추된 왕권을 회복하고 민생을 안
정시키며 국방력을 강화하기 위한 정치 개혁을 추진하였다. 이 과정에서 김부식을
중심으로 한 보수적 관리들과 묘청, 정지상을 중심으로 한 서경 출신의 개혁적 관리들 사
이에 대립 관계가 형성되었다. +
② 서경 천도 운동과 금국 정벌론：묘청 세력은 풍수지리설을 내세워 서경으로 도읍을 옮
겨, 보수적인 개경의 문벌 귀족 세력을 누르고 왕권을 강화하면서 자주적인 혁신 정
치를 시행하려 하였다. 이들은 서경에 대화궁이라는 궁궐을 짓고, 황제를 칭하고 독자적
인 연호를 사용할 것(✚칭제건원)과 금 정벌(정금론)을 주장하였다. 이에 인종은 이 주장
을 받아들여 서경에 대화궁을 짓고 그 안에 토착 신을 섬기는 팔성당을 설치하였다.
③ 개경파의 반발：김부식이 중심이 된 개경 귀족 세력은 유교 이념에 충실함으로써 사회
질서를 확립하자고 하였다.

==== (2) 묘청의 난(1135)
① 발생：묘청 세력은 서경 천도를 통한 정권 장악이 어렵게 되자 서경에서 난을 일으켰다. 국호
를 대위(大爲), 연호를 천개(天開)라 하고 서북 일대를 장악하였다. 이어 군사를 일으켜 ✚천견
충의군이라 칭하고 서경으로의 천도를 주장하며 개경으로 진격하려 하였다.
② 전개：김부식 등은 개경에 남아 있던 정지상·
백수한 등 묘청 일파를 처형한 뒤 관군을 이끌
고 서경 주변을 점령하여 1년여 만에 묘청의 난을 진압하였다.
③ 결과：개경 중심 문벌 귀족의 기반이 다시 공고해졌으며, 이에 따라 보수적 유교 사
상이 고려의 주류를 이루게 되었다. 그리고 분사 제도가 폐지되는 등 서경의 위상이
격하되고 고구려 계승 의식과 북벌에 대한 관심도 점차 약화되어 갔다.
④ 의의：묘청의 서경 천도 운동은 문벌 귀족 사회 내부의 분열과 지역 세력 간의 대립 ,
풍수지리설이 결부된 자주적 전통 사상과 사대적 유교 정치사상의 충돌, 고구려 계승 이념에 대
한 이견과 갈등 등이 얽혀 일어난 것으로, 귀족 사회 내부의 모순을 드러낸 것이었다.

== 4 고려 전기의 대외 관계

=== 1 고려 초기의 대외 관계

==== (1) 북진 정책
① 국제 정세：고려 초기 중국 지역은 당이 망하고 5대 10국의 혼란기(907~960)였으므로 고려는 자주적 외교를 추진할 수 있었다.

② 내용：태조는 고구려의 후계자임을 자처해 국호를 ‘고려’라 하고, 고구려의 옛 영토를 회복하려는 북진 정책을 추진해 서경(西京, 평양)을 중시하고 국경선을 청천강 유역까지 확대하였다. 또한, 거란의 침략으로 발해가 멸망하자, 고구려 계통의 발해 유민을 받아들여 포섭하였다. 아울러 거란에 대해서는 강경하게 대응하였다.

(2) 송과의 관계
① 친송 정책：송이 중국을 통일하고(960) 거란(요)과 대치하자, 고려는 경제적·문화적
필요에서 광종 13년(962) 송과 정식으로 국교를 맺었다. 이후 거란의 침입으로 일시
적으로 송과 국교가 단절되기도 하였으나, 문종 때 성장한 국력을 바탕으로 거란의
묵인 속에 송과 다시 수교하였다.
② 송의 대응：송은 거란을 견제하기 위해 고려와의 수교를 중시하여 고려의 사신을 조공
사가 아닌 국신사라 하며 고려를 송과 대등한 국가로 대우하였다. 그리고 추밀원에
서 고려 사신을 접대하여 외교 관계를 맺은 여러 나라 중 요와 함께 최고 지위로 대접
하였다.
③ 현실적 실리 외교：고려는 거란을 협공하자는 북송의 요청을 거부하고, 송이 금(여진)
과 손잡을 때 이를 만류하기도 하는 등 국제 판도의 변화를 파악하였다. 남송은 고려
와 연합하여 금을 치려는 연려제금책을 수립하고 요와 금의 분쟁에 고려가 개입하기
를 희망하였으나 고려는 이를 거절하였다. 또한 고려는 금과의 교섭을 도와달라는
송의 요청(가도 문제)도 거절하는 등 실리에 따라 독자적인 행보를 보였다.

